# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['PipelineArgs', 'Pipeline']

@pulumi.input_type
class PipelineArgs:
    def __init__(__self__, *,
                 cluster_api_url: pulumi.Input[_builtins.str],
                 config_yaml: pulumi.Input[_builtins.str],
                 display_name: pulumi.Input[_builtins.str],
                 allow_deletion: Optional[pulumi.Input[_builtins.bool]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 resources: Optional[pulumi.Input['PipelineResourcesArgs']] = None,
                 service_account: Optional[pulumi.Input['PipelineServiceAccountArgs']] = None,
                 state: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 timeouts: Optional[pulumi.Input['PipelineTimeoutsArgs']] = None):
        """
        The set of arguments for constructing a Pipeline resource.
        :param pulumi.Input[_builtins.str] cluster_api_url: The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports.
        :param pulumi.Input[_builtins.str] config_yaml: The Redpanda Connect pipeline configuration in YAML format. See https://docs.redpanda.com/redpanda-cloud/develop/connect/configuration/about for configuration details.
        :param pulumi.Input[_builtins.str] display_name: User-friendly display name for the pipeline.
        :param pulumi.Input[_builtins.bool] allow_deletion: Allows deletion of the pipeline. Default is false. Must be set to true to delete the resource.
        :param pulumi.Input[_builtins.str] description: Optional description of the pipeline.
        :param pulumi.Input['PipelineResourcesArgs'] resources: Resource allocation for the pipeline.
        :param pulumi.Input['PipelineServiceAccountArgs'] service_account: Service account credentials for the pipeline. Used to authenticate the pipeline with external services.
        :param pulumi.Input[_builtins.str] state: Desired state of the pipeline: 'running' or 'stopped'. The provider will ensure the pipeline reaches this state after create/update operations.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: Key-value pairs to tag the pipeline for organization and filtering.
        """
        pulumi.set(__self__, "cluster_api_url", cluster_api_url)
        pulumi.set(__self__, "config_yaml", config_yaml)
        pulumi.set(__self__, "display_name", display_name)
        if allow_deletion is not None:
            pulumi.set(__self__, "allow_deletion", allow_deletion)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if resources is not None:
            pulumi.set(__self__, "resources", resources)
        if service_account is not None:
            pulumi.set(__self__, "service_account", service_account)
        if state is not None:
            pulumi.set(__self__, "state", state)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if timeouts is not None:
            pulumi.set(__self__, "timeouts", timeouts)

    @_builtins.property
    @pulumi.getter(name="clusterApiUrl")
    def cluster_api_url(self) -> pulumi.Input[_builtins.str]:
        """
        The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports.
        """
        return pulumi.get(self, "cluster_api_url")

    @cluster_api_url.setter
    def cluster_api_url(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "cluster_api_url", value)

    @_builtins.property
    @pulumi.getter(name="configYaml")
    def config_yaml(self) -> pulumi.Input[_builtins.str]:
        """
        The Redpanda Connect pipeline configuration in YAML format. See https://docs.redpanda.com/redpanda-cloud/develop/connect/configuration/about for configuration details.
        """
        return pulumi.get(self, "config_yaml")

    @config_yaml.setter
    def config_yaml(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "config_yaml", value)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Input[_builtins.str]:
        """
        User-friendly display name for the pipeline.
        """
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "display_name", value)

    @_builtins.property
    @pulumi.getter(name="allowDeletion")
    def allow_deletion(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Allows deletion of the pipeline. Default is false. Must be set to true to delete the resource.
        """
        return pulumi.get(self, "allow_deletion")

    @allow_deletion.setter
    def allow_deletion(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "allow_deletion", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Optional description of the pipeline.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def resources(self) -> Optional[pulumi.Input['PipelineResourcesArgs']]:
        """
        Resource allocation for the pipeline.
        """
        return pulumi.get(self, "resources")

    @resources.setter
    def resources(self, value: Optional[pulumi.Input['PipelineResourcesArgs']]):
        pulumi.set(self, "resources", value)

    @_builtins.property
    @pulumi.getter(name="serviceAccount")
    def service_account(self) -> Optional[pulumi.Input['PipelineServiceAccountArgs']]:
        """
        Service account credentials for the pipeline. Used to authenticate the pipeline with external services.
        """
        return pulumi.get(self, "service_account")

    @service_account.setter
    def service_account(self, value: Optional[pulumi.Input['PipelineServiceAccountArgs']]):
        pulumi.set(self, "service_account", value)

    @_builtins.property
    @pulumi.getter
    def state(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Desired state of the pipeline: 'running' or 'stopped'. The provider will ensure the pipeline reaches this state after create/update operations.
        """
        return pulumi.get(self, "state")

    @state.setter
    def state(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "state", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Key-value pairs to tag the pipeline for organization and filtering.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter
    def timeouts(self) -> Optional[pulumi.Input['PipelineTimeoutsArgs']]:
        return pulumi.get(self, "timeouts")

    @timeouts.setter
    def timeouts(self, value: Optional[pulumi.Input['PipelineTimeoutsArgs']]):
        pulumi.set(self, "timeouts", value)


@pulumi.input_type
class _PipelineState:
    def __init__(__self__, *,
                 allow_deletion: Optional[pulumi.Input[_builtins.bool]] = None,
                 cluster_api_url: Optional[pulumi.Input[_builtins.str]] = None,
                 config_yaml: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 display_name: Optional[pulumi.Input[_builtins.str]] = None,
                 resources: Optional[pulumi.Input['PipelineResourcesArgs']] = None,
                 service_account: Optional[pulumi.Input['PipelineServiceAccountArgs']] = None,
                 state: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 timeouts: Optional[pulumi.Input['PipelineTimeoutsArgs']] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Pipeline resources.
        :param pulumi.Input[_builtins.bool] allow_deletion: Allows deletion of the pipeline. Default is false. Must be set to true to delete the resource.
        :param pulumi.Input[_builtins.str] cluster_api_url: The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports.
        :param pulumi.Input[_builtins.str] config_yaml: The Redpanda Connect pipeline configuration in YAML format. See https://docs.redpanda.com/redpanda-cloud/develop/connect/configuration/about for configuration details.
        :param pulumi.Input[_builtins.str] description: Optional description of the pipeline.
        :param pulumi.Input[_builtins.str] display_name: User-friendly display name for the pipeline.
        :param pulumi.Input['PipelineResourcesArgs'] resources: Resource allocation for the pipeline.
        :param pulumi.Input['PipelineServiceAccountArgs'] service_account: Service account credentials for the pipeline. Used to authenticate the pipeline with external services.
        :param pulumi.Input[_builtins.str] state: Desired state of the pipeline: 'running' or 'stopped'. The provider will ensure the pipeline reaches this state after create/update operations.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: Key-value pairs to tag the pipeline for organization and filtering.
        :param pulumi.Input[_builtins.str] url: URL to connect to the pipeline's HTTP server, if applicable.
        """
        if allow_deletion is not None:
            pulumi.set(__self__, "allow_deletion", allow_deletion)
        if cluster_api_url is not None:
            pulumi.set(__self__, "cluster_api_url", cluster_api_url)
        if config_yaml is not None:
            pulumi.set(__self__, "config_yaml", config_yaml)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if display_name is not None:
            pulumi.set(__self__, "display_name", display_name)
        if resources is not None:
            pulumi.set(__self__, "resources", resources)
        if service_account is not None:
            pulumi.set(__self__, "service_account", service_account)
        if state is not None:
            pulumi.set(__self__, "state", state)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if timeouts is not None:
            pulumi.set(__self__, "timeouts", timeouts)
        if url is not None:
            pulumi.set(__self__, "url", url)

    @_builtins.property
    @pulumi.getter(name="allowDeletion")
    def allow_deletion(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Allows deletion of the pipeline. Default is false. Must be set to true to delete the resource.
        """
        return pulumi.get(self, "allow_deletion")

    @allow_deletion.setter
    def allow_deletion(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "allow_deletion", value)

    @_builtins.property
    @pulumi.getter(name="clusterApiUrl")
    def cluster_api_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports.
        """
        return pulumi.get(self, "cluster_api_url")

    @cluster_api_url.setter
    def cluster_api_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "cluster_api_url", value)

    @_builtins.property
    @pulumi.getter(name="configYaml")
    def config_yaml(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The Redpanda Connect pipeline configuration in YAML format. See https://docs.redpanda.com/redpanda-cloud/develop/connect/configuration/about for configuration details.
        """
        return pulumi.get(self, "config_yaml")

    @config_yaml.setter
    def config_yaml(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "config_yaml", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Optional description of the pipeline.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        User-friendly display name for the pipeline.
        """
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "display_name", value)

    @_builtins.property
    @pulumi.getter
    def resources(self) -> Optional[pulumi.Input['PipelineResourcesArgs']]:
        """
        Resource allocation for the pipeline.
        """
        return pulumi.get(self, "resources")

    @resources.setter
    def resources(self, value: Optional[pulumi.Input['PipelineResourcesArgs']]):
        pulumi.set(self, "resources", value)

    @_builtins.property
    @pulumi.getter(name="serviceAccount")
    def service_account(self) -> Optional[pulumi.Input['PipelineServiceAccountArgs']]:
        """
        Service account credentials for the pipeline. Used to authenticate the pipeline with external services.
        """
        return pulumi.get(self, "service_account")

    @service_account.setter
    def service_account(self, value: Optional[pulumi.Input['PipelineServiceAccountArgs']]):
        pulumi.set(self, "service_account", value)

    @_builtins.property
    @pulumi.getter
    def state(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Desired state of the pipeline: 'running' or 'stopped'. The provider will ensure the pipeline reaches this state after create/update operations.
        """
        return pulumi.get(self, "state")

    @state.setter
    def state(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "state", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Key-value pairs to tag the pipeline for organization and filtering.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter
    def timeouts(self) -> Optional[pulumi.Input['PipelineTimeoutsArgs']]:
        return pulumi.get(self, "timeouts")

    @timeouts.setter
    def timeouts(self, value: Optional[pulumi.Input['PipelineTimeoutsArgs']]):
        pulumi.set(self, "timeouts", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        URL to connect to the pipeline's HTTP server, if applicable.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "url", value)


@pulumi.type_token("redpanda:index/pipeline:Pipeline")
class Pipeline(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allow_deletion: Optional[pulumi.Input[_builtins.bool]] = None,
                 cluster_api_url: Optional[pulumi.Input[_builtins.str]] = None,
                 config_yaml: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 display_name: Optional[pulumi.Input[_builtins.str]] = None,
                 resources: Optional[pulumi.Input[Union['PipelineResourcesArgs', 'PipelineResourcesArgsDict']]] = None,
                 service_account: Optional[pulumi.Input[Union['PipelineServiceAccountArgs', 'PipelineServiceAccountArgsDict']]] = None,
                 state: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 timeouts: Optional[pulumi.Input[Union['PipelineTimeoutsArgs', 'PipelineTimeoutsArgsDict']]] = None,
                 __props__=None):
        """
        Create a Pipeline resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] allow_deletion: Allows deletion of the pipeline. Default is false. Must be set to true to delete the resource.
        :param pulumi.Input[_builtins.str] cluster_api_url: The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports.
        :param pulumi.Input[_builtins.str] config_yaml: The Redpanda Connect pipeline configuration in YAML format. See https://docs.redpanda.com/redpanda-cloud/develop/connect/configuration/about for configuration details.
        :param pulumi.Input[_builtins.str] description: Optional description of the pipeline.
        :param pulumi.Input[_builtins.str] display_name: User-friendly display name for the pipeline.
        :param pulumi.Input[Union['PipelineResourcesArgs', 'PipelineResourcesArgsDict']] resources: Resource allocation for the pipeline.
        :param pulumi.Input[Union['PipelineServiceAccountArgs', 'PipelineServiceAccountArgsDict']] service_account: Service account credentials for the pipeline. Used to authenticate the pipeline with external services.
        :param pulumi.Input[_builtins.str] state: Desired state of the pipeline: 'running' or 'stopped'. The provider will ensure the pipeline reaches this state after create/update operations.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: Key-value pairs to tag the pipeline for organization and filtering.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: PipelineArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Pipeline resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param PipelineArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(PipelineArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allow_deletion: Optional[pulumi.Input[_builtins.bool]] = None,
                 cluster_api_url: Optional[pulumi.Input[_builtins.str]] = None,
                 config_yaml: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 display_name: Optional[pulumi.Input[_builtins.str]] = None,
                 resources: Optional[pulumi.Input[Union['PipelineResourcesArgs', 'PipelineResourcesArgsDict']]] = None,
                 service_account: Optional[pulumi.Input[Union['PipelineServiceAccountArgs', 'PipelineServiceAccountArgsDict']]] = None,
                 state: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 timeouts: Optional[pulumi.Input[Union['PipelineTimeoutsArgs', 'PipelineTimeoutsArgsDict']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = PipelineArgs.__new__(PipelineArgs)

            __props__.__dict__["allow_deletion"] = allow_deletion
            if cluster_api_url is None and not opts.urn:
                raise TypeError("Missing required property 'cluster_api_url'")
            __props__.__dict__["cluster_api_url"] = cluster_api_url
            if config_yaml is None and not opts.urn:
                raise TypeError("Missing required property 'config_yaml'")
            __props__.__dict__["config_yaml"] = None if config_yaml is None else pulumi.Output.secret(config_yaml)
            __props__.__dict__["description"] = description
            if display_name is None and not opts.urn:
                raise TypeError("Missing required property 'display_name'")
            __props__.__dict__["display_name"] = display_name
            __props__.__dict__["resources"] = resources
            __props__.__dict__["service_account"] = service_account
            __props__.__dict__["state"] = state
            __props__.__dict__["tags"] = tags
            __props__.__dict__["timeouts"] = timeouts
            __props__.__dict__["url"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["configYaml"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Pipeline, __self__).__init__(
            'redpanda:index/pipeline:Pipeline',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            allow_deletion: Optional[pulumi.Input[_builtins.bool]] = None,
            cluster_api_url: Optional[pulumi.Input[_builtins.str]] = None,
            config_yaml: Optional[pulumi.Input[_builtins.str]] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            display_name: Optional[pulumi.Input[_builtins.str]] = None,
            resources: Optional[pulumi.Input[Union['PipelineResourcesArgs', 'PipelineResourcesArgsDict']]] = None,
            service_account: Optional[pulumi.Input[Union['PipelineServiceAccountArgs', 'PipelineServiceAccountArgsDict']]] = None,
            state: Optional[pulumi.Input[_builtins.str]] = None,
            tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            timeouts: Optional[pulumi.Input[Union['PipelineTimeoutsArgs', 'PipelineTimeoutsArgsDict']]] = None,
            url: Optional[pulumi.Input[_builtins.str]] = None) -> 'Pipeline':
        """
        Get an existing Pipeline resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] allow_deletion: Allows deletion of the pipeline. Default is false. Must be set to true to delete the resource.
        :param pulumi.Input[_builtins.str] cluster_api_url: The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports.
        :param pulumi.Input[_builtins.str] config_yaml: The Redpanda Connect pipeline configuration in YAML format. See https://docs.redpanda.com/redpanda-cloud/develop/connect/configuration/about for configuration details.
        :param pulumi.Input[_builtins.str] description: Optional description of the pipeline.
        :param pulumi.Input[_builtins.str] display_name: User-friendly display name for the pipeline.
        :param pulumi.Input[Union['PipelineResourcesArgs', 'PipelineResourcesArgsDict']] resources: Resource allocation for the pipeline.
        :param pulumi.Input[Union['PipelineServiceAccountArgs', 'PipelineServiceAccountArgsDict']] service_account: Service account credentials for the pipeline. Used to authenticate the pipeline with external services.
        :param pulumi.Input[_builtins.str] state: Desired state of the pipeline: 'running' or 'stopped'. The provider will ensure the pipeline reaches this state after create/update operations.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: Key-value pairs to tag the pipeline for organization and filtering.
        :param pulumi.Input[_builtins.str] url: URL to connect to the pipeline's HTTP server, if applicable.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _PipelineState.__new__(_PipelineState)

        __props__.__dict__["allow_deletion"] = allow_deletion
        __props__.__dict__["cluster_api_url"] = cluster_api_url
        __props__.__dict__["config_yaml"] = config_yaml
        __props__.__dict__["description"] = description
        __props__.__dict__["display_name"] = display_name
        __props__.__dict__["resources"] = resources
        __props__.__dict__["service_account"] = service_account
        __props__.__dict__["state"] = state
        __props__.__dict__["tags"] = tags
        __props__.__dict__["timeouts"] = timeouts
        __props__.__dict__["url"] = url
        return Pipeline(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="allowDeletion")
    def allow_deletion(self) -> pulumi.Output[_builtins.bool]:
        """
        Allows deletion of the pipeline. Default is false. Must be set to true to delete the resource.
        """
        return pulumi.get(self, "allow_deletion")

    @_builtins.property
    @pulumi.getter(name="clusterApiUrl")
    def cluster_api_url(self) -> pulumi.Output[_builtins.str]:
        """
        The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports.
        """
        return pulumi.get(self, "cluster_api_url")

    @_builtins.property
    @pulumi.getter(name="configYaml")
    def config_yaml(self) -> pulumi.Output[_builtins.str]:
        """
        The Redpanda Connect pipeline configuration in YAML format. See https://docs.redpanda.com/redpanda-cloud/develop/connect/configuration/about for configuration details.
        """
        return pulumi.get(self, "config_yaml")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Optional description of the pipeline.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Output[_builtins.str]:
        """
        User-friendly display name for the pipeline.
        """
        return pulumi.get(self, "display_name")

    @_builtins.property
    @pulumi.getter
    def resources(self) -> pulumi.Output['outputs.PipelineResources']:
        """
        Resource allocation for the pipeline.
        """
        return pulumi.get(self, "resources")

    @_builtins.property
    @pulumi.getter(name="serviceAccount")
    def service_account(self) -> pulumi.Output[Optional['outputs.PipelineServiceAccount']]:
        """
        Service account credentials for the pipeline. Used to authenticate the pipeline with external services.
        """
        return pulumi.get(self, "service_account")

    @_builtins.property
    @pulumi.getter
    def state(self) -> pulumi.Output[_builtins.str]:
        """
        Desired state of the pipeline: 'running' or 'stopped'. The provider will ensure the pipeline reaches this state after create/update operations.
        """
        return pulumi.get(self, "state")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Key-value pairs to tag the pipeline for organization and filtering.
        """
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter
    def timeouts(self) -> pulumi.Output[Optional['outputs.PipelineTimeouts']]:
        return pulumi.get(self, "timeouts")

    @_builtins.property
    @pulumi.getter
    def url(self) -> pulumi.Output[_builtins.str]:
        """
        URL to connect to the pipeline's HTTP server, if applicable.
        """
        return pulumi.get(self, "url")

