# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['UserArgs', 'User']

@pulumi.input_type
class UserArgs:
    def __init__(__self__, *,
                 cluster_api_url: pulumi.Input[_builtins.str],
                 allow_deletion: Optional[pulumi.Input[_builtins.bool]] = None,
                 mechanism: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 password: Optional[pulumi.Input[_builtins.str]] = None,
                 password_wo: Optional[pulumi.Input[_builtins.str]] = None,
                 password_wo_version: Optional[pulumi.Input[_builtins.int]] = None):
        """
        The set of arguments for constructing a User resource.
        :param pulumi.Input[_builtins.str] cluster_api_url: The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports
        :param pulumi.Input[_builtins.bool] allow_deletion: Allows deletion of the user. If false, the user cannot be deleted and the resource will be removed from the state on destruction. Defaults to false.
        :param pulumi.Input[_builtins.str] mechanism: Which authentication method to use, see https://docs.redpanda.com/current/manage/security/authentication/ for more information
        :param pulumi.Input[_builtins.str] name: Name of the user, must be unique
        :param pulumi.Input[_builtins.str] password: Password of the user. Deprecated: use password_wo instead to avoid storing password in state.
        :param pulumi.Input[_builtins.str] password_wo: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               Password of the user (write-only, not stored in state). Requires Terraform 1.11+. Either password or password_wo must be set.
        :param pulumi.Input[_builtins.int] password_wo_version: Version number for password_wo. Increment this value to trigger a password update when using password_wo.
        """
        pulumi.set(__self__, "cluster_api_url", cluster_api_url)
        if allow_deletion is not None:
            pulumi.set(__self__, "allow_deletion", allow_deletion)
        if mechanism is not None:
            pulumi.set(__self__, "mechanism", mechanism)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if password is not None:
            warnings.warn("""Use password_wo instead to avoid storing password in Terraform state""", DeprecationWarning)
            pulumi.log.warn("""password is deprecated: Use password_wo instead to avoid storing password in Terraform state""")
        if password is not None:
            pulumi.set(__self__, "password", password)
        if password_wo is not None:
            pulumi.set(__self__, "password_wo", password_wo)
        if password_wo_version is not None:
            pulumi.set(__self__, "password_wo_version", password_wo_version)

    @_builtins.property
    @pulumi.getter(name="clusterApiUrl")
    def cluster_api_url(self) -> pulumi.Input[_builtins.str]:
        """
        The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports
        """
        return pulumi.get(self, "cluster_api_url")

    @cluster_api_url.setter
    def cluster_api_url(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "cluster_api_url", value)

    @_builtins.property
    @pulumi.getter(name="allowDeletion")
    def allow_deletion(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Allows deletion of the user. If false, the user cannot be deleted and the resource will be removed from the state on destruction. Defaults to false.
        """
        return pulumi.get(self, "allow_deletion")

    @allow_deletion.setter
    def allow_deletion(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "allow_deletion", value)

    @_builtins.property
    @pulumi.getter
    def mechanism(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Which authentication method to use, see https://docs.redpanda.com/current/manage/security/authentication/ for more information
        """
        return pulumi.get(self, "mechanism")

    @mechanism.setter
    def mechanism(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "mechanism", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of the user, must be unique
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""Use password_wo instead to avoid storing password in Terraform state""")
    def password(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Password of the user. Deprecated: use password_wo instead to avoid storing password in state.
        """
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "password", value)

    @_builtins.property
    @pulumi.getter(name="passwordWo")
    def password_wo(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        Password of the user (write-only, not stored in state). Requires Terraform 1.11+. Either password or password_wo must be set.
        """
        return pulumi.get(self, "password_wo")

    @password_wo.setter
    def password_wo(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "password_wo", value)

    @_builtins.property
    @pulumi.getter(name="passwordWoVersion")
    def password_wo_version(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Version number for password_wo. Increment this value to trigger a password update when using password_wo.
        """
        return pulumi.get(self, "password_wo_version")

    @password_wo_version.setter
    def password_wo_version(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "password_wo_version", value)


@pulumi.input_type
class _UserState:
    def __init__(__self__, *,
                 allow_deletion: Optional[pulumi.Input[_builtins.bool]] = None,
                 cluster_api_url: Optional[pulumi.Input[_builtins.str]] = None,
                 mechanism: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 password: Optional[pulumi.Input[_builtins.str]] = None,
                 password_wo: Optional[pulumi.Input[_builtins.str]] = None,
                 password_wo_version: Optional[pulumi.Input[_builtins.int]] = None):
        """
        Input properties used for looking up and filtering User resources.
        :param pulumi.Input[_builtins.bool] allow_deletion: Allows deletion of the user. If false, the user cannot be deleted and the resource will be removed from the state on destruction. Defaults to false.
        :param pulumi.Input[_builtins.str] cluster_api_url: The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports
        :param pulumi.Input[_builtins.str] mechanism: Which authentication method to use, see https://docs.redpanda.com/current/manage/security/authentication/ for more information
        :param pulumi.Input[_builtins.str] name: Name of the user, must be unique
        :param pulumi.Input[_builtins.str] password: Password of the user. Deprecated: use password_wo instead to avoid storing password in state.
        :param pulumi.Input[_builtins.str] password_wo: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               Password of the user (write-only, not stored in state). Requires Terraform 1.11+. Either password or password_wo must be set.
        :param pulumi.Input[_builtins.int] password_wo_version: Version number for password_wo. Increment this value to trigger a password update when using password_wo.
        """
        if allow_deletion is not None:
            pulumi.set(__self__, "allow_deletion", allow_deletion)
        if cluster_api_url is not None:
            pulumi.set(__self__, "cluster_api_url", cluster_api_url)
        if mechanism is not None:
            pulumi.set(__self__, "mechanism", mechanism)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if password is not None:
            warnings.warn("""Use password_wo instead to avoid storing password in Terraform state""", DeprecationWarning)
            pulumi.log.warn("""password is deprecated: Use password_wo instead to avoid storing password in Terraform state""")
        if password is not None:
            pulumi.set(__self__, "password", password)
        if password_wo is not None:
            pulumi.set(__self__, "password_wo", password_wo)
        if password_wo_version is not None:
            pulumi.set(__self__, "password_wo_version", password_wo_version)

    @_builtins.property
    @pulumi.getter(name="allowDeletion")
    def allow_deletion(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Allows deletion of the user. If false, the user cannot be deleted and the resource will be removed from the state on destruction. Defaults to false.
        """
        return pulumi.get(self, "allow_deletion")

    @allow_deletion.setter
    def allow_deletion(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "allow_deletion", value)

    @_builtins.property
    @pulumi.getter(name="clusterApiUrl")
    def cluster_api_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports
        """
        return pulumi.get(self, "cluster_api_url")

    @cluster_api_url.setter
    def cluster_api_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "cluster_api_url", value)

    @_builtins.property
    @pulumi.getter
    def mechanism(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Which authentication method to use, see https://docs.redpanda.com/current/manage/security/authentication/ for more information
        """
        return pulumi.get(self, "mechanism")

    @mechanism.setter
    def mechanism(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "mechanism", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of the user, must be unique
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""Use password_wo instead to avoid storing password in Terraform state""")
    def password(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Password of the user. Deprecated: use password_wo instead to avoid storing password in state.
        """
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "password", value)

    @_builtins.property
    @pulumi.getter(name="passwordWo")
    def password_wo(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        Password of the user (write-only, not stored in state). Requires Terraform 1.11+. Either password or password_wo must be set.
        """
        return pulumi.get(self, "password_wo")

    @password_wo.setter
    def password_wo(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "password_wo", value)

    @_builtins.property
    @pulumi.getter(name="passwordWoVersion")
    def password_wo_version(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Version number for password_wo. Increment this value to trigger a password update when using password_wo.
        """
        return pulumi.get(self, "password_wo_version")

    @password_wo_version.setter
    def password_wo_version(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "password_wo_version", value)


@pulumi.type_token("redpanda:index/user:User")
class User(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allow_deletion: Optional[pulumi.Input[_builtins.bool]] = None,
                 cluster_api_url: Optional[pulumi.Input[_builtins.str]] = None,
                 mechanism: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 password: Optional[pulumi.Input[_builtins.str]] = None,
                 password_wo: Optional[pulumi.Input[_builtins.str]] = None,
                 password_wo_version: Optional[pulumi.Input[_builtins.int]] = None,
                 __props__=None):
        """
        Create a User resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] allow_deletion: Allows deletion of the user. If false, the user cannot be deleted and the resource will be removed from the state on destruction. Defaults to false.
        :param pulumi.Input[_builtins.str] cluster_api_url: The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports
        :param pulumi.Input[_builtins.str] mechanism: Which authentication method to use, see https://docs.redpanda.com/current/manage/security/authentication/ for more information
        :param pulumi.Input[_builtins.str] name: Name of the user, must be unique
        :param pulumi.Input[_builtins.str] password: Password of the user. Deprecated: use password_wo instead to avoid storing password in state.
        :param pulumi.Input[_builtins.str] password_wo: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               Password of the user (write-only, not stored in state). Requires Terraform 1.11+. Either password or password_wo must be set.
        :param pulumi.Input[_builtins.int] password_wo_version: Version number for password_wo. Increment this value to trigger a password update when using password_wo.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: UserArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a User resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param UserArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(UserArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allow_deletion: Optional[pulumi.Input[_builtins.bool]] = None,
                 cluster_api_url: Optional[pulumi.Input[_builtins.str]] = None,
                 mechanism: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 password: Optional[pulumi.Input[_builtins.str]] = None,
                 password_wo: Optional[pulumi.Input[_builtins.str]] = None,
                 password_wo_version: Optional[pulumi.Input[_builtins.int]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = UserArgs.__new__(UserArgs)

            __props__.__dict__["allow_deletion"] = allow_deletion
            if cluster_api_url is None and not opts.urn:
                raise TypeError("Missing required property 'cluster_api_url'")
            __props__.__dict__["cluster_api_url"] = cluster_api_url
            __props__.__dict__["mechanism"] = mechanism
            __props__.__dict__["name"] = name
            __props__.__dict__["password"] = None if password is None else pulumi.Output.secret(password)
            __props__.__dict__["password_wo"] = None if password_wo is None else pulumi.Output.secret(password_wo)
            __props__.__dict__["password_wo_version"] = password_wo_version
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["password", "passwordWo"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(User, __self__).__init__(
            'redpanda:index/user:User',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            allow_deletion: Optional[pulumi.Input[_builtins.bool]] = None,
            cluster_api_url: Optional[pulumi.Input[_builtins.str]] = None,
            mechanism: Optional[pulumi.Input[_builtins.str]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            password: Optional[pulumi.Input[_builtins.str]] = None,
            password_wo: Optional[pulumi.Input[_builtins.str]] = None,
            password_wo_version: Optional[pulumi.Input[_builtins.int]] = None) -> 'User':
        """
        Get an existing User resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] allow_deletion: Allows deletion of the user. If false, the user cannot be deleted and the resource will be removed from the state on destruction. Defaults to false.
        :param pulumi.Input[_builtins.str] cluster_api_url: The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports
        :param pulumi.Input[_builtins.str] mechanism: Which authentication method to use, see https://docs.redpanda.com/current/manage/security/authentication/ for more information
        :param pulumi.Input[_builtins.str] name: Name of the user, must be unique
        :param pulumi.Input[_builtins.str] password: Password of the user. Deprecated: use password_wo instead to avoid storing password in state.
        :param pulumi.Input[_builtins.str] password_wo: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               Password of the user (write-only, not stored in state). Requires Terraform 1.11+. Either password or password_wo must be set.
        :param pulumi.Input[_builtins.int] password_wo_version: Version number for password_wo. Increment this value to trigger a password update when using password_wo.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _UserState.__new__(_UserState)

        __props__.__dict__["allow_deletion"] = allow_deletion
        __props__.__dict__["cluster_api_url"] = cluster_api_url
        __props__.__dict__["mechanism"] = mechanism
        __props__.__dict__["name"] = name
        __props__.__dict__["password"] = password
        __props__.__dict__["password_wo"] = password_wo
        __props__.__dict__["password_wo_version"] = password_wo_version
        return User(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="allowDeletion")
    def allow_deletion(self) -> pulumi.Output[_builtins.bool]:
        """
        Allows deletion of the user. If false, the user cannot be deleted and the resource will be removed from the state on destruction. Defaults to false.
        """
        return pulumi.get(self, "allow_deletion")

    @_builtins.property
    @pulumi.getter(name="clusterApiUrl")
    def cluster_api_url(self) -> pulumi.Output[_builtins.str]:
        """
        The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports
        """
        return pulumi.get(self, "cluster_api_url")

    @_builtins.property
    @pulumi.getter
    def mechanism(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Which authentication method to use, see https://docs.redpanda.com/current/manage/security/authentication/ for more information
        """
        return pulumi.get(self, "mechanism")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the user, must be unique
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""Use password_wo instead to avoid storing password in Terraform state""")
    def password(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Password of the user. Deprecated: use password_wo instead to avoid storing password in state.
        """
        return pulumi.get(self, "password")

    @_builtins.property
    @pulumi.getter(name="passwordWo")
    def password_wo(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        Password of the user (write-only, not stored in state). Requires Terraform 1.11+. Either password or password_wo must be set.
        """
        return pulumi.get(self, "password_wo")

    @_builtins.property
    @pulumi.getter(name="passwordWoVersion")
    def password_wo_version(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Version number for password_wo. Increment this value to trigger a password update when using password_wo.
        """
        return pulumi.get(self, "password_wo_version")

