// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda
{
    public static class GetCluster
    {
        public static Task<GetClusterResult> InvokeAsync(GetClusterArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetClusterResult>("redpanda:index/getCluster:getCluster", args ?? new GetClusterArgs(), options.WithDefaults());

        public static Output<GetClusterResult> Invoke(GetClusterInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetClusterResult>("redpanda:index/getCluster:getCluster", args ?? new GetClusterInvokeArgs(), options.WithDefaults());

        public static Output<GetClusterResult> Invoke(GetClusterInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetClusterResult>("redpanda:index/getCluster:getCluster", args ?? new GetClusterInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetClusterArgs : global::Pulumi.InvokeArgs
    {
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        [Input("timeouts")]
        public Inputs.GetClusterTimeoutsArgs? Timeouts { get; set; }

        public GetClusterArgs()
        {
        }
        public static new GetClusterArgs Empty => new GetClusterArgs();
    }

    public sealed class GetClusterInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        [Input("timeouts")]
        public Input<Inputs.GetClusterTimeoutsInputArgs>? Timeouts { get; set; }

        public GetClusterInvokeArgs()
        {
        }
        public static new GetClusterInvokeArgs Empty => new GetClusterInvokeArgs();
    }


    [OutputType]
    public sealed class GetClusterResult
    {
        public readonly bool AllowDeletion;
        public readonly Outputs.GetClusterAwsPrivateLinkResult AwsPrivateLink;
        public readonly Outputs.GetClusterAzurePrivateLinkResult AzurePrivateLink;
        public readonly string CloudProvider;
        public readonly string ClusterApiUrl;
        public readonly Outputs.GetClusterClusterConfigurationResult ClusterConfiguration;
        public readonly string ClusterType;
        public readonly string ConnectionType;
        public readonly string CreatedAt;
        public readonly Outputs.GetClusterCustomerManagedResourcesResult CustomerManagedResources;
        public readonly bool GcpGlobalAccessEnabled;
        public readonly Outputs.GetClusterGcpPrivateServiceConnectResult GcpPrivateServiceConnect;
        public readonly Outputs.GetClusterHttpProxyResult HttpProxy;
        public readonly string Id;
        public readonly Outputs.GetClusterKafkaApiResult KafkaApi;
        public readonly Outputs.GetClusterKafkaConnectResult KafkaConnect;
        public readonly Outputs.GetClusterMaintenanceWindowConfigResult MaintenanceWindowConfig;
        public readonly string Name;
        public readonly string NetworkId;
        public readonly Outputs.GetClusterPrometheusResult Prometheus;
        public readonly ImmutableArray<string> ReadReplicaClusterIds;
        public readonly Outputs.GetClusterRedpandaConsoleResult RedpandaConsole;
        public readonly string RedpandaVersion;
        public readonly string Region;
        public readonly string ResourceGroupId;
        public readonly Outputs.GetClusterSchemaRegistryResult SchemaRegistry;
        public readonly string State;
        public readonly Outputs.GetClusterStateDescriptionResult StateDescription;
        public readonly ImmutableDictionary<string, string> Tags;
        public readonly string ThroughputTier;
        public readonly Outputs.GetClusterTimeoutsResult? Timeouts;
        public readonly ImmutableArray<string> Zones;

        [OutputConstructor]
        private GetClusterResult(
            bool allowDeletion,

            Outputs.GetClusterAwsPrivateLinkResult awsPrivateLink,

            Outputs.GetClusterAzurePrivateLinkResult azurePrivateLink,

            string cloudProvider,

            string clusterApiUrl,

            Outputs.GetClusterClusterConfigurationResult clusterConfiguration,

            string clusterType,

            string connectionType,

            string createdAt,

            Outputs.GetClusterCustomerManagedResourcesResult customerManagedResources,

            bool gcpGlobalAccessEnabled,

            Outputs.GetClusterGcpPrivateServiceConnectResult gcpPrivateServiceConnect,

            Outputs.GetClusterHttpProxyResult httpProxy,

            string id,

            Outputs.GetClusterKafkaApiResult kafkaApi,

            Outputs.GetClusterKafkaConnectResult kafkaConnect,

            Outputs.GetClusterMaintenanceWindowConfigResult maintenanceWindowConfig,

            string name,

            string networkId,

            Outputs.GetClusterPrometheusResult prometheus,

            ImmutableArray<string> readReplicaClusterIds,

            Outputs.GetClusterRedpandaConsoleResult redpandaConsole,

            string redpandaVersion,

            string region,

            string resourceGroupId,

            Outputs.GetClusterSchemaRegistryResult schemaRegistry,

            string state,

            Outputs.GetClusterStateDescriptionResult stateDescription,

            ImmutableDictionary<string, string> tags,

            string throughputTier,

            Outputs.GetClusterTimeoutsResult? timeouts,

            ImmutableArray<string> zones)
        {
            AllowDeletion = allowDeletion;
            AwsPrivateLink = awsPrivateLink;
            AzurePrivateLink = azurePrivateLink;
            CloudProvider = cloudProvider;
            ClusterApiUrl = clusterApiUrl;
            ClusterConfiguration = clusterConfiguration;
            ClusterType = clusterType;
            ConnectionType = connectionType;
            CreatedAt = createdAt;
            CustomerManagedResources = customerManagedResources;
            GcpGlobalAccessEnabled = gcpGlobalAccessEnabled;
            GcpPrivateServiceConnect = gcpPrivateServiceConnect;
            HttpProxy = httpProxy;
            Id = id;
            KafkaApi = kafkaApi;
            KafkaConnect = kafkaConnect;
            MaintenanceWindowConfig = maintenanceWindowConfig;
            Name = name;
            NetworkId = networkId;
            Prometheus = prometheus;
            ReadReplicaClusterIds = readReplicaClusterIds;
            RedpandaConsole = redpandaConsole;
            RedpandaVersion = redpandaVersion;
            Region = region;
            ResourceGroupId = resourceGroupId;
            SchemaRegistry = schemaRegistry;
            State = state;
            StateDescription = stateDescription;
            Tags = tags;
            ThroughputTier = throughputTier;
            Timeouts = timeouts;
            Zones = zones;
        }
    }
}
