// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda
{
    public static class GetNetwork
    {
        public static Task<GetNetworkResult> InvokeAsync(GetNetworkArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetNetworkResult>("redpanda:index/getNetwork:getNetwork", args ?? new GetNetworkArgs(), options.WithDefaults());

        public static Output<GetNetworkResult> Invoke(GetNetworkInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetNetworkResult>("redpanda:index/getNetwork:getNetwork", args ?? new GetNetworkInvokeArgs(), options.WithDefaults());

        public static Output<GetNetworkResult> Invoke(GetNetworkInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetNetworkResult>("redpanda:index/getNetwork:getNetwork", args ?? new GetNetworkInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetNetworkArgs : global::Pulumi.InvokeArgs
    {
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        public GetNetworkArgs()
        {
        }
        public static new GetNetworkArgs Empty => new GetNetworkArgs();
    }

    public sealed class GetNetworkInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public GetNetworkInvokeArgs()
        {
        }
        public static new GetNetworkInvokeArgs Empty => new GetNetworkInvokeArgs();
    }


    [OutputType]
    public sealed class GetNetworkResult
    {
        public readonly string CidrBlock;
        public readonly string CloudProvider;
        public readonly string ClusterType;
        public readonly Outputs.GetNetworkCustomerManagedResourcesResult CustomerManagedResources;
        public readonly string Id;
        public readonly string Name;
        public readonly string Region;
        public readonly string ResourceGroupId;

        [OutputConstructor]
        private GetNetworkResult(
            string cidrBlock,

            string cloudProvider,

            string clusterType,

            Outputs.GetNetworkCustomerManagedResourcesResult customerManagedResources,

            string id,

            string name,

            string region,

            string resourceGroupId)
        {
            CidrBlock = cidrBlock;
            CloudProvider = cloudProvider;
            ClusterType = clusterType;
            CustomerManagedResources = customerManagedResources;
            Id = id;
            Name = name;
            Region = region;
            ResourceGroupId = resourceGroupId;
        }
    }
}
