// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda
{
    public static class GetResourceGroup
    {
        public static Task<GetResourceGroupResult> InvokeAsync(GetResourceGroupArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetResourceGroupResult>("redpanda:index/getResourceGroup:getResourceGroup", args ?? new GetResourceGroupArgs(), options.WithDefaults());

        public static Output<GetResourceGroupResult> Invoke(GetResourceGroupInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetResourceGroupResult>("redpanda:index/getResourceGroup:getResourceGroup", args ?? new GetResourceGroupInvokeArgs(), options.WithDefaults());

        public static Output<GetResourceGroupResult> Invoke(GetResourceGroupInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetResourceGroupResult>("redpanda:index/getResourceGroup:getResourceGroup", args ?? new GetResourceGroupInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetResourceGroupArgs : global::Pulumi.InvokeArgs
    {
        [Input("id")]
        public string? Id { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        public GetResourceGroupArgs()
        {
        }
        public static new GetResourceGroupArgs Empty => new GetResourceGroupArgs();
    }

    public sealed class GetResourceGroupInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetResourceGroupInvokeArgs()
        {
        }
        public static new GetResourceGroupInvokeArgs Empty => new GetResourceGroupInvokeArgs();
    }


    [OutputType]
    public sealed class GetResourceGroupResult
    {
        public readonly string Id;
        public readonly string Name;

        [OutputConstructor]
        private GetResourceGroupResult(
            string id,

            string name)
        {
            Id = id;
            Name = name;
        }
    }
}
