// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda
{
    public static class GetSchema
    {
        public static Task<GetSchemaResult> InvokeAsync(GetSchemaArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSchemaResult>("redpanda:index/getSchema:getSchema", args ?? new GetSchemaArgs(), options.WithDefaults());

        public static Output<GetSchemaResult> Invoke(GetSchemaInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSchemaResult>("redpanda:index/getSchema:getSchema", args ?? new GetSchemaInvokeArgs(), options.WithDefaults());

        public static Output<GetSchemaResult> Invoke(GetSchemaInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetSchemaResult>("redpanda:index/getSchema:getSchema", args ?? new GetSchemaInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSchemaArgs : global::Pulumi.InvokeArgs
    {
        [Input("clusterId", required: true)]
        public string ClusterId { get; set; } = null!;

        [Input("subject", required: true)]
        public string Subject { get; set; } = null!;

        [Input("version")]
        public int? Version { get; set; }

        public GetSchemaArgs()
        {
        }
        public static new GetSchemaArgs Empty => new GetSchemaArgs();
    }

    public sealed class GetSchemaInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("clusterId", required: true)]
        public Input<string> ClusterId { get; set; } = null!;

        [Input("subject", required: true)]
        public Input<string> Subject { get; set; } = null!;

        [Input("version")]
        public Input<int>? Version { get; set; }

        public GetSchemaInvokeArgs()
        {
        }
        public static new GetSchemaInvokeArgs Empty => new GetSchemaInvokeArgs();
    }


    [OutputType]
    public sealed class GetSchemaResult
    {
        public readonly string ClusterId;
        public readonly int Id;
        public readonly ImmutableArray<Outputs.GetSchemaReferenceResult> References;
        public readonly string Schema;
        public readonly string SchemaType;
        public readonly string Subject;
        public readonly int Version;

        [OutputConstructor]
        private GetSchemaResult(
            string clusterId,

            int id,

            ImmutableArray<Outputs.GetSchemaReferenceResult> references,

            string schema,

            string schemaType,

            string subject,

            int version)
        {
            ClusterId = clusterId;
            Id = id;
            References = references;
            Schema = schema;
            SchemaType = schemaType;
            Subject = subject;
            Version = version;
        }
    }
}
