// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda
{
    public static class GetThroughputTiers
    {
        public static Task<GetThroughputTiersResult> InvokeAsync(GetThroughputTiersArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetThroughputTiersResult>("redpanda:index/getThroughputTiers:getThroughputTiers", args ?? new GetThroughputTiersArgs(), options.WithDefaults());

        public static Output<GetThroughputTiersResult> Invoke(GetThroughputTiersInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetThroughputTiersResult>("redpanda:index/getThroughputTiers:getThroughputTiers", args ?? new GetThroughputTiersInvokeArgs(), options.WithDefaults());

        public static Output<GetThroughputTiersResult> Invoke(GetThroughputTiersInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetThroughputTiersResult>("redpanda:index/getThroughputTiers:getThroughputTiers", args ?? new GetThroughputTiersInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetThroughputTiersArgs : global::Pulumi.InvokeArgs
    {
        [Input("cloudProvider")]
        public string? CloudProvider { get; set; }

        public GetThroughputTiersArgs()
        {
        }
        public static new GetThroughputTiersArgs Empty => new GetThroughputTiersArgs();
    }

    public sealed class GetThroughputTiersInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("cloudProvider")]
        public Input<string>? CloudProvider { get; set; }

        public GetThroughputTiersInvokeArgs()
        {
        }
        public static new GetThroughputTiersInvokeArgs Empty => new GetThroughputTiersInvokeArgs();
    }


    [OutputType]
    public sealed class GetThroughputTiersResult
    {
        public readonly string? CloudProvider;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetThroughputTiersThroughputTierResult> ThroughputTiers;

        [OutputConstructor]
        private GetThroughputTiersResult(
            string? cloudProvider,

            string id,

            ImmutableArray<Outputs.GetThroughputTiersThroughputTierResult> throughputTiers)
        {
            CloudProvider = cloudProvider;
            Id = id;
            ThroughputTiers = throughputTiers;
        }
    }
}
