// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda
{
    [RedpandaResourceType("redpanda:index/pipeline:Pipeline")]
    public partial class Pipeline : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Allows deletion of the pipeline. Default is false. Must be set to true to delete the resource.
        /// </summary>
        [Output("allowDeletion")]
        public Output<bool> AllowDeletion { get; private set; } = null!;

        /// <summary>
        /// The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports.
        /// </summary>
        [Output("clusterApiUrl")]
        public Output<string> ClusterApiUrl { get; private set; } = null!;

        /// <summary>
        /// The Redpanda Connect pipeline configuration in YAML format. See https://docs.redpanda.com/redpanda-cloud/develop/connect/configuration/about for configuration details.
        /// </summary>
        [Output("configYaml")]
        public Output<string> ConfigYaml { get; private set; } = null!;

        /// <summary>
        /// Optional description of the pipeline.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// User-friendly display name for the pipeline.
        /// </summary>
        [Output("displayName")]
        public Output<string> DisplayName { get; private set; } = null!;

        /// <summary>
        /// Resource allocation for the pipeline.
        /// </summary>
        [Output("resources")]
        public Output<Outputs.PipelineResources> Resources { get; private set; } = null!;

        /// <summary>
        /// Service account credentials for the pipeline. Used to authenticate the pipeline with external services.
        /// </summary>
        [Output("serviceAccount")]
        public Output<Outputs.PipelineServiceAccount?> ServiceAccount { get; private set; } = null!;

        /// <summary>
        /// Desired state of the pipeline: 'running' or 'stopped'. The provider will ensure the pipeline reaches this state after create/update operations.
        /// </summary>
        [Output("state")]
        public Output<string> State { get; private set; } = null!;

        /// <summary>
        /// Key-value pairs to tag the pipeline for organization and filtering.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableDictionary<string, string>?> Tags { get; private set; } = null!;

        [Output("timeouts")]
        public Output<Outputs.PipelineTimeouts?> Timeouts { get; private set; } = null!;

        /// <summary>
        /// URL to connect to the pipeline's HTTP server, if applicable.
        /// </summary>
        [Output("url")]
        public Output<string> Url { get; private set; } = null!;


        /// <summary>
        /// Create a Pipeline resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Pipeline(string name, PipelineArgs args, CustomResourceOptions? options = null)
            : base("redpanda:index/pipeline:Pipeline", name, args ?? new PipelineArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Pipeline(string name, Input<string> id, PipelineState? state = null, CustomResourceOptions? options = null)
            : base("redpanda:index/pipeline:Pipeline", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/primait/pulumi-redpanda",
                AdditionalSecretOutputs =
                {
                    "configYaml",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Pipeline resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Pipeline Get(string name, Input<string> id, PipelineState? state = null, CustomResourceOptions? options = null)
        {
            return new Pipeline(name, id, state, options);
        }
    }

    public sealed class PipelineArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Allows deletion of the pipeline. Default is false. Must be set to true to delete the resource.
        /// </summary>
        [Input("allowDeletion")]
        public Input<bool>? AllowDeletion { get; set; }

        /// <summary>
        /// The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports.
        /// </summary>
        [Input("clusterApiUrl", required: true)]
        public Input<string> ClusterApiUrl { get; set; } = null!;

        [Input("configYaml", required: true)]
        private Input<string>? _configYaml;

        /// <summary>
        /// The Redpanda Connect pipeline configuration in YAML format. See https://docs.redpanda.com/redpanda-cloud/develop/connect/configuration/about for configuration details.
        /// </summary>
        public Input<string>? ConfigYaml
        {
            get => _configYaml;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _configYaml = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Optional description of the pipeline.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// User-friendly display name for the pipeline.
        /// </summary>
        [Input("displayName", required: true)]
        public Input<string> DisplayName { get; set; } = null!;

        /// <summary>
        /// Resource allocation for the pipeline.
        /// </summary>
        [Input("resources")]
        public Input<Inputs.PipelineResourcesArgs>? Resources { get; set; }

        /// <summary>
        /// Service account credentials for the pipeline. Used to authenticate the pipeline with external services.
        /// </summary>
        [Input("serviceAccount")]
        public Input<Inputs.PipelineServiceAccountArgs>? ServiceAccount { get; set; }

        /// <summary>
        /// Desired state of the pipeline: 'running' or 'stopped'. The provider will ensure the pipeline reaches this state after create/update operations.
        /// </summary>
        [Input("state")]
        public Input<string>? State { get; set; }

        [Input("tags")]
        private InputMap<string>? _tags;

        /// <summary>
        /// Key-value pairs to tag the pipeline for organization and filtering.
        /// </summary>
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        [Input("timeouts")]
        public Input<Inputs.PipelineTimeoutsArgs>? Timeouts { get; set; }

        public PipelineArgs()
        {
        }
        public static new PipelineArgs Empty => new PipelineArgs();
    }

    public sealed class PipelineState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Allows deletion of the pipeline. Default is false. Must be set to true to delete the resource.
        /// </summary>
        [Input("allowDeletion")]
        public Input<bool>? AllowDeletion { get; set; }

        /// <summary>
        /// The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports.
        /// </summary>
        [Input("clusterApiUrl")]
        public Input<string>? ClusterApiUrl { get; set; }

        [Input("configYaml")]
        private Input<string>? _configYaml;

        /// <summary>
        /// The Redpanda Connect pipeline configuration in YAML format. See https://docs.redpanda.com/redpanda-cloud/develop/connect/configuration/about for configuration details.
        /// </summary>
        public Input<string>? ConfigYaml
        {
            get => _configYaml;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _configYaml = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Optional description of the pipeline.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// User-friendly display name for the pipeline.
        /// </summary>
        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        /// <summary>
        /// Resource allocation for the pipeline.
        /// </summary>
        [Input("resources")]
        public Input<Inputs.PipelineResourcesGetArgs>? Resources { get; set; }

        /// <summary>
        /// Service account credentials for the pipeline. Used to authenticate the pipeline with external services.
        /// </summary>
        [Input("serviceAccount")]
        public Input<Inputs.PipelineServiceAccountGetArgs>? ServiceAccount { get; set; }

        /// <summary>
        /// Desired state of the pipeline: 'running' or 'stopped'. The provider will ensure the pipeline reaches this state after create/update operations.
        /// </summary>
        [Input("state")]
        public Input<string>? State { get; set; }

        [Input("tags")]
        private InputMap<string>? _tags;

        /// <summary>
        /// Key-value pairs to tag the pipeline for organization and filtering.
        /// </summary>
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        [Input("timeouts")]
        public Input<Inputs.PipelineTimeoutsGetArgs>? Timeouts { get; set; }

        /// <summary>
        /// URL to connect to the pipeline's HTTP server, if applicable.
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        public PipelineState()
        {
        }
        public static new PipelineState Empty => new PipelineState();
    }
}
