// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda
{
    [RedpandaResourceType("redpanda:index/schemaRegistryAcl:SchemaRegistryAcl")]
    public partial class SchemaRegistryAcl : global::Pulumi.CustomResource
    {
        /// <summary>
        /// When set to true, allows the resource to be removed from state even if deletion fails due to permission errors
        /// </summary>
        [Output("allowDeletion")]
        public Output<bool> AllowDeletion { get; private set; } = null!;

        /// <summary>
        /// The ID of the cluster where the Schema Registry ACL will be created
        /// </summary>
        [Output("clusterId")]
        public Output<string> ClusterId { get; private set; } = null!;

        /// <summary>
        /// The host address to use for this ACL. Use '*' for wildcard
        /// </summary>
        [Output("host")]
        public Output<string> Host { get; private set; } = null!;

        /// <summary>
        /// The operation type that shall be allowed or denied: ALL, READ, WRITE, DELETE, DESCRIBE, DESCRIBE_CONFIGS, ALTER, ALTER_CONFIGS
        /// </summary>
        [Output("operation")]
        public Output<string> Operation { get; private set; } = null!;

        /// <summary>
        /// Password for authentication. Deprecated: use PasswordWo instead. Can be set via REDPANDA_SR_PASSWORD environment variable
        /// </summary>
        [Output("password")]
        public Output<string?> Password { get; private set; } = null!;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Password for authentication (write-only, not stored in state). Requires Terraform 1.11+. Can be set via REDPANDA_SR_PASSWORD environment variable
        /// </summary>
        [Output("passwordWo")]
        public Output<string?> PasswordWo { get; private set; } = null!;

        /// <summary>
        /// Version number for password_wo. Increment this value to trigger a password update when using password_wo.
        /// </summary>
        [Output("passwordWoVersion")]
        public Output<int?> PasswordWoVersion { get; private set; } = null!;

        /// <summary>
        /// The pattern type of the resource: LITERAL or PREFIXED
        /// </summary>
        [Output("patternType")]
        public Output<string> PatternType { get; private set; } = null!;

        /// <summary>
        /// The permission type: ALLOW or DENY
        /// </summary>
        [Output("permission")]
        public Output<string> Permission { get; private set; } = null!;

        /// <summary>
        /// The principal to apply this ACL for (e.g., User:alice or RedpandaRole:admin)
        /// </summary>
        [Output("principal")]
        public Output<string> Principal { get; private set; } = null!;

        /// <summary>
        /// The name of the resource this ACL entry will be on. Use '*' for wildcard
        /// </summary>
        [Output("resourceName")]
        public Output<string> ResourceName { get; private set; } = null!;

        /// <summary>
        /// The type of the resource: SUBJECT or REGISTRY
        /// </summary>
        [Output("resourceType")]
        public Output<string> ResourceType { get; private set; } = null!;

        /// <summary>
        /// Username for authentication. Can be set via REDPANDA_SR_USERNAME environment variable
        /// </summary>
        [Output("username")]
        public Output<string?> Username { get; private set; } = null!;


        /// <summary>
        /// Create a SchemaRegistryAcl resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SchemaRegistryAcl(string name, SchemaRegistryAclArgs args, CustomResourceOptions? options = null)
            : base("redpanda:index/schemaRegistryAcl:SchemaRegistryAcl", name, args ?? new SchemaRegistryAclArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SchemaRegistryAcl(string name, Input<string> id, SchemaRegistryAclState? state = null, CustomResourceOptions? options = null)
            : base("redpanda:index/schemaRegistryAcl:SchemaRegistryAcl", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/primait/pulumi-redpanda",
                AdditionalSecretOutputs =
                {
                    "password",
                    "passwordWo",
                    "username",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SchemaRegistryAcl resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SchemaRegistryAcl Get(string name, Input<string> id, SchemaRegistryAclState? state = null, CustomResourceOptions? options = null)
        {
            return new SchemaRegistryAcl(name, id, state, options);
        }
    }

    public sealed class SchemaRegistryAclArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// When set to true, allows the resource to be removed from state even if deletion fails due to permission errors
        /// </summary>
        [Input("allowDeletion")]
        public Input<bool>? AllowDeletion { get; set; }

        /// <summary>
        /// The ID of the cluster where the Schema Registry ACL will be created
        /// </summary>
        [Input("clusterId", required: true)]
        public Input<string> ClusterId { get; set; } = null!;

        /// <summary>
        /// The host address to use for this ACL. Use '*' for wildcard
        /// </summary>
        [Input("host", required: true)]
        public Input<string> Host { get; set; } = null!;

        /// <summary>
        /// The operation type that shall be allowed or denied: ALL, READ, WRITE, DELETE, DESCRIBE, DESCRIBE_CONFIGS, ALTER, ALTER_CONFIGS
        /// </summary>
        [Input("operation", required: true)]
        public Input<string> Operation { get; set; } = null!;

        [Input("password")]
        private Input<string>? _password;

        /// <summary>
        /// Password for authentication. Deprecated: use PasswordWo instead. Can be set via REDPANDA_SR_PASSWORD environment variable
        /// </summary>
        [Obsolete(@"Use PasswordWo instead to avoid storing password in Terraform state")]
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("passwordWo")]
        private Input<string>? _passwordWo;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Password for authentication (write-only, not stored in state). Requires Terraform 1.11+. Can be set via REDPANDA_SR_PASSWORD environment variable
        /// </summary>
        public Input<string>? PasswordWo
        {
            get => _passwordWo;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _passwordWo = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Version number for password_wo. Increment this value to trigger a password update when using password_wo.
        /// </summary>
        [Input("passwordWoVersion")]
        public Input<int>? PasswordWoVersion { get; set; }

        /// <summary>
        /// The pattern type of the resource: LITERAL or PREFIXED
        /// </summary>
        [Input("patternType", required: true)]
        public Input<string> PatternType { get; set; } = null!;

        /// <summary>
        /// The permission type: ALLOW or DENY
        /// </summary>
        [Input("permission", required: true)]
        public Input<string> Permission { get; set; } = null!;

        /// <summary>
        /// The principal to apply this ACL for (e.g., User:alice or RedpandaRole:admin)
        /// </summary>
        [Input("principal", required: true)]
        public Input<string> Principal { get; set; } = null!;

        /// <summary>
        /// The name of the resource this ACL entry will be on. Use '*' for wildcard
        /// </summary>
        [Input("resourceName", required: true)]
        public Input<string> ResourceName { get; set; } = null!;

        /// <summary>
        /// The type of the resource: SUBJECT or REGISTRY
        /// </summary>
        [Input("resourceType", required: true)]
        public Input<string> ResourceType { get; set; } = null!;

        [Input("username")]
        private Input<string>? _username;

        /// <summary>
        /// Username for authentication. Can be set via REDPANDA_SR_USERNAME environment variable
        /// </summary>
        public Input<string>? Username
        {
            get => _username;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _username = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public SchemaRegistryAclArgs()
        {
        }
        public static new SchemaRegistryAclArgs Empty => new SchemaRegistryAclArgs();
    }

    public sealed class SchemaRegistryAclState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// When set to true, allows the resource to be removed from state even if deletion fails due to permission errors
        /// </summary>
        [Input("allowDeletion")]
        public Input<bool>? AllowDeletion { get; set; }

        /// <summary>
        /// The ID of the cluster where the Schema Registry ACL will be created
        /// </summary>
        [Input("clusterId")]
        public Input<string>? ClusterId { get; set; }

        /// <summary>
        /// The host address to use for this ACL. Use '*' for wildcard
        /// </summary>
        [Input("host")]
        public Input<string>? Host { get; set; }

        /// <summary>
        /// The operation type that shall be allowed or denied: ALL, READ, WRITE, DELETE, DESCRIBE, DESCRIBE_CONFIGS, ALTER, ALTER_CONFIGS
        /// </summary>
        [Input("operation")]
        public Input<string>? Operation { get; set; }

        [Input("password")]
        private Input<string>? _password;

        /// <summary>
        /// Password for authentication. Deprecated: use PasswordWo instead. Can be set via REDPANDA_SR_PASSWORD environment variable
        /// </summary>
        [Obsolete(@"Use PasswordWo instead to avoid storing password in Terraform state")]
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("passwordWo")]
        private Input<string>? _passwordWo;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Password for authentication (write-only, not stored in state). Requires Terraform 1.11+. Can be set via REDPANDA_SR_PASSWORD environment variable
        /// </summary>
        public Input<string>? PasswordWo
        {
            get => _passwordWo;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _passwordWo = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Version number for password_wo. Increment this value to trigger a password update when using password_wo.
        /// </summary>
        [Input("passwordWoVersion")]
        public Input<int>? PasswordWoVersion { get; set; }

        /// <summary>
        /// The pattern type of the resource: LITERAL or PREFIXED
        /// </summary>
        [Input("patternType")]
        public Input<string>? PatternType { get; set; }

        /// <summary>
        /// The permission type: ALLOW or DENY
        /// </summary>
        [Input("permission")]
        public Input<string>? Permission { get; set; }

        /// <summary>
        /// The principal to apply this ACL for (e.g., User:alice or RedpandaRole:admin)
        /// </summary>
        [Input("principal")]
        public Input<string>? Principal { get; set; }

        /// <summary>
        /// The name of the resource this ACL entry will be on. Use '*' for wildcard
        /// </summary>
        [Input("resourceName")]
        public Input<string>? ResourceName { get; set; }

        /// <summary>
        /// The type of the resource: SUBJECT or REGISTRY
        /// </summary>
        [Input("resourceType")]
        public Input<string>? ResourceType { get; set; }

        [Input("username")]
        private Input<string>? _username;

        /// <summary>
        /// Username for authentication. Can be set via REDPANDA_SR_USERNAME environment variable
        /// </summary>
        public Input<string>? Username
        {
            get => _username;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _username = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public SchemaRegistryAclState()
        {
        }
        public static new SchemaRegistryAclState Empty => new SchemaRegistryAclState();
    }
}
