// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda
{
    [RedpandaResourceType("redpanda:index/serverlessPrivateLink:ServerlessPrivateLink")]
    public partial class ServerlessPrivateLink : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Allows deletion of the serverless private link. Defaults to false.
        /// </summary>
        [Output("allowDeletion")]
        public Output<bool> AllowDeletion { get; private set; } = null!;

        /// <summary>
        /// Cloud provider (aws)
        /// </summary>
        [Output("cloudProvider")]
        public Output<string> CloudProvider { get; private set; } = null!;

        /// <summary>
        /// Cloud provider specific configuration
        /// </summary>
        [Output("cloudProviderConfig")]
        public Output<Outputs.ServerlessPrivateLinkCloudProviderConfig> CloudProviderConfig { get; private set; } = null!;

        /// <summary>
        /// Timestamp when the serverless private link was created
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Name of the serverless private link
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The ID of the Resource Group in which to create the serverless private link
        /// </summary>
        [Output("resourceGroupId")]
        public Output<string> ResourceGroupId { get; private set; } = null!;

        /// <summary>
        /// Redpanda serverless region
        /// </summary>
        [Output("serverlessRegion")]
        public Output<string> ServerlessRegion { get; private set; } = null!;

        /// <summary>
        /// Current state of the serverless private link (STATE_CREATING, STATE_READY, STATE_DELETING, STATE_FAILED, STATE_UPDATING)
        /// </summary>
        [Output("state")]
        public Output<string> State { get; private set; } = null!;

        /// <summary>
        /// Cloud provider specific status information
        /// </summary>
        [Output("status")]
        public Output<Outputs.ServerlessPrivateLinkStatus> Status { get; private set; } = null!;

        /// <summary>
        /// Timestamp when the serverless private link was last updated. This value changes on every update operation.
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;


        /// <summary>
        /// Create a ServerlessPrivateLink resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ServerlessPrivateLink(string name, ServerlessPrivateLinkArgs args, CustomResourceOptions? options = null)
            : base("redpanda:index/serverlessPrivateLink:ServerlessPrivateLink", name, args ?? new ServerlessPrivateLinkArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ServerlessPrivateLink(string name, Input<string> id, ServerlessPrivateLinkState? state = null, CustomResourceOptions? options = null)
            : base("redpanda:index/serverlessPrivateLink:ServerlessPrivateLink", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/primait/pulumi-redpanda",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ServerlessPrivateLink resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ServerlessPrivateLink Get(string name, Input<string> id, ServerlessPrivateLinkState? state = null, CustomResourceOptions? options = null)
        {
            return new ServerlessPrivateLink(name, id, state, options);
        }
    }

    public sealed class ServerlessPrivateLinkArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Allows deletion of the serverless private link. Defaults to false.
        /// </summary>
        [Input("allowDeletion")]
        public Input<bool>? AllowDeletion { get; set; }

        /// <summary>
        /// Cloud provider (aws)
        /// </summary>
        [Input("cloudProvider", required: true)]
        public Input<string> CloudProvider { get; set; } = null!;

        /// <summary>
        /// Cloud provider specific configuration
        /// </summary>
        [Input("cloudProviderConfig", required: true)]
        public Input<Inputs.ServerlessPrivateLinkCloudProviderConfigArgs> CloudProviderConfig { get; set; } = null!;

        /// <summary>
        /// Name of the serverless private link
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The ID of the Resource Group in which to create the serverless private link
        /// </summary>
        [Input("resourceGroupId", required: true)]
        public Input<string> ResourceGroupId { get; set; } = null!;

        /// <summary>
        /// Redpanda serverless region
        /// </summary>
        [Input("serverlessRegion", required: true)]
        public Input<string> ServerlessRegion { get; set; } = null!;

        public ServerlessPrivateLinkArgs()
        {
        }
        public static new ServerlessPrivateLinkArgs Empty => new ServerlessPrivateLinkArgs();
    }

    public sealed class ServerlessPrivateLinkState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Allows deletion of the serverless private link. Defaults to false.
        /// </summary>
        [Input("allowDeletion")]
        public Input<bool>? AllowDeletion { get; set; }

        /// <summary>
        /// Cloud provider (aws)
        /// </summary>
        [Input("cloudProvider")]
        public Input<string>? CloudProvider { get; set; }

        /// <summary>
        /// Cloud provider specific configuration
        /// </summary>
        [Input("cloudProviderConfig")]
        public Input<Inputs.ServerlessPrivateLinkCloudProviderConfigGetArgs>? CloudProviderConfig { get; set; }

        /// <summary>
        /// Timestamp when the serverless private link was created
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// Name of the serverless private link
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The ID of the Resource Group in which to create the serverless private link
        /// </summary>
        [Input("resourceGroupId")]
        public Input<string>? ResourceGroupId { get; set; }

        /// <summary>
        /// Redpanda serverless region
        /// </summary>
        [Input("serverlessRegion")]
        public Input<string>? ServerlessRegion { get; set; }

        /// <summary>
        /// Current state of the serverless private link (STATE_CREATING, STATE_READY, STATE_DELETING, STATE_FAILED, STATE_UPDATING)
        /// </summary>
        [Input("state")]
        public Input<string>? State { get; set; }

        /// <summary>
        /// Cloud provider specific status information
        /// </summary>
        [Input("status")]
        public Input<Inputs.ServerlessPrivateLinkStatusGetArgs>? Status { get; set; }

        /// <summary>
        /// Timestamp when the serverless private link was last updated. This value changes on every update operation.
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        public ServerlessPrivateLinkState()
        {
        }
        public static new ServerlessPrivateLinkState Empty => new ServerlessPrivateLinkState();
    }
}
