// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda
{
    [RedpandaResourceType("redpanda:index/user:User")]
    public partial class User : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Allows deletion of the user. If false, the user cannot be deleted and the resource will be removed from the state on destruction. Defaults to false.
        /// </summary>
        [Output("allowDeletion")]
        public Output<bool> AllowDeletion { get; private set; } = null!;

        /// <summary>
        /// The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports
        /// </summary>
        [Output("clusterApiUrl")]
        public Output<string> ClusterApiUrl { get; private set; } = null!;

        /// <summary>
        /// Which authentication method to use, see https://docs.redpanda.com/current/manage/security/authentication/ for more information
        /// </summary>
        [Output("mechanism")]
        public Output<string?> Mechanism { get; private set; } = null!;

        /// <summary>
        /// Name of the user, must be unique
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Password of the user. Deprecated: use PasswordWo instead to avoid storing password in state.
        /// </summary>
        [Output("password")]
        public Output<string?> Password { get; private set; } = null!;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Password of the user (write-only, not stored in state). Requires Terraform 1.11+. Either password or PasswordWo must be set.
        /// </summary>
        [Output("passwordWo")]
        public Output<string?> PasswordWo { get; private set; } = null!;

        /// <summary>
        /// Version number for password_wo. Increment this value to trigger a password update when using password_wo.
        /// </summary>
        [Output("passwordWoVersion")]
        public Output<int?> PasswordWoVersion { get; private set; } = null!;


        /// <summary>
        /// Create a User resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public User(string name, UserArgs args, CustomResourceOptions? options = null)
            : base("redpanda:index/user:User", name, args ?? new UserArgs(), MakeResourceOptions(options, ""))
        {
        }

        private User(string name, Input<string> id, UserState? state = null, CustomResourceOptions? options = null)
            : base("redpanda:index/user:User", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/primait/pulumi-redpanda",
                AdditionalSecretOutputs =
                {
                    "password",
                    "passwordWo",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing User resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static User Get(string name, Input<string> id, UserState? state = null, CustomResourceOptions? options = null)
        {
            return new User(name, id, state, options);
        }
    }

    public sealed class UserArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Allows deletion of the user. If false, the user cannot be deleted and the resource will be removed from the state on destruction. Defaults to false.
        /// </summary>
        [Input("allowDeletion")]
        public Input<bool>? AllowDeletion { get; set; }

        /// <summary>
        /// The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports
        /// </summary>
        [Input("clusterApiUrl", required: true)]
        public Input<string> ClusterApiUrl { get; set; } = null!;

        /// <summary>
        /// Which authentication method to use, see https://docs.redpanda.com/current/manage/security/authentication/ for more information
        /// </summary>
        [Input("mechanism")]
        public Input<string>? Mechanism { get; set; }

        /// <summary>
        /// Name of the user, must be unique
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("password")]
        private Input<string>? _password;

        /// <summary>
        /// Password of the user. Deprecated: use PasswordWo instead to avoid storing password in state.
        /// </summary>
        [Obsolete(@"Use PasswordWo instead to avoid storing password in Terraform state")]
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("passwordWo")]
        private Input<string>? _passwordWo;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Password of the user (write-only, not stored in state). Requires Terraform 1.11+. Either password or PasswordWo must be set.
        /// </summary>
        public Input<string>? PasswordWo
        {
            get => _passwordWo;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _passwordWo = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Version number for password_wo. Increment this value to trigger a password update when using password_wo.
        /// </summary>
        [Input("passwordWoVersion")]
        public Input<int>? PasswordWoVersion { get; set; }

        public UserArgs()
        {
        }
        public static new UserArgs Empty => new UserArgs();
    }

    public sealed class UserState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Allows deletion of the user. If false, the user cannot be deleted and the resource will be removed from the state on destruction. Defaults to false.
        /// </summary>
        [Input("allowDeletion")]
        public Input<bool>? AllowDeletion { get; set; }

        /// <summary>
        /// The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports
        /// </summary>
        [Input("clusterApiUrl")]
        public Input<string>? ClusterApiUrl { get; set; }

        /// <summary>
        /// Which authentication method to use, see https://docs.redpanda.com/current/manage/security/authentication/ for more information
        /// </summary>
        [Input("mechanism")]
        public Input<string>? Mechanism { get; set; }

        /// <summary>
        /// Name of the user, must be unique
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("password")]
        private Input<string>? _password;

        /// <summary>
        /// Password of the user. Deprecated: use PasswordWo instead to avoid storing password in state.
        /// </summary>
        [Obsolete(@"Use PasswordWo instead to avoid storing password in Terraform state")]
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("passwordWo")]
        private Input<string>? _passwordWo;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Password of the user (write-only, not stored in state). Requires Terraform 1.11+. Either password or PasswordWo must be set.
        /// </summary>
        public Input<string>? PasswordWo
        {
            get => _passwordWo;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _passwordWo = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Version number for password_wo. Increment this value to trigger a password update when using password_wo.
        /// </summary>
        [Input("passwordWoVersion")]
        public Input<int>? PasswordWoVersion { get; set; }

        public UserState()
        {
        }
        public static new UserState Empty => new UserState();
    }
}
