// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class ClusterClusterConfiguration
    {
        /// <summary>
        /// Custom properties for the cluster in JSON format.
        /// </summary>
        public readonly string? CustomPropertiesJson;

        [OutputConstructor]
        private ClusterClusterConfiguration(string? customPropertiesJson)
        {
            CustomPropertiesJson = customPropertiesJson;
        }
    }
}
