// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class ClusterCustomerManagedResources
    {
        public readonly Outputs.ClusterCustomerManagedResourcesAws? Aws;
        public readonly Outputs.ClusterCustomerManagedResourcesGcp? Gcp;

        [OutputConstructor]
        private ClusterCustomerManagedResources(
            Outputs.ClusterCustomerManagedResourcesAws? aws,

            Outputs.ClusterCustomerManagedResourcesGcp? gcp)
        {
            Aws = aws;
            Gcp = gcp;
        }
    }
}
