// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class ClusterCustomerManagedResourcesAws
    {
        public readonly Outputs.ClusterCustomerManagedResourcesAwsAgentInstanceProfile AgentInstanceProfile;
        public readonly Outputs.ClusterCustomerManagedResourcesAwsCloudStorageBucket CloudStorageBucket;
        public readonly Outputs.ClusterCustomerManagedResourcesAwsClusterSecurityGroup ClusterSecurityGroup;
        public readonly Outputs.ClusterCustomerManagedResourcesAwsConnectorsNodeGroupInstanceProfile ConnectorsNodeGroupInstanceProfile;
        public readonly Outputs.ClusterCustomerManagedResourcesAwsConnectorsSecurityGroup ConnectorsSecurityGroup;
        public readonly Outputs.ClusterCustomerManagedResourcesAwsK8sClusterRole K8sClusterRole;
        public readonly Outputs.ClusterCustomerManagedResourcesAwsNodeSecurityGroup NodeSecurityGroup;
        public readonly Outputs.ClusterCustomerManagedResourcesAwsPermissionsBoundaryPolicy PermissionsBoundaryPolicy;
        public readonly Outputs.ClusterCustomerManagedResourcesAwsRedpandaAgentSecurityGroup RedpandaAgentSecurityGroup;
        public readonly Outputs.ClusterCustomerManagedResourcesAwsRedpandaNodeGroupInstanceProfile RedpandaNodeGroupInstanceProfile;
        public readonly Outputs.ClusterCustomerManagedResourcesAwsRedpandaNodeGroupSecurityGroup RedpandaNodeGroupSecurityGroup;
        public readonly Outputs.ClusterCustomerManagedResourcesAwsUtilityNodeGroupInstanceProfile UtilityNodeGroupInstanceProfile;
        public readonly Outputs.ClusterCustomerManagedResourcesAwsUtilitySecurityGroup UtilitySecurityGroup;

        [OutputConstructor]
        private ClusterCustomerManagedResourcesAws(
            Outputs.ClusterCustomerManagedResourcesAwsAgentInstanceProfile agentInstanceProfile,

            Outputs.ClusterCustomerManagedResourcesAwsCloudStorageBucket cloudStorageBucket,

            Outputs.ClusterCustomerManagedResourcesAwsClusterSecurityGroup clusterSecurityGroup,

            Outputs.ClusterCustomerManagedResourcesAwsConnectorsNodeGroupInstanceProfile connectorsNodeGroupInstanceProfile,

            Outputs.ClusterCustomerManagedResourcesAwsConnectorsSecurityGroup connectorsSecurityGroup,

            Outputs.ClusterCustomerManagedResourcesAwsK8sClusterRole k8sClusterRole,

            Outputs.ClusterCustomerManagedResourcesAwsNodeSecurityGroup nodeSecurityGroup,

            Outputs.ClusterCustomerManagedResourcesAwsPermissionsBoundaryPolicy permissionsBoundaryPolicy,

            Outputs.ClusterCustomerManagedResourcesAwsRedpandaAgentSecurityGroup redpandaAgentSecurityGroup,

            Outputs.ClusterCustomerManagedResourcesAwsRedpandaNodeGroupInstanceProfile redpandaNodeGroupInstanceProfile,

            Outputs.ClusterCustomerManagedResourcesAwsRedpandaNodeGroupSecurityGroup redpandaNodeGroupSecurityGroup,

            Outputs.ClusterCustomerManagedResourcesAwsUtilityNodeGroupInstanceProfile utilityNodeGroupInstanceProfile,

            Outputs.ClusterCustomerManagedResourcesAwsUtilitySecurityGroup utilitySecurityGroup)
        {
            AgentInstanceProfile = agentInstanceProfile;
            CloudStorageBucket = cloudStorageBucket;
            ClusterSecurityGroup = clusterSecurityGroup;
            ConnectorsNodeGroupInstanceProfile = connectorsNodeGroupInstanceProfile;
            ConnectorsSecurityGroup = connectorsSecurityGroup;
            K8sClusterRole = k8sClusterRole;
            NodeSecurityGroup = nodeSecurityGroup;
            PermissionsBoundaryPolicy = permissionsBoundaryPolicy;
            RedpandaAgentSecurityGroup = redpandaAgentSecurityGroup;
            RedpandaNodeGroupInstanceProfile = redpandaNodeGroupInstanceProfile;
            RedpandaNodeGroupSecurityGroup = redpandaNodeGroupSecurityGroup;
            UtilityNodeGroupInstanceProfile = utilityNodeGroupInstanceProfile;
            UtilitySecurityGroup = utilitySecurityGroup;
        }
    }
}
