// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class ClusterMaintenanceWindowConfig
    {
        /// <summary>
        /// If true, maintenance can occur at any time.
        /// </summary>
        public readonly bool? Anytime;
        public readonly Outputs.ClusterMaintenanceWindowConfigDayHour? DayHour;
        /// <summary>
        /// If true, maintenance window is unspecified.
        /// </summary>
        public readonly bool? Unspecified;

        [OutputConstructor]
        private ClusterMaintenanceWindowConfig(
            bool? anytime,

            Outputs.ClusterMaintenanceWindowConfigDayHour? dayHour,

            bool? unspecified)
        {
            Anytime = anytime;
            DayHour = dayHour;
            Unspecified = unspecified;
        }
    }
}
