// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class ClusterGcpPrivateServiceConnect
    {
        /// <summary>
        /// List of consumers that are allowed to connect to Redpanda GCP PSC (Private Service Connect) service attachment.
        /// </summary>
        public readonly ImmutableArray<Outputs.ClusterGcpPrivateServiceConnectConsumerAcceptList> ConsumerAcceptLists;
        /// <summary>
        /// Whether Redpanda GCP Private Service Connect is enabled.
        /// </summary>
        public readonly bool Enabled;
        /// <summary>
        /// Whether global access is enabled.
        /// </summary>
        public readonly bool GlobalAccessEnabled;
        /// <summary>
        /// Current status of the Private Service Connect configuration.
        /// </summary>
        public readonly Outputs.ClusterGcpPrivateServiceConnectStatus? Status;

        [OutputConstructor]
        private ClusterGcpPrivateServiceConnect(
            ImmutableArray<Outputs.ClusterGcpPrivateServiceConnectConsumerAcceptList> consumerAcceptLists,

            bool enabled,

            bool globalAccessEnabled,

            Outputs.ClusterGcpPrivateServiceConnectStatus? status)
        {
            ConsumerAcceptLists = consumerAcceptLists;
            Enabled = enabled;
            GlobalAccessEnabled = globalAccessEnabled;
            Status = status;
        }
    }
}
