// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class ClusterCustomerManagedResourcesAwsNodeSecurityGroup
    {
        /// <summary>
        /// ARN for the node security group
        /// </summary>
        public readonly string Arn;

        [OutputConstructor]
        private ClusterCustomerManagedResourcesAwsNodeSecurityGroup(string arn)
        {
            Arn = arn;
        }
    }
}
