// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class ClusterCustomerManagedResourcesGcpSubnet
    {
        /// <summary>
        /// Kubernetes Master IPv4 range, e.g. 10.0.0.0/24.
        /// </summary>
        public readonly string K8sMasterIpv4Range;
        /// <summary>
        /// Subnet name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Secondary IPv4 range for pods.
        /// </summary>
        public readonly Outputs.ClusterCustomerManagedResourcesGcpSubnetSecondaryIpv4RangePods SecondaryIpv4RangePods;
        /// <summary>
        /// Secondary IPv4 range for services.
        /// </summary>
        public readonly Outputs.ClusterCustomerManagedResourcesGcpSubnetSecondaryIpv4RangeServices SecondaryIpv4RangeServices;

        [OutputConstructor]
        private ClusterCustomerManagedResourcesGcpSubnet(
            string k8sMasterIpv4Range,

            string name,

            Outputs.ClusterCustomerManagedResourcesGcpSubnetSecondaryIpv4RangePods secondaryIpv4RangePods,

            Outputs.ClusterCustomerManagedResourcesGcpSubnetSecondaryIpv4RangeServices secondaryIpv4RangeServices)
        {
            K8sMasterIpv4Range = k8sMasterIpv4Range;
            Name = name;
            SecondaryIpv4RangePods = secondaryIpv4RangePods;
            SecondaryIpv4RangeServices = secondaryIpv4RangeServices;
        }
    }
}
