// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class ClusterPrometheus
    {
        /// <summary>
        /// The Prometheus metrics endpoint URL.
        /// </summary>
        public readonly string? Url;

        [OutputConstructor]
        private ClusterPrometheus(string? url)
        {
            Url = url;
        }
    }
}
