// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class ClusterAwsPrivateLink
    {
        /// <summary>
        /// The ARN of the principals that can access the Redpanda AWS PrivateLink Endpoint Service. To grant permissions to all principals, use an asterisk (*).
        /// </summary>
        public readonly ImmutableArray<string> AllowedPrincipals;
        /// <summary>
        /// Whether Console is connected via PrivateLink.
        /// </summary>
        public readonly bool ConnectConsole;
        /// <summary>
        /// Whether AWS PrivateLink is enabled.
        /// </summary>
        public readonly bool Enabled;
        /// <summary>
        /// Current status of the PrivateLink configuration.
        /// </summary>
        public readonly Outputs.ClusterAwsPrivateLinkStatus? Status;

        [OutputConstructor]
        private ClusterAwsPrivateLink(
            ImmutableArray<string> allowedPrincipals,

            bool connectConsole,

            bool enabled,

            Outputs.ClusterAwsPrivateLinkStatus? status)
        {
            AllowedPrincipals = allowedPrincipals;
            ConnectConsole = connectConsole;
            Enabled = enabled;
            Status = status;
        }
    }
}
