// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class GetClusterMaintenanceWindowConfigDayHourResult
    {
        /// <summary>
        /// Day of week.
        /// </summary>
        public readonly string DayOfWeek;
        /// <summary>
        /// Hour of day.
        /// </summary>
        public readonly int HourOfDay;

        [OutputConstructor]
        private GetClusterMaintenanceWindowConfigDayHourResult(
            string dayOfWeek,

            int hourOfDay)
        {
            DayOfWeek = dayOfWeek;
            HourOfDay = hourOfDay;
        }
    }
}
