// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class GetClusterRedpandaConsoleResult
    {
        /// <summary>
        /// The Redpanda Console URL.
        /// </summary>
        public readonly string Url;

        [OutputConstructor]
        private GetClusterRedpandaConsoleResult(string url)
        {
            Url = url;
        }
    }
}
