// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class GetClusterAzurePrivateLinkResult
    {
        /// <summary>
        /// The subscriptions that can access the Redpanda Azure PrivateLink Endpoint Service.
        /// </summary>
        public readonly ImmutableArray<string> AllowedSubscriptions;
        /// <summary>
        /// Whether Console is connected in Redpanda Azure Private Link Service.
        /// </summary>
        public readonly bool ConnectConsole;
        /// <summary>
        /// Whether Redpanda Azure Private Link Endpoint Service is enabled.
        /// </summary>
        public readonly bool Enabled;
        /// <summary>
        /// Current status of the Private Link configuration.
        /// </summary>
        public readonly Outputs.GetClusterAzurePrivateLinkStatusResult Status;

        [OutputConstructor]
        private GetClusterAzurePrivateLinkResult(
            ImmutableArray<string> allowedSubscriptions,

            bool connectConsole,

            bool enabled,

            Outputs.GetClusterAzurePrivateLinkStatusResult status)
        {
            AllowedSubscriptions = allowedSubscriptions;
            ConnectConsole = connectConsole;
            Enabled = enabled;
            Status = status;
        }
    }
}
