// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class GetClusterCustomerManagedResourcesGcpResult
    {
        /// <summary>
        /// GCP service account for the agent.
        /// </summary>
        public readonly Outputs.GetClusterCustomerManagedResourcesGcpAgentServiceAccountResult AgentServiceAccount;
        /// <summary>
        /// GCP service account for managed connectors.
        /// </summary>
        public readonly Outputs.GetClusterCustomerManagedResourcesGcpConnectorServiceAccountResult ConnectorServiceAccount;
        /// <summary>
        /// GCP service account for Redpanda Console.
        /// </summary>
        public readonly Outputs.GetClusterCustomerManagedResourcesGcpConsoleServiceAccountResult ConsoleServiceAccount;
        /// <summary>
        /// GCP service account for GCP Kubernetes Engine (GKE).
        /// </summary>
        public readonly Outputs.GetClusterCustomerManagedResourcesGcpGkeServiceAccountResult GkeServiceAccount;
        /// <summary>
        /// NAT subnet name if GCP Private Service Connect is enabled.
        /// </summary>
        public readonly string PscNatSubnetName;
        /// <summary>
        /// GCP service account for the Redpanda cluster.
        /// </summary>
        public readonly Outputs.GetClusterCustomerManagedResourcesGcpRedpandaClusterServiceAccountResult RedpandaClusterServiceAccount;
        /// <summary>
        /// GCP subnet where Redpanda cluster is deployed.
        /// </summary>
        public readonly Outputs.GetClusterCustomerManagedResourcesGcpSubnetResult Subnet;
        /// <summary>
        /// GCP storage bucket for Tiered storage.
        /// </summary>
        public readonly Outputs.GetClusterCustomerManagedResourcesGcpTieredStorageBucketResult TieredStorageBucket;

        [OutputConstructor]
        private GetClusterCustomerManagedResourcesGcpResult(
            Outputs.GetClusterCustomerManagedResourcesGcpAgentServiceAccountResult agentServiceAccount,

            Outputs.GetClusterCustomerManagedResourcesGcpConnectorServiceAccountResult connectorServiceAccount,

            Outputs.GetClusterCustomerManagedResourcesGcpConsoleServiceAccountResult consoleServiceAccount,

            Outputs.GetClusterCustomerManagedResourcesGcpGkeServiceAccountResult gkeServiceAccount,

            string pscNatSubnetName,

            Outputs.GetClusterCustomerManagedResourcesGcpRedpandaClusterServiceAccountResult redpandaClusterServiceAccount,

            Outputs.GetClusterCustomerManagedResourcesGcpSubnetResult subnet,

            Outputs.GetClusterCustomerManagedResourcesGcpTieredStorageBucketResult tieredStorageBucket)
        {
            AgentServiceAccount = agentServiceAccount;
            ConnectorServiceAccount = connectorServiceAccount;
            ConsoleServiceAccount = consoleServiceAccount;
            GkeServiceAccount = gkeServiceAccount;
            PscNatSubnetName = pscNatSubnetName;
            RedpandaClusterServiceAccount = redpandaClusterServiceAccount;
            Subnet = subnet;
            TieredStorageBucket = tieredStorageBucket;
        }
    }
}
