// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class GetClusterAwsPrivateLinkStatusVpcEndpointConnectionDnsEntryResult
    {
        /// <summary>
        /// The DNS name.
        /// </summary>
        public readonly string DnsName;
        /// <summary>
        /// The hosted zone ID.
        /// </summary>
        public readonly string HostedZoneId;

        [OutputConstructor]
        private GetClusterAwsPrivateLinkStatusVpcEndpointConnectionDnsEntryResult(
            string dnsName,

            string hostedZoneId)
        {
            DnsName = dnsName;
            HostedZoneId = hostedZoneId;
        }
    }
}
