// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class GetClusterAzurePrivateLinkStatusResult
    {
        /// <summary>
        /// List of approved Azure subscription IDs.
        /// </summary>
        public readonly ImmutableArray<string> ApprovedSubscriptions;
        /// <summary>
        /// Port for Redpanda Console.
        /// </summary>
        public readonly int ConsolePort;
        /// <summary>
        /// When the Private Link service was created.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// When the Private Link service was deleted.
        /// </summary>
        public readonly string DeletedAt;
        /// <summary>
        /// DNS A record for the service.
        /// </summary>
        public readonly string DnsARecord;
        /// <summary>
        /// Base port for Kafka API nodes.
        /// </summary>
        public readonly int KafkaApiNodeBasePort;
        /// <summary>
        /// Port for Kafka API seed brokers.
        /// </summary>
        public readonly int KafkaApiSeedPort;
        /// <summary>
        /// List of private endpoint connections.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetClusterAzurePrivateLinkStatusPrivateEndpointConnectionResult> PrivateEndpointConnections;
        /// <summary>
        /// Base port for HTTP proxy nodes.
        /// </summary>
        public readonly int RedpandaProxyNodeBasePort;
        /// <summary>
        /// Port for HTTP proxy.
        /// </summary>
        public readonly int RedpandaProxySeedPort;
        /// <summary>
        /// Port for Schema Registry.
        /// </summary>
        public readonly int SchemaRegistrySeedPort;
        /// <summary>
        /// The Private Link service ID.
        /// </summary>
        public readonly string ServiceId;
        /// <summary>
        /// The Private Link service name.
        /// </summary>
        public readonly string ServiceName;

        [OutputConstructor]
        private GetClusterAzurePrivateLinkStatusResult(
            ImmutableArray<string> approvedSubscriptions,

            int consolePort,

            string createdAt,

            string deletedAt,

            string dnsARecord,

            int kafkaApiNodeBasePort,

            int kafkaApiSeedPort,

            ImmutableArray<Outputs.GetClusterAzurePrivateLinkStatusPrivateEndpointConnectionResult> privateEndpointConnections,

            int redpandaProxyNodeBasePort,

            int redpandaProxySeedPort,

            int schemaRegistrySeedPort,

            string serviceId,

            string serviceName)
        {
            ApprovedSubscriptions = approvedSubscriptions;
            ConsolePort = consolePort;
            CreatedAt = createdAt;
            DeletedAt = deletedAt;
            DnsARecord = dnsARecord;
            KafkaApiNodeBasePort = kafkaApiNodeBasePort;
            KafkaApiSeedPort = kafkaApiSeedPort;
            PrivateEndpointConnections = privateEndpointConnections;
            RedpandaProxyNodeBasePort = redpandaProxyNodeBasePort;
            RedpandaProxySeedPort = redpandaProxySeedPort;
            SchemaRegistrySeedPort = schemaRegistrySeedPort;
            ServiceId = serviceId;
            ServiceName = serviceName;
        }
    }
}
