// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class GetClusterAzurePrivateLinkStatusPrivateEndpointConnectionResult
    {
        /// <summary>
        /// ID of the connection.
        /// </summary>
        public readonly string ConnectionId;
        /// <summary>
        /// Name of the connection.
        /// </summary>
        public readonly string ConnectionName;
        /// <summary>
        /// When the endpoint connection was created.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// ID of the private endpoint.
        /// </summary>
        public readonly string PrivateEndpointId;
        /// <summary>
        /// Name of the private endpoint.
        /// </summary>
        public readonly string PrivateEndpointName;
        /// <summary>
        /// Status of the endpoint connection.
        /// </summary>
        public readonly string Status;

        [OutputConstructor]
        private GetClusterAzurePrivateLinkStatusPrivateEndpointConnectionResult(
            string connectionId,

            string connectionName,

            string createdAt,

            string privateEndpointId,

            string privateEndpointName,

            string status)
        {
            ConnectionId = connectionId;
            ConnectionName = connectionName;
            CreatedAt = createdAt;
            PrivateEndpointId = privateEndpointId;
            PrivateEndpointName = privateEndpointName;
            Status = status;
        }
    }
}
