// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class GetClusterCustomerManagedResourcesGcpSubnetSecondaryIpv4RangePodsResult
    {
        /// <summary>
        /// Secondary IPv4 range name for pods.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private GetClusterCustomerManagedResourcesGcpSubnetSecondaryIpv4RangePodsResult(string name)
        {
            Name = name;
        }
    }
}
