// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class GetClusterStateDescriptionResult
    {
        /// <summary>
        /// Error code if cluster is in error state.
        /// </summary>
        public readonly int Code;
        /// <summary>
        /// Detailed error message if cluster is in error state.
        /// </summary>
        public readonly string Message;

        [OutputConstructor]
        private GetClusterStateDescriptionResult(
            int code,

            string message)
        {
            Code = code;
            Message = message;
        }
    }
}
