// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class GetClusterCustomerManagedResourcesAwsResult
    {
        public readonly Outputs.GetClusterCustomerManagedResourcesAwsAgentInstanceProfileResult AgentInstanceProfile;
        public readonly Outputs.GetClusterCustomerManagedResourcesAwsCloudStorageBucketResult CloudStorageBucket;
        public readonly Outputs.GetClusterCustomerManagedResourcesAwsClusterSecurityGroupResult ClusterSecurityGroup;
        public readonly Outputs.GetClusterCustomerManagedResourcesAwsConnectorsNodeGroupInstanceProfileResult ConnectorsNodeGroupInstanceProfile;
        public readonly Outputs.GetClusterCustomerManagedResourcesAwsConnectorsSecurityGroupResult ConnectorsSecurityGroup;
        public readonly Outputs.GetClusterCustomerManagedResourcesAwsK8sClusterRoleResult K8sClusterRole;
        public readonly Outputs.GetClusterCustomerManagedResourcesAwsNodeSecurityGroupResult NodeSecurityGroup;
        public readonly Outputs.GetClusterCustomerManagedResourcesAwsPermissionsBoundaryPolicyResult PermissionsBoundaryPolicy;
        public readonly Outputs.GetClusterCustomerManagedResourcesAwsRedpandaAgentSecurityGroupResult RedpandaAgentSecurityGroup;
        public readonly Outputs.GetClusterCustomerManagedResourcesAwsRedpandaNodeGroupInstanceProfileResult RedpandaNodeGroupInstanceProfile;
        public readonly Outputs.GetClusterCustomerManagedResourcesAwsRedpandaNodeGroupSecurityGroupResult RedpandaNodeGroupSecurityGroup;
        public readonly Outputs.GetClusterCustomerManagedResourcesAwsUtilityNodeGroupInstanceProfileResult UtilityNodeGroupInstanceProfile;
        public readonly Outputs.GetClusterCustomerManagedResourcesAwsUtilitySecurityGroupResult UtilitySecurityGroup;

        [OutputConstructor]
        private GetClusterCustomerManagedResourcesAwsResult(
            Outputs.GetClusterCustomerManagedResourcesAwsAgentInstanceProfileResult agentInstanceProfile,

            Outputs.GetClusterCustomerManagedResourcesAwsCloudStorageBucketResult cloudStorageBucket,

            Outputs.GetClusterCustomerManagedResourcesAwsClusterSecurityGroupResult clusterSecurityGroup,

            Outputs.GetClusterCustomerManagedResourcesAwsConnectorsNodeGroupInstanceProfileResult connectorsNodeGroupInstanceProfile,

            Outputs.GetClusterCustomerManagedResourcesAwsConnectorsSecurityGroupResult connectorsSecurityGroup,

            Outputs.GetClusterCustomerManagedResourcesAwsK8sClusterRoleResult k8sClusterRole,

            Outputs.GetClusterCustomerManagedResourcesAwsNodeSecurityGroupResult nodeSecurityGroup,

            Outputs.GetClusterCustomerManagedResourcesAwsPermissionsBoundaryPolicyResult permissionsBoundaryPolicy,

            Outputs.GetClusterCustomerManagedResourcesAwsRedpandaAgentSecurityGroupResult redpandaAgentSecurityGroup,

            Outputs.GetClusterCustomerManagedResourcesAwsRedpandaNodeGroupInstanceProfileResult redpandaNodeGroupInstanceProfile,

            Outputs.GetClusterCustomerManagedResourcesAwsRedpandaNodeGroupSecurityGroupResult redpandaNodeGroupSecurityGroup,

            Outputs.GetClusterCustomerManagedResourcesAwsUtilityNodeGroupInstanceProfileResult utilityNodeGroupInstanceProfile,

            Outputs.GetClusterCustomerManagedResourcesAwsUtilitySecurityGroupResult utilitySecurityGroup)
        {
            AgentInstanceProfile = agentInstanceProfile;
            CloudStorageBucket = cloudStorageBucket;
            ClusterSecurityGroup = clusterSecurityGroup;
            ConnectorsNodeGroupInstanceProfile = connectorsNodeGroupInstanceProfile;
            ConnectorsSecurityGroup = connectorsSecurityGroup;
            K8sClusterRole = k8sClusterRole;
            NodeSecurityGroup = nodeSecurityGroup;
            PermissionsBoundaryPolicy = permissionsBoundaryPolicy;
            RedpandaAgentSecurityGroup = redpandaAgentSecurityGroup;
            RedpandaNodeGroupInstanceProfile = redpandaNodeGroupInstanceProfile;
            RedpandaNodeGroupSecurityGroup = redpandaNodeGroupSecurityGroup;
            UtilityNodeGroupInstanceProfile = utilityNodeGroupInstanceProfile;
            UtilitySecurityGroup = utilitySecurityGroup;
        }
    }
}
