// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class GetClusterGcpPrivateServiceConnectStatusConnectedEndpointResult
    {
        /// <summary>
        /// The connection ID.
        /// </summary>
        public readonly string ConnectionId;
        /// <summary>
        /// The consumer network.
        /// </summary>
        public readonly string ConsumerNetwork;
        /// <summary>
        /// The endpoint address.
        /// </summary>
        public readonly string Endpoint;
        /// <summary>
        /// Status of the endpoint connection.
        /// </summary>
        public readonly string Status;

        [OutputConstructor]
        private GetClusterGcpPrivateServiceConnectStatusConnectedEndpointResult(
            string connectionId,

            string consumerNetwork,

            string endpoint,

            string status)
        {
            ConnectionId = connectionId;
            ConsumerNetwork = consumerNetwork;
            Endpoint = endpoint;
            Status = status;
        }
    }
}
