// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class GetClusterAwsPrivateLinkStatusVpcEndpointConnectionResult
    {
        /// <summary>
        /// The connection ID.
        /// </summary>
        public readonly string ConnectionId;
        /// <summary>
        /// When the endpoint connection was created.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// DNS entries for the endpoint.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetClusterAwsPrivateLinkStatusVpcEndpointConnectionDnsEntryResult> DnsEntries;
        /// <summary>
        /// The endpoint connection ID.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// ARNs of associated load balancers.
        /// </summary>
        public readonly ImmutableArray<string> LoadBalancerArns;
        /// <summary>
        /// Owner of the endpoint connection.
        /// </summary>
        public readonly string Owner;
        /// <summary>
        /// State of the endpoint connection.
        /// </summary>
        public readonly string State;

        [OutputConstructor]
        private GetClusterAwsPrivateLinkStatusVpcEndpointConnectionResult(
            string connectionId,

            string createdAt,

            ImmutableArray<Outputs.GetClusterAwsPrivateLinkStatusVpcEndpointConnectionDnsEntryResult> dnsEntries,

            string id,

            ImmutableArray<string> loadBalancerArns,

            string owner,

            string state)
        {
            ConnectionId = connectionId;
            CreatedAt = createdAt;
            DnsEntries = dnsEntries;
            Id = id;
            LoadBalancerArns = loadBalancerArns;
            Owner = owner;
            State = state;
        }
    }
}
