// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class GetNetworkCustomerManagedResourcesResult
    {
        public readonly Outputs.GetNetworkCustomerManagedResourcesAwsResult Aws;
        public readonly Outputs.GetNetworkCustomerManagedResourcesGcpResult Gcp;

        [OutputConstructor]
        private GetNetworkCustomerManagedResourcesResult(
            Outputs.GetNetworkCustomerManagedResourcesAwsResult aws,

            Outputs.GetNetworkCustomerManagedResourcesGcpResult gcp)
        {
            Aws = aws;
            Gcp = gcp;
        }
    }
}
