// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class GetNetworkCustomerManagedResourcesAwsPrivateSubnetsResult
    {
        /// <summary>
        /// AWS private subnet identifiers
        /// </summary>
        public readonly ImmutableArray<string> Arns;

        [OutputConstructor]
        private GetNetworkCustomerManagedResourcesAwsPrivateSubnetsResult(ImmutableArray<string> arns)
        {
            Arns = arns;
        }
    }
}
