// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class GetRegionsRegionResult
    {
        /// <summary>
        /// Name of the region
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Zones available in the region
        /// </summary>
        public readonly ImmutableArray<string> Zones;

        [OutputConstructor]
        private GetRegionsRegionResult(
            string name,

            ImmutableArray<string> zones)
        {
            Name = name;
            Zones = zones;
        }
    }
}
