// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class GetServerlessRegionsServerlessRegionPlacementResult
    {
        /// <summary>
        /// Region available
        /// </summary>
        public readonly bool Enabled;

        [OutputConstructor]
        private GetServerlessRegionsServerlessRegionPlacementResult(bool enabled)
        {
            Enabled = enabled;
        }
    }
}
