// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class GetServerlessRegionsServerlessRegionResult
    {
        /// <summary>
        /// Cloud provider where the serverless regions exist
        /// </summary>
        public readonly string CloudProvider;
        /// <summary>
        /// Name of the serverless region
        /// </summary>
        public readonly string Name;
        public readonly Outputs.GetServerlessRegionsServerlessRegionPlacementResult Placement;
        /// <summary>
        /// Time zone of the serverless region
        /// </summary>
        public readonly string TimeZone;

        [OutputConstructor]
        private GetServerlessRegionsServerlessRegionResult(
            string cloudProvider,

            string name,

            Outputs.GetServerlessRegionsServerlessRegionPlacementResult placement,

            string timeZone)
        {
            CloudProvider = cloudProvider;
            Name = name;
            Placement = placement;
            TimeZone = timeZone;
        }
    }
}
