// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class GetThroughputTiersThroughputTierResult
    {
        /// <summary>
        /// Cloud provider where the Throughput Tier is available
        /// </summary>
        public readonly string CloudProvider;
        /// <summary>
        /// Display name of the Throughput Tier
        /// </summary>
        public readonly string DisplayName;
        /// <summary>
        /// Unique name of the Throughput Tier
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private GetThroughputTiersThroughputTierResult(
            string cloudProvider,

            string displayName,

            string name)
        {
            CloudProvider = cloudProvider;
            DisplayName = displayName;
            Name = name;
        }
    }
}
