// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class NetworkCustomerManagedResourcesAws
    {
        public readonly Outputs.NetworkCustomerManagedResourcesAwsDynamodbTable DynamodbTable;
        public readonly Outputs.NetworkCustomerManagedResourcesAwsManagementBucket ManagementBucket;
        public readonly Outputs.NetworkCustomerManagedResourcesAwsPrivateSubnets PrivateSubnets;
        public readonly Outputs.NetworkCustomerManagedResourcesAwsVpc Vpc;

        [OutputConstructor]
        private NetworkCustomerManagedResourcesAws(
            Outputs.NetworkCustomerManagedResourcesAwsDynamodbTable dynamodbTable,

            Outputs.NetworkCustomerManagedResourcesAwsManagementBucket managementBucket,

            Outputs.NetworkCustomerManagedResourcesAwsPrivateSubnets privateSubnets,

            Outputs.NetworkCustomerManagedResourcesAwsVpc vpc)
        {
            DynamodbTable = dynamodbTable;
            ManagementBucket = managementBucket;
            PrivateSubnets = privateSubnets;
            Vpc = vpc;
        }
    }
}
