// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class NetworkCustomerManagedResourcesGcp
    {
        public readonly Outputs.NetworkCustomerManagedResourcesGcpManagementBucket ManagementBucket;
        /// <summary>
        /// Name of user-created network where the Redpanda cluster is deployed
        /// </summary>
        public readonly string NetworkName;
        /// <summary>
        /// GCP project ID where the network is created
        /// </summary>
        public readonly string NetworkProjectId;

        [OutputConstructor]
        private NetworkCustomerManagedResourcesGcp(
            Outputs.NetworkCustomerManagedResourcesGcpManagementBucket managementBucket,

            string networkName,

            string networkProjectId)
        {
            ManagementBucket = managementBucket;
            NetworkName = networkName;
            NetworkProjectId = networkProjectId;
        }
    }
}
