// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class NetworkCustomerManagedResources
    {
        public readonly Outputs.NetworkCustomerManagedResourcesAws? Aws;
        public readonly Outputs.NetworkCustomerManagedResourcesGcp? Gcp;

        [OutputConstructor]
        private NetworkCustomerManagedResources(
            Outputs.NetworkCustomerManagedResourcesAws? aws,

            Outputs.NetworkCustomerManagedResourcesGcp? gcp)
        {
            Aws = aws;
            Gcp = gcp;
        }
    }
}
