// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class PipelineServiceAccount
    {
        /// <summary>
        /// The client ID for the service account.
        /// </summary>
        public readonly string ClientId;
        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// The client secret for the service account (write-only, not stored in state). Requires Terraform 1.11+.
        /// </summary>
        public readonly string ClientSecret;
        /// <summary>
        /// Version number for client_secret. Increment to trigger a secret update.
        /// </summary>
        public readonly int? SecretVersion;

        [OutputConstructor]
        private PipelineServiceAccount(
            string clientId,

            string clientSecret,

            int? secretVersion)
        {
            ClientId = clientId;
            ClientSecret = clientSecret;
            SecretVersion = secretVersion;
        }
    }
}
