// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class PipelineResources
    {
        /// <summary>
        /// Amount of CPU to allocate for the pipeline.
        /// </summary>
        public readonly string? CpuShares;
        /// <summary>
        /// Amount of memory to allocate for the pipeline.
        /// </summary>
        public readonly string? MemoryShares;

        [OutputConstructor]
        private PipelineResources(
            string? cpuShares,

            string? memoryShares)
        {
            CpuShares = cpuShares;
            MemoryShares = memoryShares;
        }
    }
}
