// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class SchemaReference
    {
        /// <summary>
        /// The name of the referenced schema.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The subject of the referenced schema.
        /// </summary>
        public readonly string Subject;
        /// <summary>
        /// The version of the referenced schema.
        /// </summary>
        public readonly int Version;

        [OutputConstructor]
        private SchemaReference(
            string name,

            string subject,

            int version)
        {
            Name = name;
            Subject = subject;
            Version = version;
        }
    }
}
