// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class ServerlessClusterNetworkingConfig
    {
        /// <summary>
        /// Private network state. Valid values: STATE_UNSPECIFIED, STATE_DISABLED, STATE_ENABLED
        /// </summary>
        public readonly string? Private;
        /// <summary>
        /// Public network state. Valid values: STATE_UNSPECIFIED, STATE_DISABLED, STATE_ENABLED
        /// </summary>
        public readonly string? Public;

        [OutputConstructor]
        private ServerlessClusterNetworkingConfig(
            string? @private,

            string? @public)
        {
            Private = @private;
            Public = @public;
        }
    }
}
