// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class ServerlessClusterSchemaRegistry
    {
        /// <summary>
        /// Private Schema Registry URL
        /// </summary>
        public readonly string? PrivateUrl;
        /// <summary>
        /// Public Schema Registry URL
        /// </summary>
        public readonly string? Url;

        [OutputConstructor]
        private ServerlessClusterSchemaRegistry(
            string? privateUrl,

            string? url)
        {
            PrivateUrl = privateUrl;
            Url = url;
        }
    }
}
