// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class ServerlessClusterKafkaApi
    {
        /// <summary>
        /// Private Kafka API seed brokers (bootstrap servers)
        /// </summary>
        public readonly ImmutableArray<string> PrivateSeedBrokers;
        /// <summary>
        /// Public Kafka API seed brokers (bootstrap servers)
        /// </summary>
        public readonly ImmutableArray<string> SeedBrokers;

        [OutputConstructor]
        private ServerlessClusterKafkaApi(
            ImmutableArray<string> privateSeedBrokers,

            ImmutableArray<string> seedBrokers)
        {
            PrivateSeedBrokers = privateSeedBrokers;
            SeedBrokers = seedBrokers;
        }
    }
}
