// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Outputs
{

    [OutputType]
    public sealed class ServerlessPrivateLinkStatus
    {
        /// <summary>
        /// AWS-specific status information
        /// </summary>
        public readonly Outputs.ServerlessPrivateLinkStatusAws? Aws;

        [OutputConstructor]
        private ServerlessPrivateLinkStatus(Outputs.ServerlessPrivateLinkStatusAws? aws)
        {
            Aws = aws;
        }
    }
}
