// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class ClusterCustomerManagedResourcesAwsConnectorsSecurityGroupArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ARN for the connectors security group
        /// </summary>
        [Input("arn", required: true)]
        public Input<string> Arn { get; set; } = null!;

        public ClusterCustomerManagedResourcesAwsConnectorsSecurityGroupArgs()
        {
        }
        public static new ClusterCustomerManagedResourcesAwsConnectorsSecurityGroupArgs Empty => new ClusterCustomerManagedResourcesAwsConnectorsSecurityGroupArgs();
    }
}
