// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class ClusterCustomerManagedResourcesGcpSubnetSecondaryIpv4RangeServicesGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Secondary IPv4 range name for services.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public ClusterCustomerManagedResourcesGcpSubnetSecondaryIpv4RangeServicesGetArgs()
        {
        }
        public static new ClusterCustomerManagedResourcesGcpSubnetSecondaryIpv4RangeServicesGetArgs Empty => new ClusterCustomerManagedResourcesGcpSubnetSecondaryIpv4RangeServicesGetArgs();
    }
}
