// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class ClusterCustomerManagedResourcesAwsNodeSecurityGroupArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ARN for the node security group
        /// </summary>
        [Input("arn", required: true)]
        public Input<string> Arn { get; set; } = null!;

        public ClusterCustomerManagedResourcesAwsNodeSecurityGroupArgs()
        {
        }
        public static new ClusterCustomerManagedResourcesAwsNodeSecurityGroupArgs Empty => new ClusterCustomerManagedResourcesAwsNodeSecurityGroupArgs();
    }
}
