// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class ClusterAwsPrivateLinkStatusVpcEndpointConnectionGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The connection ID.
        /// </summary>
        [Input("connectionId")]
        public Input<string>? ConnectionId { get; set; }

        /// <summary>
        /// When the endpoint connection was created.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        [Input("dnsEntries")]
        private InputList<Inputs.ClusterAwsPrivateLinkStatusVpcEndpointConnectionDnsEntryGetArgs>? _dnsEntries;

        /// <summary>
        /// DNS entries for the endpoint.
        /// </summary>
        public InputList<Inputs.ClusterAwsPrivateLinkStatusVpcEndpointConnectionDnsEntryGetArgs> DnsEntries
        {
            get => _dnsEntries ?? (_dnsEntries = new InputList<Inputs.ClusterAwsPrivateLinkStatusVpcEndpointConnectionDnsEntryGetArgs>());
            set => _dnsEntries = value;
        }

        /// <summary>
        /// The endpoint connection ID.
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("loadBalancerArns")]
        private InputList<string>? _loadBalancerArns;

        /// <summary>
        /// ARNs of associated load balancers.
        /// </summary>
        public InputList<string> LoadBalancerArns
        {
            get => _loadBalancerArns ?? (_loadBalancerArns = new InputList<string>());
            set => _loadBalancerArns = value;
        }

        /// <summary>
        /// Owner of the endpoint connection.
        /// </summary>
        [Input("owner")]
        public Input<string>? Owner { get; set; }

        /// <summary>
        /// State of the endpoint connection.
        /// </summary>
        [Input("state")]
        public Input<string>? State { get; set; }

        public ClusterAwsPrivateLinkStatusVpcEndpointConnectionGetArgs()
        {
        }
        public static new ClusterAwsPrivateLinkStatusVpcEndpointConnectionGetArgs Empty => new ClusterAwsPrivateLinkStatusVpcEndpointConnectionGetArgs();
    }
}
