// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class ClusterMaintenanceWindowConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// If true, maintenance can occur at any time.
        /// </summary>
        [Input("anytime")]
        public Input<bool>? Anytime { get; set; }

        [Input("dayHour")]
        public Input<Inputs.ClusterMaintenanceWindowConfigDayHourArgs>? DayHour { get; set; }

        /// <summary>
        /// If true, maintenance window is unspecified.
        /// </summary>
        [Input("unspecified")]
        public Input<bool>? Unspecified { get; set; }

        public ClusterMaintenanceWindowConfigArgs()
        {
        }
        public static new ClusterMaintenanceWindowConfigArgs Empty => new ClusterMaintenanceWindowConfigArgs();
    }
}
