// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class ClusterAwsPrivateLinkStatusVpcEndpointConnectionDnsEntryArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The DNS name.
        /// </summary>
        [Input("dnsName")]
        public Input<string>? DnsName { get; set; }

        /// <summary>
        /// The hosted zone ID.
        /// </summary>
        [Input("hostedZoneId")]
        public Input<string>? HostedZoneId { get; set; }

        public ClusterAwsPrivateLinkStatusVpcEndpointConnectionDnsEntryArgs()
        {
        }
        public static new ClusterAwsPrivateLinkStatusVpcEndpointConnectionDnsEntryArgs Empty => new ClusterAwsPrivateLinkStatusVpcEndpointConnectionDnsEntryArgs();
    }
}
