// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class ClusterKafkaApiGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// mTLS configuration.
        /// </summary>
        [Input("mtls")]
        public Input<Inputs.ClusterKafkaApiMtlsGetArgs>? Mtls { get; set; }

        [Input("seedBrokers")]
        private InputList<string>? _seedBrokers;

        /// <summary>
        /// List of Kafka broker addresses.
        /// </summary>
        public InputList<string> SeedBrokers
        {
            get => _seedBrokers ?? (_seedBrokers = new InputList<string>());
            set => _seedBrokers = value;
        }

        public ClusterKafkaApiGetArgs()
        {
        }
        public static new ClusterKafkaApiGetArgs Empty => new ClusterKafkaApiGetArgs();
    }
}
