// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class ClusterCustomerManagedResourcesGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("aws")]
        public Input<Inputs.ClusterCustomerManagedResourcesAwsGetArgs>? Aws { get; set; }

        [Input("gcp")]
        public Input<Inputs.ClusterCustomerManagedResourcesGcpGetArgs>? Gcp { get; set; }

        public ClusterCustomerManagedResourcesGetArgs()
        {
        }
        public static new ClusterCustomerManagedResourcesGetArgs Empty => new ClusterCustomerManagedResourcesGetArgs();
    }
}
