// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class ClusterGcpPrivateServiceConnectConsumerAcceptListArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Either the GCP project number or its alphanumeric ID.
        /// </summary>
        [Input("source", required: true)]
        public Input<string> Source { get; set; } = null!;

        public ClusterGcpPrivateServiceConnectConsumerAcceptListArgs()
        {
        }
        public static new ClusterGcpPrivateServiceConnectConsumerAcceptListArgs Empty => new ClusterGcpPrivateServiceConnectConsumerAcceptListArgs();
    }
}
