// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class ClusterCustomerManagedResourcesGcpGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// GCP service account for the agent.
        /// </summary>
        [Input("agentServiceAccount", required: true)]
        public Input<Inputs.ClusterCustomerManagedResourcesGcpAgentServiceAccountGetArgs> AgentServiceAccount { get; set; } = null!;

        /// <summary>
        /// GCP service account for managed connectors.
        /// </summary>
        [Input("connectorServiceAccount", required: true)]
        public Input<Inputs.ClusterCustomerManagedResourcesGcpConnectorServiceAccountGetArgs> ConnectorServiceAccount { get; set; } = null!;

        /// <summary>
        /// GCP service account for Redpanda Console.
        /// </summary>
        [Input("consoleServiceAccount", required: true)]
        public Input<Inputs.ClusterCustomerManagedResourcesGcpConsoleServiceAccountGetArgs> ConsoleServiceAccount { get; set; } = null!;

        /// <summary>
        /// GCP service account for GCP Kubernetes Engine (GKE).
        /// </summary>
        [Input("gkeServiceAccount", required: true)]
        public Input<Inputs.ClusterCustomerManagedResourcesGcpGkeServiceAccountGetArgs> GkeServiceAccount { get; set; } = null!;

        /// <summary>
        /// NAT subnet name if GCP Private Service Connect is enabled.
        /// </summary>
        [Input("pscNatSubnetName")]
        public Input<string>? PscNatSubnetName { get; set; }

        /// <summary>
        /// GCP service account for the Redpanda cluster.
        /// </summary>
        [Input("redpandaClusterServiceAccount", required: true)]
        public Input<Inputs.ClusterCustomerManagedResourcesGcpRedpandaClusterServiceAccountGetArgs> RedpandaClusterServiceAccount { get; set; } = null!;

        /// <summary>
        /// GCP subnet where Redpanda cluster is deployed.
        /// </summary>
        [Input("subnet", required: true)]
        public Input<Inputs.ClusterCustomerManagedResourcesGcpSubnetGetArgs> Subnet { get; set; } = null!;

        /// <summary>
        /// GCP storage bucket for Tiered storage.
        /// </summary>
        [Input("tieredStorageBucket", required: true)]
        public Input<Inputs.ClusterCustomerManagedResourcesGcpTieredStorageBucketGetArgs> TieredStorageBucket { get; set; } = null!;

        public ClusterCustomerManagedResourcesGcpGetArgs()
        {
        }
        public static new ClusterCustomerManagedResourcesGcpGetArgs Empty => new ClusterCustomerManagedResourcesGcpGetArgs();
    }
}
