// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class ClusterAwsPrivateLinkStatusArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Port for Redpanda Console.
        /// </summary>
        [Input("consolePort")]
        public Input<int>? ConsolePort { get; set; }

        /// <summary>
        /// When the PrivateLink service was created.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// When the PrivateLink service was deleted.
        /// </summary>
        [Input("deletedAt")]
        public Input<string>? DeletedAt { get; set; }

        /// <summary>
        /// Base port for Kafka API nodes.
        /// </summary>
        [Input("kafkaApiNodeBasePort")]
        public Input<int>? KafkaApiNodeBasePort { get; set; }

        /// <summary>
        /// Port for Kafka API seed brokers.
        /// </summary>
        [Input("kafkaApiSeedPort")]
        public Input<int>? KafkaApiSeedPort { get; set; }

        /// <summary>
        /// Base port for HTTP proxy nodes.
        /// </summary>
        [Input("redpandaProxyNodeBasePort")]
        public Input<int>? RedpandaProxyNodeBasePort { get; set; }

        /// <summary>
        /// Port for HTTP proxy.
        /// </summary>
        [Input("redpandaProxySeedPort")]
        public Input<int>? RedpandaProxySeedPort { get; set; }

        /// <summary>
        /// Port for Schema Registry.
        /// </summary>
        [Input("schemaRegistrySeedPort")]
        public Input<int>? SchemaRegistrySeedPort { get; set; }

        /// <summary>
        /// The PrivateLink service ID.
        /// </summary>
        [Input("serviceId")]
        public Input<string>? ServiceId { get; set; }

        /// <summary>
        /// The PrivateLink service name.
        /// </summary>
        [Input("serviceName")]
        public Input<string>? ServiceName { get; set; }

        /// <summary>
        /// Current state of the PrivateLink service.
        /// </summary>
        [Input("serviceState")]
        public Input<string>? ServiceState { get; set; }

        [Input("vpcEndpointConnections")]
        private InputList<Inputs.ClusterAwsPrivateLinkStatusVpcEndpointConnectionArgs>? _vpcEndpointConnections;

        /// <summary>
        /// List of VPC endpoint connections.
        /// </summary>
        public InputList<Inputs.ClusterAwsPrivateLinkStatusVpcEndpointConnectionArgs> VpcEndpointConnections
        {
            get => _vpcEndpointConnections ?? (_vpcEndpointConnections = new InputList<Inputs.ClusterAwsPrivateLinkStatusVpcEndpointConnectionArgs>());
            set => _vpcEndpointConnections = value;
        }

        public ClusterAwsPrivateLinkStatusArgs()
        {
        }
        public static new ClusterAwsPrivateLinkStatusArgs Empty => new ClusterAwsPrivateLinkStatusArgs();
    }
}
