// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class ClusterKafkaConnectArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether Kafka Connect is enabled.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        public ClusterKafkaConnectArgs()
        {
        }
        public static new ClusterKafkaConnectArgs Empty => new ClusterKafkaConnectArgs();
    }
}
