// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class ClusterMaintenanceWindowConfigDayHourArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Day of week.
        /// </summary>
        [Input("dayOfWeek")]
        public Input<string>? DayOfWeek { get; set; }

        /// <summary>
        /// Hour of day.
        /// </summary>
        [Input("hourOfDay")]
        public Input<int>? HourOfDay { get; set; }

        public ClusterMaintenanceWindowConfigDayHourArgs()
        {
        }
        public static new ClusterMaintenanceWindowConfigDayHourArgs Empty => new ClusterMaintenanceWindowConfigDayHourArgs();
    }
}
