// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class ClusterGcpPrivateServiceConnectStatusArgs : global::Pulumi.ResourceArgs
    {
        [Input("connectedEndpoints")]
        private InputList<Inputs.ClusterGcpPrivateServiceConnectStatusConnectedEndpointArgs>? _connectedEndpoints;

        /// <summary>
        /// List of connected endpoints.
        /// </summary>
        public InputList<Inputs.ClusterGcpPrivateServiceConnectStatusConnectedEndpointArgs> ConnectedEndpoints
        {
            get => _connectedEndpoints ?? (_connectedEndpoints = new InputList<Inputs.ClusterGcpPrivateServiceConnectStatusConnectedEndpointArgs>());
            set => _connectedEndpoints = value;
        }

        /// <summary>
        /// When the Private Service Connect service was created.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// When the Private Service Connect service was deleted.
        /// </summary>
        [Input("deletedAt")]
        public Input<string>? DeletedAt { get; set; }

        [Input("dnsARecords")]
        private InputList<string>? _dnsARecords;

        /// <summary>
        /// DNS A records for the service.
        /// </summary>
        public InputList<string> DnsARecords
        {
            get => _dnsARecords ?? (_dnsARecords = new InputList<string>());
            set => _dnsARecords = value;
        }

        /// <summary>
        /// Base port for Kafka API nodes.
        /// </summary>
        [Input("kafkaApiNodeBasePort")]
        public Input<int>? KafkaApiNodeBasePort { get; set; }

        /// <summary>
        /// Port for Kafka API seed brokers.
        /// </summary>
        [Input("kafkaApiSeedPort")]
        public Input<int>? KafkaApiSeedPort { get; set; }

        /// <summary>
        /// Base port for HTTP proxy nodes.
        /// </summary>
        [Input("redpandaProxyNodeBasePort")]
        public Input<int>? RedpandaProxyNodeBasePort { get; set; }

        /// <summary>
        /// Port for HTTP proxy.
        /// </summary>
        [Input("redpandaProxySeedPort")]
        public Input<int>? RedpandaProxySeedPort { get; set; }

        /// <summary>
        /// Port for Schema Registry.
        /// </summary>
        [Input("schemaRegistrySeedPort")]
        public Input<int>? SchemaRegistrySeedPort { get; set; }

        /// <summary>
        /// Hostname for the seed brokers.
        /// </summary>
        [Input("seedHostname")]
        public Input<string>? SeedHostname { get; set; }

        /// <summary>
        /// The service attachment identifier.
        /// </summary>
        [Input("serviceAttachment")]
        public Input<string>? ServiceAttachment { get; set; }

        public ClusterGcpPrivateServiceConnectStatusArgs()
        {
        }
        public static new ClusterGcpPrivateServiceConnectStatusArgs Empty => new ClusterGcpPrivateServiceConnectStatusArgs();
    }
}
