// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class ClusterRedpandaConsoleGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Redpanda Console URL.
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        public ClusterRedpandaConsoleGetArgs()
        {
        }
        public static new ClusterRedpandaConsoleGetArgs Empty => new ClusterRedpandaConsoleGetArgs();
    }
}
