// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class ClusterCustomerManagedResourcesArgs : global::Pulumi.ResourceArgs
    {
        [Input("aws")]
        public Input<Inputs.ClusterCustomerManagedResourcesAwsArgs>? Aws { get; set; }

        [Input("gcp")]
        public Input<Inputs.ClusterCustomerManagedResourcesGcpArgs>? Gcp { get; set; }

        public ClusterCustomerManagedResourcesArgs()
        {
        }
        public static new ClusterCustomerManagedResourcesArgs Empty => new ClusterCustomerManagedResourcesArgs();
    }
}
