// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class ClusterCustomerManagedResourcesGcpGkeServiceAccountGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// GCP service account email.
        /// </summary>
        [Input("email", required: true)]
        public Input<string> Email { get; set; } = null!;

        public ClusterCustomerManagedResourcesGcpGkeServiceAccountGetArgs()
        {
        }
        public static new ClusterCustomerManagedResourcesGcpGkeServiceAccountGetArgs Empty => new ClusterCustomerManagedResourcesGcpGkeServiceAccountGetArgs();
    }
}
