// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class ClusterPrometheusArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Prometheus metrics endpoint URL.
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        public ClusterPrometheusArgs()
        {
        }
        public static new ClusterPrometheusArgs Empty => new ClusterPrometheusArgs();
    }
}
