// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class ClusterSchemaRegistryArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// mTLS configuration.
        /// </summary>
        [Input("mtls")]
        public Input<Inputs.ClusterSchemaRegistryMtlsArgs>? Mtls { get; set; }

        /// <summary>
        /// The Schema Registry URL.
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        public ClusterSchemaRegistryArgs()
        {
        }
        public static new ClusterSchemaRegistryArgs Empty => new ClusterSchemaRegistryArgs();
    }
}
