// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class ClusterGcpPrivateServiceConnectStatusConnectedEndpointGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The connection ID.
        /// </summary>
        [Input("connectionId")]
        public Input<string>? ConnectionId { get; set; }

        /// <summary>
        /// The consumer network.
        /// </summary>
        [Input("consumerNetwork")]
        public Input<string>? ConsumerNetwork { get; set; }

        /// <summary>
        /// The endpoint address.
        /// </summary>
        [Input("endpoint")]
        public Input<string>? Endpoint { get; set; }

        /// <summary>
        /// Status of the endpoint connection.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        public ClusterGcpPrivateServiceConnectStatusConnectedEndpointGetArgs()
        {
        }
        public static new ClusterGcpPrivateServiceConnectStatusConnectedEndpointGetArgs Empty => new ClusterGcpPrivateServiceConnectStatusConnectedEndpointGetArgs();
    }
}
