// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class NetworkCustomerManagedResourcesGcpManagementBucketGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// GCP storage bucket name for storing the state of Redpanda cluster deployment
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public NetworkCustomerManagedResourcesGcpManagementBucketGetArgs()
        {
        }
        public static new NetworkCustomerManagedResourcesGcpManagementBucketGetArgs Empty => new NetworkCustomerManagedResourcesGcpManagementBucketGetArgs();
    }
}
