// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class NetworkCustomerManagedResourcesAwsPrivateSubnetsArgs : global::Pulumi.ResourceArgs
    {
        [Input("arns", required: true)]
        private InputList<string>? _arns;

        /// <summary>
        /// AWS private subnet identifiers
        /// </summary>
        public InputList<string> Arns
        {
            get => _arns ?? (_arns = new InputList<string>());
            set => _arns = value;
        }

        public NetworkCustomerManagedResourcesAwsPrivateSubnetsArgs()
        {
        }
        public static new NetworkCustomerManagedResourcesAwsPrivateSubnetsArgs Empty => new NetworkCustomerManagedResourcesAwsPrivateSubnetsArgs();
    }
}
