// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class NetworkCustomerManagedResourcesGcpArgs : global::Pulumi.ResourceArgs
    {
        [Input("managementBucket", required: true)]
        public Input<Inputs.NetworkCustomerManagedResourcesGcpManagementBucketArgs> ManagementBucket { get; set; } = null!;

        /// <summary>
        /// Name of user-created network where the Redpanda cluster is deployed
        /// </summary>
        [Input("networkName", required: true)]
        public Input<string> NetworkName { get; set; } = null!;

        /// <summary>
        /// GCP project ID where the network is created
        /// </summary>
        [Input("networkProjectId", required: true)]
        public Input<string> NetworkProjectId { get; set; } = null!;

        public NetworkCustomerManagedResourcesGcpArgs()
        {
        }
        public static new NetworkCustomerManagedResourcesGcpArgs Empty => new NetworkCustomerManagedResourcesGcpArgs();
    }
}
