// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class NetworkCustomerManagedResourcesAwsArgs : global::Pulumi.ResourceArgs
    {
        [Input("dynamodbTable", required: true)]
        public Input<Inputs.NetworkCustomerManagedResourcesAwsDynamodbTableArgs> DynamodbTable { get; set; } = null!;

        [Input("managementBucket", required: true)]
        public Input<Inputs.NetworkCustomerManagedResourcesAwsManagementBucketArgs> ManagementBucket { get; set; } = null!;

        [Input("privateSubnets", required: true)]
        public Input<Inputs.NetworkCustomerManagedResourcesAwsPrivateSubnetsArgs> PrivateSubnets { get; set; } = null!;

        [Input("vpc", required: true)]
        public Input<Inputs.NetworkCustomerManagedResourcesAwsVpcArgs> Vpc { get; set; } = null!;

        public NetworkCustomerManagedResourcesAwsArgs()
        {
        }
        public static new NetworkCustomerManagedResourcesAwsArgs Empty => new NetworkCustomerManagedResourcesAwsArgs();
    }
}
