// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class SchemaReferenceGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the referenced schema.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// The subject of the referenced schema.
        /// </summary>
        [Input("subject", required: true)]
        public Input<string> Subject { get; set; } = null!;

        /// <summary>
        /// The version of the referenced schema.
        /// </summary>
        [Input("version", required: true)]
        public Input<int> Version { get; set; } = null!;

        public SchemaReferenceGetArgs()
        {
        }
        public static new SchemaReferenceGetArgs Empty => new SchemaReferenceGetArgs();
    }
}
