// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class ServerlessClusterKafkaApiArgs : global::Pulumi.ResourceArgs
    {
        [Input("privateSeedBrokers")]
        private InputList<string>? _privateSeedBrokers;

        /// <summary>
        /// Private Kafka API seed brokers (bootstrap servers)
        /// </summary>
        public InputList<string> PrivateSeedBrokers
        {
            get => _privateSeedBrokers ?? (_privateSeedBrokers = new InputList<string>());
            set => _privateSeedBrokers = value;
        }

        [Input("seedBrokers")]
        private InputList<string>? _seedBrokers;

        /// <summary>
        /// Public Kafka API seed brokers (bootstrap servers)
        /// </summary>
        public InputList<string> SeedBrokers
        {
            get => _seedBrokers ?? (_seedBrokers = new InputList<string>());
            set => _seedBrokers = value;
        }

        public ServerlessClusterKafkaApiArgs()
        {
        }
        public static new ServerlessClusterKafkaApiArgs Empty => new ServerlessClusterKafkaApiArgs();
    }
}
