// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class ServerlessPrivateLinkCloudProviderConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// AWS-specific configuration. Required when CloudProvider is 'aws'.
        /// </summary>
        [Input("aws")]
        public Input<Inputs.ServerlessPrivateLinkCloudProviderConfigAwsArgs>? Aws { get; set; }

        public ServerlessPrivateLinkCloudProviderConfigArgs()
        {
        }
        public static new ServerlessPrivateLinkCloudProviderConfigArgs Empty => new ServerlessPrivateLinkCloudProviderConfigArgs();
    }
}
