// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class ServerlessClusterNetworkingConfigGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Private network state. Valid values: STATE_UNSPECIFIED, STATE_DISABLED, STATE_ENABLED
        /// </summary>
        [Input("private")]
        public Input<string>? Private { get; set; }

        /// <summary>
        /// Public network state. Valid values: STATE_UNSPECIFIED, STATE_DISABLED, STATE_ENABLED
        /// </summary>
        [Input("public")]
        public Input<string>? Public { get; set; }

        public ServerlessClusterNetworkingConfigGetArgs()
        {
        }
        public static new ServerlessClusterNetworkingConfigGetArgs Empty => new ServerlessClusterNetworkingConfigGetArgs();
    }
}
