// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class ServerlessClusterPrometheusGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Private Prometheus metrics URL
        /// </summary>
        [Input("privateUrl")]
        public Input<string>? PrivateUrl { get; set; }

        /// <summary>
        /// Public Prometheus metrics URL
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        public ServerlessClusterPrometheusGetArgs()
        {
        }
        public static new ServerlessClusterPrometheusGetArgs Empty => new ServerlessClusterPrometheusGetArgs();
    }
}
