// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Redpanda.Inputs
{

    public sealed class ServerlessPrivateLinkStatusAwsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("availabilityZones")]
        private InputList<string>? _availabilityZones;

        /// <summary>
        /// Availability zones where the private link endpoint service is available
        /// </summary>
        public InputList<string> AvailabilityZones
        {
            get => _availabilityZones ?? (_availabilityZones = new InputList<string>());
            set => _availabilityZones = value;
        }

        /// <summary>
        /// VPC endpoint service name for connecting to the private link
        /// </summary>
        [Input("vpcEndpointServiceName")]
        public Input<string>? VpcEndpointServiceName { get; set; }

        public ServerlessPrivateLinkStatusAwsGetArgs()
        {
        }
        public static new ServerlessPrivateLinkStatusAwsGetArgs Empty => new ServerlessPrivateLinkStatusAwsGetArgs();
    }
}
