// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package redpanda

import (
	"context"
	"reflect"

	"errors"
	"github.com/primait/pulumi-redpanda/sdk/go/redpanda/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Cluster struct {
	pulumi.CustomResourceState

	// Allows deletion of the cluster. Defaults to false.
	AllowDeletion pulumi.BoolOutput `pulumi:"allowDeletion"`
	// AWS PrivateLink configuration.
	AwsPrivateLink ClusterAwsPrivateLinkPtrOutput `pulumi:"awsPrivateLink"`
	// Azure Private Link configuration.
	AzurePrivateLink ClusterAzurePrivateLinkPtrOutput `pulumi:"azurePrivateLink"`
	// Cloud provider where resources are created.
	CloudProvider pulumi.StringOutput `pulumi:"cloudProvider"`
	// The URL of the cluster API.
	ClusterApiUrl pulumi.StringOutput `pulumi:"clusterApiUrl"`
	// Configuration for the cluster.
	ClusterConfiguration ClusterClusterConfigurationOutput `pulumi:"clusterConfiguration"`
	// Cluster type. Type is immutable and can only be set on cluster creation. Can be either byoc or dedicated.
	ClusterType pulumi.StringOutput `pulumi:"clusterType"`
	// Cluster connection type. Private clusters are not exposed to the internet. For BYOC clusters, private is best-practice.
	ConnectionType pulumi.StringOutput `pulumi:"connectionType"`
	// Timestamp when the cluster was created.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Customer managed resources configuration for the cluster.
	CustomerManagedResources ClusterCustomerManagedResourcesPtrOutput `pulumi:"customerManagedResources"`
	// If true, GCP global access is enabled.
	GcpGlobalAccessEnabled pulumi.BoolPtrOutput `pulumi:"gcpGlobalAccessEnabled"`
	// GCP Private Service Connect configuration.
	GcpPrivateServiceConnect ClusterGcpPrivateServiceConnectPtrOutput `pulumi:"gcpPrivateServiceConnect"`
	// HTTP Proxy properties.
	HttpProxy ClusterHttpProxyOutput `pulumi:"httpProxy"`
	// Cluster's Kafka API properties.
	KafkaApi ClusterKafkaApiOutput `pulumi:"kafkaApi"`
	// Kafka Connect configuration.
	KafkaConnect ClusterKafkaConnectOutput `pulumi:"kafkaConnect"`
	// Maintenance window configuration for the cluster.
	MaintenanceWindowConfig ClusterMaintenanceWindowConfigOutput `pulumi:"maintenanceWindowConfig"`
	// Unique name of the cluster.
	Name pulumi.StringOutput `pulumi:"name"`
	// Network ID where cluster is placed.
	NetworkId pulumi.StringOutput `pulumi:"networkId"`
	// Prometheus metrics endpoint properties.
	Prometheus ClusterPrometheusOutput `pulumi:"prometheus"`
	// IDs of clusters that can create read-only topics from this cluster.
	ReadReplicaClusterIds pulumi.StringArrayOutput `pulumi:"readReplicaClusterIds"`
	// Redpanda Console properties.
	RedpandaConsole ClusterRedpandaConsoleOutput `pulumi:"redpandaConsole"`
	// Number of Redpanda nodes in the cluster. NOTE: This feature is not available for all customers by default. Contact your Redpanda account team to enable this feature.
	RedpandaNodeCount pulumi.IntOutput `pulumi:"redpandaNodeCount"`
	// Current Redpanda version of the cluster.
	RedpandaVersion pulumi.StringPtrOutput `pulumi:"redpandaVersion"`
	// Cloud provider region. Region represents the name of the region where the cluster will be provisioned.
	Region pulumi.StringOutput `pulumi:"region"`
	// Resource group ID of the cluster.
	ResourceGroupId pulumi.StringOutput `pulumi:"resourceGroupId"`
	// Schema Registry properties.
	SchemaRegistry ClusterSchemaRegistryOutput `pulumi:"schemaRegistry"`
	// Current state of the cluster.
	State pulumi.StringOutput `pulumi:"state"`
	// Detailed state description when cluster is in a non-ready state.
	StateDescription ClusterStateDescriptionOutput `pulumi:"stateDescription"`
	// Tags placed on cloud resources. If the cloud provider is GCP and the name of a tag has the prefix "gcp.network-tag.", the tag is a network tag that will be added to the Redpanda cluster GKE nodes. Otherwise, the tag is a normal tag. For example, if the name of a tag is "gcp.network-tag.network-tag-foo", the network tag named "network-tag-foo" will be added to the Redpanda cluster GKE nodes. Note: The value of a network tag will be ignored. See the details on network tags at https://cloud.google.com/vpc/docs/add-remove-network-tags.
	Tags pulumi.StringMapOutput `pulumi:"tags"`
	// Usage tier of the cluster.
	ThroughputTier pulumi.StringOutput      `pulumi:"throughputTier"`
	Timeouts       ClusterTimeoutsPtrOutput `pulumi:"timeouts"`
	// Zones of the cluster. Must be valid zones within the selected region. If multiple zones are used, the cluster is a multi-AZ cluster.
	Zones pulumi.StringArrayOutput `pulumi:"zones"`
}

// NewCluster registers a new resource with the given unique name, arguments, and options.
func NewCluster(ctx *pulumi.Context,
	name string, args *ClusterArgs, opts ...pulumi.ResourceOption) (*Cluster, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.CloudProvider == nil {
		return nil, errors.New("invalid value for required argument 'CloudProvider'")
	}
	if args.ClusterType == nil {
		return nil, errors.New("invalid value for required argument 'ClusterType'")
	}
	if args.ConnectionType == nil {
		return nil, errors.New("invalid value for required argument 'ConnectionType'")
	}
	if args.NetworkId == nil {
		return nil, errors.New("invalid value for required argument 'NetworkId'")
	}
	if args.Region == nil {
		return nil, errors.New("invalid value for required argument 'Region'")
	}
	if args.ResourceGroupId == nil {
		return nil, errors.New("invalid value for required argument 'ResourceGroupId'")
	}
	if args.ThroughputTier == nil {
		return nil, errors.New("invalid value for required argument 'ThroughputTier'")
	}
	if args.Zones == nil {
		return nil, errors.New("invalid value for required argument 'Zones'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Cluster
	err := ctx.RegisterResource("redpanda:index/cluster:Cluster", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCluster gets an existing Cluster resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCluster(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ClusterState, opts ...pulumi.ResourceOption) (*Cluster, error) {
	var resource Cluster
	err := ctx.ReadResource("redpanda:index/cluster:Cluster", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Cluster resources.
type clusterState struct {
	// Allows deletion of the cluster. Defaults to false.
	AllowDeletion *bool `pulumi:"allowDeletion"`
	// AWS PrivateLink configuration.
	AwsPrivateLink *ClusterAwsPrivateLink `pulumi:"awsPrivateLink"`
	// Azure Private Link configuration.
	AzurePrivateLink *ClusterAzurePrivateLink `pulumi:"azurePrivateLink"`
	// Cloud provider where resources are created.
	CloudProvider *string `pulumi:"cloudProvider"`
	// The URL of the cluster API.
	ClusterApiUrl *string `pulumi:"clusterApiUrl"`
	// Configuration for the cluster.
	ClusterConfiguration *ClusterClusterConfiguration `pulumi:"clusterConfiguration"`
	// Cluster type. Type is immutable and can only be set on cluster creation. Can be either byoc or dedicated.
	ClusterType *string `pulumi:"clusterType"`
	// Cluster connection type. Private clusters are not exposed to the internet. For BYOC clusters, private is best-practice.
	ConnectionType *string `pulumi:"connectionType"`
	// Timestamp when the cluster was created.
	CreatedAt *string `pulumi:"createdAt"`
	// Customer managed resources configuration for the cluster.
	CustomerManagedResources *ClusterCustomerManagedResources `pulumi:"customerManagedResources"`
	// If true, GCP global access is enabled.
	GcpGlobalAccessEnabled *bool `pulumi:"gcpGlobalAccessEnabled"`
	// GCP Private Service Connect configuration.
	GcpPrivateServiceConnect *ClusterGcpPrivateServiceConnect `pulumi:"gcpPrivateServiceConnect"`
	// HTTP Proxy properties.
	HttpProxy *ClusterHttpProxy `pulumi:"httpProxy"`
	// Cluster's Kafka API properties.
	KafkaApi *ClusterKafkaApi `pulumi:"kafkaApi"`
	// Kafka Connect configuration.
	KafkaConnect *ClusterKafkaConnect `pulumi:"kafkaConnect"`
	// Maintenance window configuration for the cluster.
	MaintenanceWindowConfig *ClusterMaintenanceWindowConfig `pulumi:"maintenanceWindowConfig"`
	// Unique name of the cluster.
	Name *string `pulumi:"name"`
	// Network ID where cluster is placed.
	NetworkId *string `pulumi:"networkId"`
	// Prometheus metrics endpoint properties.
	Prometheus *ClusterPrometheus `pulumi:"prometheus"`
	// IDs of clusters that can create read-only topics from this cluster.
	ReadReplicaClusterIds []string `pulumi:"readReplicaClusterIds"`
	// Redpanda Console properties.
	RedpandaConsole *ClusterRedpandaConsole `pulumi:"redpandaConsole"`
	// Number of Redpanda nodes in the cluster. NOTE: This feature is not available for all customers by default. Contact your Redpanda account team to enable this feature.
	RedpandaNodeCount *int `pulumi:"redpandaNodeCount"`
	// Current Redpanda version of the cluster.
	RedpandaVersion *string `pulumi:"redpandaVersion"`
	// Cloud provider region. Region represents the name of the region where the cluster will be provisioned.
	Region *string `pulumi:"region"`
	// Resource group ID of the cluster.
	ResourceGroupId *string `pulumi:"resourceGroupId"`
	// Schema Registry properties.
	SchemaRegistry *ClusterSchemaRegistry `pulumi:"schemaRegistry"`
	// Current state of the cluster.
	State *string `pulumi:"state"`
	// Detailed state description when cluster is in a non-ready state.
	StateDescription *ClusterStateDescription `pulumi:"stateDescription"`
	// Tags placed on cloud resources. If the cloud provider is GCP and the name of a tag has the prefix "gcp.network-tag.", the tag is a network tag that will be added to the Redpanda cluster GKE nodes. Otherwise, the tag is a normal tag. For example, if the name of a tag is "gcp.network-tag.network-tag-foo", the network tag named "network-tag-foo" will be added to the Redpanda cluster GKE nodes. Note: The value of a network tag will be ignored. See the details on network tags at https://cloud.google.com/vpc/docs/add-remove-network-tags.
	Tags map[string]string `pulumi:"tags"`
	// Usage tier of the cluster.
	ThroughputTier *string          `pulumi:"throughputTier"`
	Timeouts       *ClusterTimeouts `pulumi:"timeouts"`
	// Zones of the cluster. Must be valid zones within the selected region. If multiple zones are used, the cluster is a multi-AZ cluster.
	Zones []string `pulumi:"zones"`
}

type ClusterState struct {
	// Allows deletion of the cluster. Defaults to false.
	AllowDeletion pulumi.BoolPtrInput
	// AWS PrivateLink configuration.
	AwsPrivateLink ClusterAwsPrivateLinkPtrInput
	// Azure Private Link configuration.
	AzurePrivateLink ClusterAzurePrivateLinkPtrInput
	// Cloud provider where resources are created.
	CloudProvider pulumi.StringPtrInput
	// The URL of the cluster API.
	ClusterApiUrl pulumi.StringPtrInput
	// Configuration for the cluster.
	ClusterConfiguration ClusterClusterConfigurationPtrInput
	// Cluster type. Type is immutable and can only be set on cluster creation. Can be either byoc or dedicated.
	ClusterType pulumi.StringPtrInput
	// Cluster connection type. Private clusters are not exposed to the internet. For BYOC clusters, private is best-practice.
	ConnectionType pulumi.StringPtrInput
	// Timestamp when the cluster was created.
	CreatedAt pulumi.StringPtrInput
	// Customer managed resources configuration for the cluster.
	CustomerManagedResources ClusterCustomerManagedResourcesPtrInput
	// If true, GCP global access is enabled.
	GcpGlobalAccessEnabled pulumi.BoolPtrInput
	// GCP Private Service Connect configuration.
	GcpPrivateServiceConnect ClusterGcpPrivateServiceConnectPtrInput
	// HTTP Proxy properties.
	HttpProxy ClusterHttpProxyPtrInput
	// Cluster's Kafka API properties.
	KafkaApi ClusterKafkaApiPtrInput
	// Kafka Connect configuration.
	KafkaConnect ClusterKafkaConnectPtrInput
	// Maintenance window configuration for the cluster.
	MaintenanceWindowConfig ClusterMaintenanceWindowConfigPtrInput
	// Unique name of the cluster.
	Name pulumi.StringPtrInput
	// Network ID where cluster is placed.
	NetworkId pulumi.StringPtrInput
	// Prometheus metrics endpoint properties.
	Prometheus ClusterPrometheusPtrInput
	// IDs of clusters that can create read-only topics from this cluster.
	ReadReplicaClusterIds pulumi.StringArrayInput
	// Redpanda Console properties.
	RedpandaConsole ClusterRedpandaConsolePtrInput
	// Number of Redpanda nodes in the cluster. NOTE: This feature is not available for all customers by default. Contact your Redpanda account team to enable this feature.
	RedpandaNodeCount pulumi.IntPtrInput
	// Current Redpanda version of the cluster.
	RedpandaVersion pulumi.StringPtrInput
	// Cloud provider region. Region represents the name of the region where the cluster will be provisioned.
	Region pulumi.StringPtrInput
	// Resource group ID of the cluster.
	ResourceGroupId pulumi.StringPtrInput
	// Schema Registry properties.
	SchemaRegistry ClusterSchemaRegistryPtrInput
	// Current state of the cluster.
	State pulumi.StringPtrInput
	// Detailed state description when cluster is in a non-ready state.
	StateDescription ClusterStateDescriptionPtrInput
	// Tags placed on cloud resources. If the cloud provider is GCP and the name of a tag has the prefix "gcp.network-tag.", the tag is a network tag that will be added to the Redpanda cluster GKE nodes. Otherwise, the tag is a normal tag. For example, if the name of a tag is "gcp.network-tag.network-tag-foo", the network tag named "network-tag-foo" will be added to the Redpanda cluster GKE nodes. Note: The value of a network tag will be ignored. See the details on network tags at https://cloud.google.com/vpc/docs/add-remove-network-tags.
	Tags pulumi.StringMapInput
	// Usage tier of the cluster.
	ThroughputTier pulumi.StringPtrInput
	Timeouts       ClusterTimeoutsPtrInput
	// Zones of the cluster. Must be valid zones within the selected region. If multiple zones are used, the cluster is a multi-AZ cluster.
	Zones pulumi.StringArrayInput
}

func (ClusterState) ElementType() reflect.Type {
	return reflect.TypeOf((*clusterState)(nil)).Elem()
}

type clusterArgs struct {
	// Allows deletion of the cluster. Defaults to false.
	AllowDeletion *bool `pulumi:"allowDeletion"`
	// AWS PrivateLink configuration.
	AwsPrivateLink *ClusterAwsPrivateLink `pulumi:"awsPrivateLink"`
	// Azure Private Link configuration.
	AzurePrivateLink *ClusterAzurePrivateLink `pulumi:"azurePrivateLink"`
	// Cloud provider where resources are created.
	CloudProvider string `pulumi:"cloudProvider"`
	// Configuration for the cluster.
	ClusterConfiguration *ClusterClusterConfiguration `pulumi:"clusterConfiguration"`
	// Cluster type. Type is immutable and can only be set on cluster creation. Can be either byoc or dedicated.
	ClusterType string `pulumi:"clusterType"`
	// Cluster connection type. Private clusters are not exposed to the internet. For BYOC clusters, private is best-practice.
	ConnectionType string `pulumi:"connectionType"`
	// Customer managed resources configuration for the cluster.
	CustomerManagedResources *ClusterCustomerManagedResources `pulumi:"customerManagedResources"`
	// If true, GCP global access is enabled.
	GcpGlobalAccessEnabled *bool `pulumi:"gcpGlobalAccessEnabled"`
	// GCP Private Service Connect configuration.
	GcpPrivateServiceConnect *ClusterGcpPrivateServiceConnect `pulumi:"gcpPrivateServiceConnect"`
	// HTTP Proxy properties.
	HttpProxy *ClusterHttpProxy `pulumi:"httpProxy"`
	// Cluster's Kafka API properties.
	KafkaApi *ClusterKafkaApi `pulumi:"kafkaApi"`
	// Kafka Connect configuration.
	KafkaConnect *ClusterKafkaConnect `pulumi:"kafkaConnect"`
	// Maintenance window configuration for the cluster.
	MaintenanceWindowConfig *ClusterMaintenanceWindowConfig `pulumi:"maintenanceWindowConfig"`
	// Unique name of the cluster.
	Name *string `pulumi:"name"`
	// Network ID where cluster is placed.
	NetworkId string `pulumi:"networkId"`
	// IDs of clusters that can create read-only topics from this cluster.
	ReadReplicaClusterIds []string `pulumi:"readReplicaClusterIds"`
	// Number of Redpanda nodes in the cluster. NOTE: This feature is not available for all customers by default. Contact your Redpanda account team to enable this feature.
	RedpandaNodeCount *int `pulumi:"redpandaNodeCount"`
	// Current Redpanda version of the cluster.
	RedpandaVersion *string `pulumi:"redpandaVersion"`
	// Cloud provider region. Region represents the name of the region where the cluster will be provisioned.
	Region string `pulumi:"region"`
	// Resource group ID of the cluster.
	ResourceGroupId string `pulumi:"resourceGroupId"`
	// Schema Registry properties.
	SchemaRegistry *ClusterSchemaRegistry `pulumi:"schemaRegistry"`
	// Tags placed on cloud resources. If the cloud provider is GCP and the name of a tag has the prefix "gcp.network-tag.", the tag is a network tag that will be added to the Redpanda cluster GKE nodes. Otherwise, the tag is a normal tag. For example, if the name of a tag is "gcp.network-tag.network-tag-foo", the network tag named "network-tag-foo" will be added to the Redpanda cluster GKE nodes. Note: The value of a network tag will be ignored. See the details on network tags at https://cloud.google.com/vpc/docs/add-remove-network-tags.
	Tags map[string]string `pulumi:"tags"`
	// Usage tier of the cluster.
	ThroughputTier string           `pulumi:"throughputTier"`
	Timeouts       *ClusterTimeouts `pulumi:"timeouts"`
	// Zones of the cluster. Must be valid zones within the selected region. If multiple zones are used, the cluster is a multi-AZ cluster.
	Zones []string `pulumi:"zones"`
}

// The set of arguments for constructing a Cluster resource.
type ClusterArgs struct {
	// Allows deletion of the cluster. Defaults to false.
	AllowDeletion pulumi.BoolPtrInput
	// AWS PrivateLink configuration.
	AwsPrivateLink ClusterAwsPrivateLinkPtrInput
	// Azure Private Link configuration.
	AzurePrivateLink ClusterAzurePrivateLinkPtrInput
	// Cloud provider where resources are created.
	CloudProvider pulumi.StringInput
	// Configuration for the cluster.
	ClusterConfiguration ClusterClusterConfigurationPtrInput
	// Cluster type. Type is immutable and can only be set on cluster creation. Can be either byoc or dedicated.
	ClusterType pulumi.StringInput
	// Cluster connection type. Private clusters are not exposed to the internet. For BYOC clusters, private is best-practice.
	ConnectionType pulumi.StringInput
	// Customer managed resources configuration for the cluster.
	CustomerManagedResources ClusterCustomerManagedResourcesPtrInput
	// If true, GCP global access is enabled.
	GcpGlobalAccessEnabled pulumi.BoolPtrInput
	// GCP Private Service Connect configuration.
	GcpPrivateServiceConnect ClusterGcpPrivateServiceConnectPtrInput
	// HTTP Proxy properties.
	HttpProxy ClusterHttpProxyPtrInput
	// Cluster's Kafka API properties.
	KafkaApi ClusterKafkaApiPtrInput
	// Kafka Connect configuration.
	KafkaConnect ClusterKafkaConnectPtrInput
	// Maintenance window configuration for the cluster.
	MaintenanceWindowConfig ClusterMaintenanceWindowConfigPtrInput
	// Unique name of the cluster.
	Name pulumi.StringPtrInput
	// Network ID where cluster is placed.
	NetworkId pulumi.StringInput
	// IDs of clusters that can create read-only topics from this cluster.
	ReadReplicaClusterIds pulumi.StringArrayInput
	// Number of Redpanda nodes in the cluster. NOTE: This feature is not available for all customers by default. Contact your Redpanda account team to enable this feature.
	RedpandaNodeCount pulumi.IntPtrInput
	// Current Redpanda version of the cluster.
	RedpandaVersion pulumi.StringPtrInput
	// Cloud provider region. Region represents the name of the region where the cluster will be provisioned.
	Region pulumi.StringInput
	// Resource group ID of the cluster.
	ResourceGroupId pulumi.StringInput
	// Schema Registry properties.
	SchemaRegistry ClusterSchemaRegistryPtrInput
	// Tags placed on cloud resources. If the cloud provider is GCP and the name of a tag has the prefix "gcp.network-tag.", the tag is a network tag that will be added to the Redpanda cluster GKE nodes. Otherwise, the tag is a normal tag. For example, if the name of a tag is "gcp.network-tag.network-tag-foo", the network tag named "network-tag-foo" will be added to the Redpanda cluster GKE nodes. Note: The value of a network tag will be ignored. See the details on network tags at https://cloud.google.com/vpc/docs/add-remove-network-tags.
	Tags pulumi.StringMapInput
	// Usage tier of the cluster.
	ThroughputTier pulumi.StringInput
	Timeouts       ClusterTimeoutsPtrInput
	// Zones of the cluster. Must be valid zones within the selected region. If multiple zones are used, the cluster is a multi-AZ cluster.
	Zones pulumi.StringArrayInput
}

func (ClusterArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*clusterArgs)(nil)).Elem()
}

type ClusterInput interface {
	pulumi.Input

	ToClusterOutput() ClusterOutput
	ToClusterOutputWithContext(ctx context.Context) ClusterOutput
}

func (*Cluster) ElementType() reflect.Type {
	return reflect.TypeOf((**Cluster)(nil)).Elem()
}

func (i *Cluster) ToClusterOutput() ClusterOutput {
	return i.ToClusterOutputWithContext(context.Background())
}

func (i *Cluster) ToClusterOutputWithContext(ctx context.Context) ClusterOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterOutput)
}

// ClusterArrayInput is an input type that accepts ClusterArray and ClusterArrayOutput values.
// You can construct a concrete instance of `ClusterArrayInput` via:
//
//	ClusterArray{ ClusterArgs{...} }
type ClusterArrayInput interface {
	pulumi.Input

	ToClusterArrayOutput() ClusterArrayOutput
	ToClusterArrayOutputWithContext(context.Context) ClusterArrayOutput
}

type ClusterArray []ClusterInput

func (ClusterArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Cluster)(nil)).Elem()
}

func (i ClusterArray) ToClusterArrayOutput() ClusterArrayOutput {
	return i.ToClusterArrayOutputWithContext(context.Background())
}

func (i ClusterArray) ToClusterArrayOutputWithContext(ctx context.Context) ClusterArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterArrayOutput)
}

// ClusterMapInput is an input type that accepts ClusterMap and ClusterMapOutput values.
// You can construct a concrete instance of `ClusterMapInput` via:
//
//	ClusterMap{ "key": ClusterArgs{...} }
type ClusterMapInput interface {
	pulumi.Input

	ToClusterMapOutput() ClusterMapOutput
	ToClusterMapOutputWithContext(context.Context) ClusterMapOutput
}

type ClusterMap map[string]ClusterInput

func (ClusterMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Cluster)(nil)).Elem()
}

func (i ClusterMap) ToClusterMapOutput() ClusterMapOutput {
	return i.ToClusterMapOutputWithContext(context.Background())
}

func (i ClusterMap) ToClusterMapOutputWithContext(ctx context.Context) ClusterMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterMapOutput)
}

type ClusterOutput struct{ *pulumi.OutputState }

func (ClusterOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Cluster)(nil)).Elem()
}

func (o ClusterOutput) ToClusterOutput() ClusterOutput {
	return o
}

func (o ClusterOutput) ToClusterOutputWithContext(ctx context.Context) ClusterOutput {
	return o
}

// Allows deletion of the cluster. Defaults to false.
func (o ClusterOutput) AllowDeletion() pulumi.BoolOutput {
	return o.ApplyT(func(v *Cluster) pulumi.BoolOutput { return v.AllowDeletion }).(pulumi.BoolOutput)
}

// AWS PrivateLink configuration.
func (o ClusterOutput) AwsPrivateLink() ClusterAwsPrivateLinkPtrOutput {
	return o.ApplyT(func(v *Cluster) ClusterAwsPrivateLinkPtrOutput { return v.AwsPrivateLink }).(ClusterAwsPrivateLinkPtrOutput)
}

// Azure Private Link configuration.
func (o ClusterOutput) AzurePrivateLink() ClusterAzurePrivateLinkPtrOutput {
	return o.ApplyT(func(v *Cluster) ClusterAzurePrivateLinkPtrOutput { return v.AzurePrivateLink }).(ClusterAzurePrivateLinkPtrOutput)
}

// Cloud provider where resources are created.
func (o ClusterOutput) CloudProvider() pulumi.StringOutput {
	return o.ApplyT(func(v *Cluster) pulumi.StringOutput { return v.CloudProvider }).(pulumi.StringOutput)
}

// The URL of the cluster API.
func (o ClusterOutput) ClusterApiUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *Cluster) pulumi.StringOutput { return v.ClusterApiUrl }).(pulumi.StringOutput)
}

// Configuration for the cluster.
func (o ClusterOutput) ClusterConfiguration() ClusterClusterConfigurationOutput {
	return o.ApplyT(func(v *Cluster) ClusterClusterConfigurationOutput { return v.ClusterConfiguration }).(ClusterClusterConfigurationOutput)
}

// Cluster type. Type is immutable and can only be set on cluster creation. Can be either byoc or dedicated.
func (o ClusterOutput) ClusterType() pulumi.StringOutput {
	return o.ApplyT(func(v *Cluster) pulumi.StringOutput { return v.ClusterType }).(pulumi.StringOutput)
}

// Cluster connection type. Private clusters are not exposed to the internet. For BYOC clusters, private is best-practice.
func (o ClusterOutput) ConnectionType() pulumi.StringOutput {
	return o.ApplyT(func(v *Cluster) pulumi.StringOutput { return v.ConnectionType }).(pulumi.StringOutput)
}

// Timestamp when the cluster was created.
func (o ClusterOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Cluster) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Customer managed resources configuration for the cluster.
func (o ClusterOutput) CustomerManagedResources() ClusterCustomerManagedResourcesPtrOutput {
	return o.ApplyT(func(v *Cluster) ClusterCustomerManagedResourcesPtrOutput { return v.CustomerManagedResources }).(ClusterCustomerManagedResourcesPtrOutput)
}

// If true, GCP global access is enabled.
func (o ClusterOutput) GcpGlobalAccessEnabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Cluster) pulumi.BoolPtrOutput { return v.GcpGlobalAccessEnabled }).(pulumi.BoolPtrOutput)
}

// GCP Private Service Connect configuration.
func (o ClusterOutput) GcpPrivateServiceConnect() ClusterGcpPrivateServiceConnectPtrOutput {
	return o.ApplyT(func(v *Cluster) ClusterGcpPrivateServiceConnectPtrOutput { return v.GcpPrivateServiceConnect }).(ClusterGcpPrivateServiceConnectPtrOutput)
}

// HTTP Proxy properties.
func (o ClusterOutput) HttpProxy() ClusterHttpProxyOutput {
	return o.ApplyT(func(v *Cluster) ClusterHttpProxyOutput { return v.HttpProxy }).(ClusterHttpProxyOutput)
}

// Cluster's Kafka API properties.
func (o ClusterOutput) KafkaApi() ClusterKafkaApiOutput {
	return o.ApplyT(func(v *Cluster) ClusterKafkaApiOutput { return v.KafkaApi }).(ClusterKafkaApiOutput)
}

// Kafka Connect configuration.
func (o ClusterOutput) KafkaConnect() ClusterKafkaConnectOutput {
	return o.ApplyT(func(v *Cluster) ClusterKafkaConnectOutput { return v.KafkaConnect }).(ClusterKafkaConnectOutput)
}

// Maintenance window configuration for the cluster.
func (o ClusterOutput) MaintenanceWindowConfig() ClusterMaintenanceWindowConfigOutput {
	return o.ApplyT(func(v *Cluster) ClusterMaintenanceWindowConfigOutput { return v.MaintenanceWindowConfig }).(ClusterMaintenanceWindowConfigOutput)
}

// Unique name of the cluster.
func (o ClusterOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Cluster) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Network ID where cluster is placed.
func (o ClusterOutput) NetworkId() pulumi.StringOutput {
	return o.ApplyT(func(v *Cluster) pulumi.StringOutput { return v.NetworkId }).(pulumi.StringOutput)
}

// Prometheus metrics endpoint properties.
func (o ClusterOutput) Prometheus() ClusterPrometheusOutput {
	return o.ApplyT(func(v *Cluster) ClusterPrometheusOutput { return v.Prometheus }).(ClusterPrometheusOutput)
}

// IDs of clusters that can create read-only topics from this cluster.
func (o ClusterOutput) ReadReplicaClusterIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Cluster) pulumi.StringArrayOutput { return v.ReadReplicaClusterIds }).(pulumi.StringArrayOutput)
}

// Redpanda Console properties.
func (o ClusterOutput) RedpandaConsole() ClusterRedpandaConsoleOutput {
	return o.ApplyT(func(v *Cluster) ClusterRedpandaConsoleOutput { return v.RedpandaConsole }).(ClusterRedpandaConsoleOutput)
}

// Number of Redpanda nodes in the cluster. NOTE: This feature is not available for all customers by default. Contact your Redpanda account team to enable this feature.
func (o ClusterOutput) RedpandaNodeCount() pulumi.IntOutput {
	return o.ApplyT(func(v *Cluster) pulumi.IntOutput { return v.RedpandaNodeCount }).(pulumi.IntOutput)
}

// Current Redpanda version of the cluster.
func (o ClusterOutput) RedpandaVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Cluster) pulumi.StringPtrOutput { return v.RedpandaVersion }).(pulumi.StringPtrOutput)
}

// Cloud provider region. Region represents the name of the region where the cluster will be provisioned.
func (o ClusterOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *Cluster) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

// Resource group ID of the cluster.
func (o ClusterOutput) ResourceGroupId() pulumi.StringOutput {
	return o.ApplyT(func(v *Cluster) pulumi.StringOutput { return v.ResourceGroupId }).(pulumi.StringOutput)
}

// Schema Registry properties.
func (o ClusterOutput) SchemaRegistry() ClusterSchemaRegistryOutput {
	return o.ApplyT(func(v *Cluster) ClusterSchemaRegistryOutput { return v.SchemaRegistry }).(ClusterSchemaRegistryOutput)
}

// Current state of the cluster.
func (o ClusterOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *Cluster) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

// Detailed state description when cluster is in a non-ready state.
func (o ClusterOutput) StateDescription() ClusterStateDescriptionOutput {
	return o.ApplyT(func(v *Cluster) ClusterStateDescriptionOutput { return v.StateDescription }).(ClusterStateDescriptionOutput)
}

// Tags placed on cloud resources. If the cloud provider is GCP and the name of a tag has the prefix "gcp.network-tag.", the tag is a network tag that will be added to the Redpanda cluster GKE nodes. Otherwise, the tag is a normal tag. For example, if the name of a tag is "gcp.network-tag.network-tag-foo", the network tag named "network-tag-foo" will be added to the Redpanda cluster GKE nodes. Note: The value of a network tag will be ignored. See the details on network tags at https://cloud.google.com/vpc/docs/add-remove-network-tags.
func (o ClusterOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v *Cluster) pulumi.StringMapOutput { return v.Tags }).(pulumi.StringMapOutput)
}

// Usage tier of the cluster.
func (o ClusterOutput) ThroughputTier() pulumi.StringOutput {
	return o.ApplyT(func(v *Cluster) pulumi.StringOutput { return v.ThroughputTier }).(pulumi.StringOutput)
}

func (o ClusterOutput) Timeouts() ClusterTimeoutsPtrOutput {
	return o.ApplyT(func(v *Cluster) ClusterTimeoutsPtrOutput { return v.Timeouts }).(ClusterTimeoutsPtrOutput)
}

// Zones of the cluster. Must be valid zones within the selected region. If multiple zones are used, the cluster is a multi-AZ cluster.
func (o ClusterOutput) Zones() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Cluster) pulumi.StringArrayOutput { return v.Zones }).(pulumi.StringArrayOutput)
}

type ClusterArrayOutput struct{ *pulumi.OutputState }

func (ClusterArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Cluster)(nil)).Elem()
}

func (o ClusterArrayOutput) ToClusterArrayOutput() ClusterArrayOutput {
	return o
}

func (o ClusterArrayOutput) ToClusterArrayOutputWithContext(ctx context.Context) ClusterArrayOutput {
	return o
}

func (o ClusterArrayOutput) Index(i pulumi.IntInput) ClusterOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Cluster {
		return vs[0].([]*Cluster)[vs[1].(int)]
	}).(ClusterOutput)
}

type ClusterMapOutput struct{ *pulumi.OutputState }

func (ClusterMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Cluster)(nil)).Elem()
}

func (o ClusterMapOutput) ToClusterMapOutput() ClusterMapOutput {
	return o
}

func (o ClusterMapOutput) ToClusterMapOutputWithContext(ctx context.Context) ClusterMapOutput {
	return o
}

func (o ClusterMapOutput) MapIndex(k pulumi.StringInput) ClusterOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Cluster {
		return vs[0].(map[string]*Cluster)[vs[1].(string)]
	}).(ClusterOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ClusterInput)(nil)).Elem(), &Cluster{})
	pulumi.RegisterInputType(reflect.TypeOf((*ClusterArrayInput)(nil)).Elem(), ClusterArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ClusterMapInput)(nil)).Elem(), ClusterMap{})
	pulumi.RegisterOutputType(ClusterOutput{})
	pulumi.RegisterOutputType(ClusterArrayOutput{})
	pulumi.RegisterOutputType(ClusterMapOutput{})
}
