// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package redpanda

import (
	"context"
	"reflect"

	"github.com/primait/pulumi-redpanda/sdk/go/redpanda/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupSchema(ctx *pulumi.Context, args *LookupSchemaArgs, opts ...pulumi.InvokeOption) (*LookupSchemaResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSchemaResult
	err := ctx.Invoke("redpanda:index/getSchema:getSchema", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSchema.
type LookupSchemaArgs struct {
	ClusterId string `pulumi:"clusterId"`
	Subject   string `pulumi:"subject"`
	Version   *int   `pulumi:"version"`
}

// A collection of values returned by getSchema.
type LookupSchemaResult struct {
	ClusterId  string               `pulumi:"clusterId"`
	Id         int                  `pulumi:"id"`
	References []GetSchemaReference `pulumi:"references"`
	Schema     string               `pulumi:"schema"`
	SchemaType string               `pulumi:"schemaType"`
	Subject    string               `pulumi:"subject"`
	Version    int                  `pulumi:"version"`
}

func LookupSchemaOutput(ctx *pulumi.Context, args LookupSchemaOutputArgs, opts ...pulumi.InvokeOption) LookupSchemaResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupSchemaResultOutput, error) {
			args := v.(LookupSchemaArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("redpanda:index/getSchema:getSchema", args, LookupSchemaResultOutput{}, options).(LookupSchemaResultOutput), nil
		}).(LookupSchemaResultOutput)
}

// A collection of arguments for invoking getSchema.
type LookupSchemaOutputArgs struct {
	ClusterId pulumi.StringInput `pulumi:"clusterId"`
	Subject   pulumi.StringInput `pulumi:"subject"`
	Version   pulumi.IntPtrInput `pulumi:"version"`
}

func (LookupSchemaOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSchemaArgs)(nil)).Elem()
}

// A collection of values returned by getSchema.
type LookupSchemaResultOutput struct{ *pulumi.OutputState }

func (LookupSchemaResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSchemaResult)(nil)).Elem()
}

func (o LookupSchemaResultOutput) ToLookupSchemaResultOutput() LookupSchemaResultOutput {
	return o
}

func (o LookupSchemaResultOutput) ToLookupSchemaResultOutputWithContext(ctx context.Context) LookupSchemaResultOutput {
	return o
}

func (o LookupSchemaResultOutput) ClusterId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSchemaResult) string { return v.ClusterId }).(pulumi.StringOutput)
}

func (o LookupSchemaResultOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v LookupSchemaResult) int { return v.Id }).(pulumi.IntOutput)
}

func (o LookupSchemaResultOutput) References() GetSchemaReferenceArrayOutput {
	return o.ApplyT(func(v LookupSchemaResult) []GetSchemaReference { return v.References }).(GetSchemaReferenceArrayOutput)
}

func (o LookupSchemaResultOutput) Schema() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSchemaResult) string { return v.Schema }).(pulumi.StringOutput)
}

func (o LookupSchemaResultOutput) SchemaType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSchemaResult) string { return v.SchemaType }).(pulumi.StringOutput)
}

func (o LookupSchemaResultOutput) Subject() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSchemaResult) string { return v.Subject }).(pulumi.StringOutput)
}

func (o LookupSchemaResultOutput) Version() pulumi.IntOutput {
	return o.ApplyT(func(v LookupSchemaResult) int { return v.Version }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSchemaResultOutput{})
}
