// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package redpanda

import (
	"context"
	"reflect"

	"github.com/primait/pulumi-redpanda/sdk/go/redpanda/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupServerlessCluster(ctx *pulumi.Context, args *LookupServerlessClusterArgs, opts ...pulumi.InvokeOption) (*LookupServerlessClusterResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupServerlessClusterResult
	err := ctx.Invoke("redpanda:index/getServerlessCluster:getServerlessCluster", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getServerlessCluster.
type LookupServerlessClusterArgs struct {
	Id string `pulumi:"id"`
}

// A collection of values returned by getServerlessCluster.
type LookupServerlessClusterResult struct {
	ClusterApiUrl    string `pulumi:"clusterApiUrl"`
	Id               string `pulumi:"id"`
	Name             string `pulumi:"name"`
	ResourceGroupId  string `pulumi:"resourceGroupId"`
	ServerlessRegion string `pulumi:"serverlessRegion"`
}

func LookupServerlessClusterOutput(ctx *pulumi.Context, args LookupServerlessClusterOutputArgs, opts ...pulumi.InvokeOption) LookupServerlessClusterResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupServerlessClusterResultOutput, error) {
			args := v.(LookupServerlessClusterArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("redpanda:index/getServerlessCluster:getServerlessCluster", args, LookupServerlessClusterResultOutput{}, options).(LookupServerlessClusterResultOutput), nil
		}).(LookupServerlessClusterResultOutput)
}

// A collection of arguments for invoking getServerlessCluster.
type LookupServerlessClusterOutputArgs struct {
	Id pulumi.StringInput `pulumi:"id"`
}

func (LookupServerlessClusterOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupServerlessClusterArgs)(nil)).Elem()
}

// A collection of values returned by getServerlessCluster.
type LookupServerlessClusterResultOutput struct{ *pulumi.OutputState }

func (LookupServerlessClusterResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupServerlessClusterResult)(nil)).Elem()
}

func (o LookupServerlessClusterResultOutput) ToLookupServerlessClusterResultOutput() LookupServerlessClusterResultOutput {
	return o
}

func (o LookupServerlessClusterResultOutput) ToLookupServerlessClusterResultOutputWithContext(ctx context.Context) LookupServerlessClusterResultOutput {
	return o
}

func (o LookupServerlessClusterResultOutput) ClusterApiUrl() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessClusterResult) string { return v.ClusterApiUrl }).(pulumi.StringOutput)
}

func (o LookupServerlessClusterResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessClusterResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupServerlessClusterResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessClusterResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupServerlessClusterResultOutput) ResourceGroupId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessClusterResult) string { return v.ResourceGroupId }).(pulumi.StringOutput)
}

func (o LookupServerlessClusterResultOutput) ServerlessRegion() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessClusterResult) string { return v.ServerlessRegion }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupServerlessClusterResultOutput{})
}
