// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package redpanda

import (
	"context"
	"reflect"

	"errors"
	"github.com/primait/pulumi-redpanda/sdk/go/redpanda/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Schema struct {
	pulumi.CustomResourceState

	// When enabled, prevents the resource from being deleted if the cluster is unreachable. When disabled (default), the resource will be removed from state without attempting deletion when the cluster is unreachable.
	AllowDeletion pulumi.BoolOutput `pulumi:"allowDeletion"`
	// The ID of the cluster where the schema is stored.
	ClusterId pulumi.StringOutput `pulumi:"clusterId"`
	// The compatibility level for schema evolution (BACKWARD, BACKWARD_TRANSITIVE, FORWARD, FORWARD_TRANSITIVE, FULL, FULL_TRANSITIVE, NONE). Defaults to BACKWARD.
	Compatibility pulumi.StringOutput `pulumi:"compatibility"`
	// The SASL password for Schema Registry authentication. Deprecated: use passwordWo instead.
	//
	// Deprecated: Use passwordWo instead to avoid storing password in Terraform state
	Password pulumi.StringPtrOutput `pulumi:"password"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// The SASL password for Schema Registry authentication (write-only, not stored in state). Requires Terraform 1.11+.
	PasswordWo pulumi.StringPtrOutput `pulumi:"passwordWo"`
	// Version number for password_wo. Increment this value to trigger a password update when using password_wo.
	PasswordWoVersion pulumi.IntPtrOutput `pulumi:"passwordWoVersion"`
	// List of schema references.
	References SchemaReferenceArrayOutput `pulumi:"references"`
	// The schema definition in JSON format.
	Schema pulumi.StringOutput `pulumi:"schema"`
	// The type of schema (AVRO, JSON, PROTOBUF).
	SchemaType pulumi.StringOutput `pulumi:"schemaType"`
	// The subject name for the schema.
	Subject pulumi.StringOutput `pulumi:"subject"`
	// The SASL username for Schema Registry authentication.
	Username pulumi.StringOutput `pulumi:"username"`
	// The version of the schema.
	Version pulumi.IntOutput `pulumi:"version"`
}

// NewSchema registers a new resource with the given unique name, arguments, and options.
func NewSchema(ctx *pulumi.Context,
	name string, args *SchemaArgs, opts ...pulumi.ResourceOption) (*Schema, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClusterId == nil {
		return nil, errors.New("invalid value for required argument 'ClusterId'")
	}
	if args.Schema == nil {
		return nil, errors.New("invalid value for required argument 'Schema'")
	}
	if args.Subject == nil {
		return nil, errors.New("invalid value for required argument 'Subject'")
	}
	if args.Username == nil {
		return nil, errors.New("invalid value for required argument 'Username'")
	}
	if args.Password != nil {
		args.Password = pulumi.ToSecret(args.Password).(pulumi.StringPtrInput)
	}
	if args.PasswordWo != nil {
		args.PasswordWo = pulumi.ToSecret(args.PasswordWo).(pulumi.StringPtrInput)
	}
	if args.Username != nil {
		args.Username = pulumi.ToSecret(args.Username).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"password",
		"passwordWo",
		"username",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Schema
	err := ctx.RegisterResource("redpanda:index/schema:Schema", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSchema gets an existing Schema resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSchema(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SchemaState, opts ...pulumi.ResourceOption) (*Schema, error) {
	var resource Schema
	err := ctx.ReadResource("redpanda:index/schema:Schema", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Schema resources.
type schemaState struct {
	// When enabled, prevents the resource from being deleted if the cluster is unreachable. When disabled (default), the resource will be removed from state without attempting deletion when the cluster is unreachable.
	AllowDeletion *bool `pulumi:"allowDeletion"`
	// The ID of the cluster where the schema is stored.
	ClusterId *string `pulumi:"clusterId"`
	// The compatibility level for schema evolution (BACKWARD, BACKWARD_TRANSITIVE, FORWARD, FORWARD_TRANSITIVE, FULL, FULL_TRANSITIVE, NONE). Defaults to BACKWARD.
	Compatibility *string `pulumi:"compatibility"`
	// The SASL password for Schema Registry authentication. Deprecated: use passwordWo instead.
	//
	// Deprecated: Use passwordWo instead to avoid storing password in Terraform state
	Password *string `pulumi:"password"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// The SASL password for Schema Registry authentication (write-only, not stored in state). Requires Terraform 1.11+.
	PasswordWo *string `pulumi:"passwordWo"`
	// Version number for password_wo. Increment this value to trigger a password update when using password_wo.
	PasswordWoVersion *int `pulumi:"passwordWoVersion"`
	// List of schema references.
	References []SchemaReference `pulumi:"references"`
	// The schema definition in JSON format.
	Schema *string `pulumi:"schema"`
	// The type of schema (AVRO, JSON, PROTOBUF).
	SchemaType *string `pulumi:"schemaType"`
	// The subject name for the schema.
	Subject *string `pulumi:"subject"`
	// The SASL username for Schema Registry authentication.
	Username *string `pulumi:"username"`
	// The version of the schema.
	Version *int `pulumi:"version"`
}

type SchemaState struct {
	// When enabled, prevents the resource from being deleted if the cluster is unreachable. When disabled (default), the resource will be removed from state without attempting deletion when the cluster is unreachable.
	AllowDeletion pulumi.BoolPtrInput
	// The ID of the cluster where the schema is stored.
	ClusterId pulumi.StringPtrInput
	// The compatibility level for schema evolution (BACKWARD, BACKWARD_TRANSITIVE, FORWARD, FORWARD_TRANSITIVE, FULL, FULL_TRANSITIVE, NONE). Defaults to BACKWARD.
	Compatibility pulumi.StringPtrInput
	// The SASL password for Schema Registry authentication. Deprecated: use passwordWo instead.
	//
	// Deprecated: Use passwordWo instead to avoid storing password in Terraform state
	Password pulumi.StringPtrInput
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// The SASL password for Schema Registry authentication (write-only, not stored in state). Requires Terraform 1.11+.
	PasswordWo pulumi.StringPtrInput
	// Version number for password_wo. Increment this value to trigger a password update when using password_wo.
	PasswordWoVersion pulumi.IntPtrInput
	// List of schema references.
	References SchemaReferenceArrayInput
	// The schema definition in JSON format.
	Schema pulumi.StringPtrInput
	// The type of schema (AVRO, JSON, PROTOBUF).
	SchemaType pulumi.StringPtrInput
	// The subject name for the schema.
	Subject pulumi.StringPtrInput
	// The SASL username for Schema Registry authentication.
	Username pulumi.StringPtrInput
	// The version of the schema.
	Version pulumi.IntPtrInput
}

func (SchemaState) ElementType() reflect.Type {
	return reflect.TypeOf((*schemaState)(nil)).Elem()
}

type schemaArgs struct {
	// When enabled, prevents the resource from being deleted if the cluster is unreachable. When disabled (default), the resource will be removed from state without attempting deletion when the cluster is unreachable.
	AllowDeletion *bool `pulumi:"allowDeletion"`
	// The ID of the cluster where the schema is stored.
	ClusterId string `pulumi:"clusterId"`
	// The compatibility level for schema evolution (BACKWARD, BACKWARD_TRANSITIVE, FORWARD, FORWARD_TRANSITIVE, FULL, FULL_TRANSITIVE, NONE). Defaults to BACKWARD.
	Compatibility *string `pulumi:"compatibility"`
	// The SASL password for Schema Registry authentication. Deprecated: use passwordWo instead.
	//
	// Deprecated: Use passwordWo instead to avoid storing password in Terraform state
	Password *string `pulumi:"password"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// The SASL password for Schema Registry authentication (write-only, not stored in state). Requires Terraform 1.11+.
	PasswordWo *string `pulumi:"passwordWo"`
	// Version number for password_wo. Increment this value to trigger a password update when using password_wo.
	PasswordWoVersion *int `pulumi:"passwordWoVersion"`
	// List of schema references.
	References []SchemaReference `pulumi:"references"`
	// The schema definition in JSON format.
	Schema string `pulumi:"schema"`
	// The type of schema (AVRO, JSON, PROTOBUF).
	SchemaType *string `pulumi:"schemaType"`
	// The subject name for the schema.
	Subject string `pulumi:"subject"`
	// The SASL username for Schema Registry authentication.
	Username string `pulumi:"username"`
}

// The set of arguments for constructing a Schema resource.
type SchemaArgs struct {
	// When enabled, prevents the resource from being deleted if the cluster is unreachable. When disabled (default), the resource will be removed from state without attempting deletion when the cluster is unreachable.
	AllowDeletion pulumi.BoolPtrInput
	// The ID of the cluster where the schema is stored.
	ClusterId pulumi.StringInput
	// The compatibility level for schema evolution (BACKWARD, BACKWARD_TRANSITIVE, FORWARD, FORWARD_TRANSITIVE, FULL, FULL_TRANSITIVE, NONE). Defaults to BACKWARD.
	Compatibility pulumi.StringPtrInput
	// The SASL password for Schema Registry authentication. Deprecated: use passwordWo instead.
	//
	// Deprecated: Use passwordWo instead to avoid storing password in Terraform state
	Password pulumi.StringPtrInput
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// The SASL password for Schema Registry authentication (write-only, not stored in state). Requires Terraform 1.11+.
	PasswordWo pulumi.StringPtrInput
	// Version number for password_wo. Increment this value to trigger a password update when using password_wo.
	PasswordWoVersion pulumi.IntPtrInput
	// List of schema references.
	References SchemaReferenceArrayInput
	// The schema definition in JSON format.
	Schema pulumi.StringInput
	// The type of schema (AVRO, JSON, PROTOBUF).
	SchemaType pulumi.StringPtrInput
	// The subject name for the schema.
	Subject pulumi.StringInput
	// The SASL username for Schema Registry authentication.
	Username pulumi.StringInput
}

func (SchemaArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*schemaArgs)(nil)).Elem()
}

type SchemaInput interface {
	pulumi.Input

	ToSchemaOutput() SchemaOutput
	ToSchemaOutputWithContext(ctx context.Context) SchemaOutput
}

func (*Schema) ElementType() reflect.Type {
	return reflect.TypeOf((**Schema)(nil)).Elem()
}

func (i *Schema) ToSchemaOutput() SchemaOutput {
	return i.ToSchemaOutputWithContext(context.Background())
}

func (i *Schema) ToSchemaOutputWithContext(ctx context.Context) SchemaOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SchemaOutput)
}

// SchemaArrayInput is an input type that accepts SchemaArray and SchemaArrayOutput values.
// You can construct a concrete instance of `SchemaArrayInput` via:
//
//	SchemaArray{ SchemaArgs{...} }
type SchemaArrayInput interface {
	pulumi.Input

	ToSchemaArrayOutput() SchemaArrayOutput
	ToSchemaArrayOutputWithContext(context.Context) SchemaArrayOutput
}

type SchemaArray []SchemaInput

func (SchemaArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Schema)(nil)).Elem()
}

func (i SchemaArray) ToSchemaArrayOutput() SchemaArrayOutput {
	return i.ToSchemaArrayOutputWithContext(context.Background())
}

func (i SchemaArray) ToSchemaArrayOutputWithContext(ctx context.Context) SchemaArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SchemaArrayOutput)
}

// SchemaMapInput is an input type that accepts SchemaMap and SchemaMapOutput values.
// You can construct a concrete instance of `SchemaMapInput` via:
//
//	SchemaMap{ "key": SchemaArgs{...} }
type SchemaMapInput interface {
	pulumi.Input

	ToSchemaMapOutput() SchemaMapOutput
	ToSchemaMapOutputWithContext(context.Context) SchemaMapOutput
}

type SchemaMap map[string]SchemaInput

func (SchemaMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Schema)(nil)).Elem()
}

func (i SchemaMap) ToSchemaMapOutput() SchemaMapOutput {
	return i.ToSchemaMapOutputWithContext(context.Background())
}

func (i SchemaMap) ToSchemaMapOutputWithContext(ctx context.Context) SchemaMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SchemaMapOutput)
}

type SchemaOutput struct{ *pulumi.OutputState }

func (SchemaOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Schema)(nil)).Elem()
}

func (o SchemaOutput) ToSchemaOutput() SchemaOutput {
	return o
}

func (o SchemaOutput) ToSchemaOutputWithContext(ctx context.Context) SchemaOutput {
	return o
}

// When enabled, prevents the resource from being deleted if the cluster is unreachable. When disabled (default), the resource will be removed from state without attempting deletion when the cluster is unreachable.
func (o SchemaOutput) AllowDeletion() pulumi.BoolOutput {
	return o.ApplyT(func(v *Schema) pulumi.BoolOutput { return v.AllowDeletion }).(pulumi.BoolOutput)
}

// The ID of the cluster where the schema is stored.
func (o SchemaOutput) ClusterId() pulumi.StringOutput {
	return o.ApplyT(func(v *Schema) pulumi.StringOutput { return v.ClusterId }).(pulumi.StringOutput)
}

// The compatibility level for schema evolution (BACKWARD, BACKWARD_TRANSITIVE, FORWARD, FORWARD_TRANSITIVE, FULL, FULL_TRANSITIVE, NONE). Defaults to BACKWARD.
func (o SchemaOutput) Compatibility() pulumi.StringOutput {
	return o.ApplyT(func(v *Schema) pulumi.StringOutput { return v.Compatibility }).(pulumi.StringOutput)
}

// The SASL password for Schema Registry authentication. Deprecated: use passwordWo instead.
//
// Deprecated: Use passwordWo instead to avoid storing password in Terraform state
func (o SchemaOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Schema) pulumi.StringPtrOutput { return v.Password }).(pulumi.StringPtrOutput)
}

// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
// The SASL password for Schema Registry authentication (write-only, not stored in state). Requires Terraform 1.11+.
func (o SchemaOutput) PasswordWo() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Schema) pulumi.StringPtrOutput { return v.PasswordWo }).(pulumi.StringPtrOutput)
}

// Version number for password_wo. Increment this value to trigger a password update when using password_wo.
func (o SchemaOutput) PasswordWoVersion() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Schema) pulumi.IntPtrOutput { return v.PasswordWoVersion }).(pulumi.IntPtrOutput)
}

// List of schema references.
func (o SchemaOutput) References() SchemaReferenceArrayOutput {
	return o.ApplyT(func(v *Schema) SchemaReferenceArrayOutput { return v.References }).(SchemaReferenceArrayOutput)
}

// The schema definition in JSON format.
func (o SchemaOutput) Schema() pulumi.StringOutput {
	return o.ApplyT(func(v *Schema) pulumi.StringOutput { return v.Schema }).(pulumi.StringOutput)
}

// The type of schema (AVRO, JSON, PROTOBUF).
func (o SchemaOutput) SchemaType() pulumi.StringOutput {
	return o.ApplyT(func(v *Schema) pulumi.StringOutput { return v.SchemaType }).(pulumi.StringOutput)
}

// The subject name for the schema.
func (o SchemaOutput) Subject() pulumi.StringOutput {
	return o.ApplyT(func(v *Schema) pulumi.StringOutput { return v.Subject }).(pulumi.StringOutput)
}

// The SASL username for Schema Registry authentication.
func (o SchemaOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v *Schema) pulumi.StringOutput { return v.Username }).(pulumi.StringOutput)
}

// The version of the schema.
func (o SchemaOutput) Version() pulumi.IntOutput {
	return o.ApplyT(func(v *Schema) pulumi.IntOutput { return v.Version }).(pulumi.IntOutput)
}

type SchemaArrayOutput struct{ *pulumi.OutputState }

func (SchemaArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Schema)(nil)).Elem()
}

func (o SchemaArrayOutput) ToSchemaArrayOutput() SchemaArrayOutput {
	return o
}

func (o SchemaArrayOutput) ToSchemaArrayOutputWithContext(ctx context.Context) SchemaArrayOutput {
	return o
}

func (o SchemaArrayOutput) Index(i pulumi.IntInput) SchemaOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Schema {
		return vs[0].([]*Schema)[vs[1].(int)]
	}).(SchemaOutput)
}

type SchemaMapOutput struct{ *pulumi.OutputState }

func (SchemaMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Schema)(nil)).Elem()
}

func (o SchemaMapOutput) ToSchemaMapOutput() SchemaMapOutput {
	return o
}

func (o SchemaMapOutput) ToSchemaMapOutputWithContext(ctx context.Context) SchemaMapOutput {
	return o
}

func (o SchemaMapOutput) MapIndex(k pulumi.StringInput) SchemaOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Schema {
		return vs[0].(map[string]*Schema)[vs[1].(string)]
	}).(SchemaOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SchemaInput)(nil)).Elem(), &Schema{})
	pulumi.RegisterInputType(reflect.TypeOf((*SchemaArrayInput)(nil)).Elem(), SchemaArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SchemaMapInput)(nil)).Elem(), SchemaMap{})
	pulumi.RegisterOutputType(SchemaOutput{})
	pulumi.RegisterOutputType(SchemaArrayOutput{})
	pulumi.RegisterOutputType(SchemaMapOutput{})
}
