// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package redpanda

import (
	"context"
	"reflect"

	"errors"
	"github.com/primait/pulumi-redpanda/sdk/go/redpanda/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ServerlessPrivateLink struct {
	pulumi.CustomResourceState

	// Allows deletion of the serverless private link. Defaults to false.
	AllowDeletion pulumi.BoolOutput `pulumi:"allowDeletion"`
	// Cloud provider (aws)
	CloudProvider pulumi.StringOutput `pulumi:"cloudProvider"`
	// Cloud provider specific configuration
	CloudProviderConfig ServerlessPrivateLinkCloudProviderConfigOutput `pulumi:"cloudProviderConfig"`
	// Timestamp when the serverless private link was created
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Name of the serverless private link
	Name pulumi.StringOutput `pulumi:"name"`
	// The ID of the Resource Group in which to create the serverless private link
	ResourceGroupId pulumi.StringOutput `pulumi:"resourceGroupId"`
	// Redpanda serverless region
	ServerlessRegion pulumi.StringOutput `pulumi:"serverlessRegion"`
	// Current state of the serverless private link (STATE_CREATING, STATE_READY, STATE_DELETING, STATE_FAILED, STATE_UPDATING)
	State pulumi.StringOutput `pulumi:"state"`
	// Cloud provider specific status information
	Status ServerlessPrivateLinkStatusOutput `pulumi:"status"`
	// Timestamp when the serverless private link was last updated. This value changes on every update operation.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
}

// NewServerlessPrivateLink registers a new resource with the given unique name, arguments, and options.
func NewServerlessPrivateLink(ctx *pulumi.Context,
	name string, args *ServerlessPrivateLinkArgs, opts ...pulumi.ResourceOption) (*ServerlessPrivateLink, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.CloudProvider == nil {
		return nil, errors.New("invalid value for required argument 'CloudProvider'")
	}
	if args.CloudProviderConfig == nil {
		return nil, errors.New("invalid value for required argument 'CloudProviderConfig'")
	}
	if args.ResourceGroupId == nil {
		return nil, errors.New("invalid value for required argument 'ResourceGroupId'")
	}
	if args.ServerlessRegion == nil {
		return nil, errors.New("invalid value for required argument 'ServerlessRegion'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ServerlessPrivateLink
	err := ctx.RegisterResource("redpanda:index/serverlessPrivateLink:ServerlessPrivateLink", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetServerlessPrivateLink gets an existing ServerlessPrivateLink resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetServerlessPrivateLink(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ServerlessPrivateLinkState, opts ...pulumi.ResourceOption) (*ServerlessPrivateLink, error) {
	var resource ServerlessPrivateLink
	err := ctx.ReadResource("redpanda:index/serverlessPrivateLink:ServerlessPrivateLink", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ServerlessPrivateLink resources.
type serverlessPrivateLinkState struct {
	// Allows deletion of the serverless private link. Defaults to false.
	AllowDeletion *bool `pulumi:"allowDeletion"`
	// Cloud provider (aws)
	CloudProvider *string `pulumi:"cloudProvider"`
	// Cloud provider specific configuration
	CloudProviderConfig *ServerlessPrivateLinkCloudProviderConfig `pulumi:"cloudProviderConfig"`
	// Timestamp when the serverless private link was created
	CreatedAt *string `pulumi:"createdAt"`
	// Name of the serverless private link
	Name *string `pulumi:"name"`
	// The ID of the Resource Group in which to create the serverless private link
	ResourceGroupId *string `pulumi:"resourceGroupId"`
	// Redpanda serverless region
	ServerlessRegion *string `pulumi:"serverlessRegion"`
	// Current state of the serverless private link (STATE_CREATING, STATE_READY, STATE_DELETING, STATE_FAILED, STATE_UPDATING)
	State *string `pulumi:"state"`
	// Cloud provider specific status information
	Status *ServerlessPrivateLinkStatus `pulumi:"status"`
	// Timestamp when the serverless private link was last updated. This value changes on every update operation.
	UpdatedAt *string `pulumi:"updatedAt"`
}

type ServerlessPrivateLinkState struct {
	// Allows deletion of the serverless private link. Defaults to false.
	AllowDeletion pulumi.BoolPtrInput
	// Cloud provider (aws)
	CloudProvider pulumi.StringPtrInput
	// Cloud provider specific configuration
	CloudProviderConfig ServerlessPrivateLinkCloudProviderConfigPtrInput
	// Timestamp when the serverless private link was created
	CreatedAt pulumi.StringPtrInput
	// Name of the serverless private link
	Name pulumi.StringPtrInput
	// The ID of the Resource Group in which to create the serverless private link
	ResourceGroupId pulumi.StringPtrInput
	// Redpanda serverless region
	ServerlessRegion pulumi.StringPtrInput
	// Current state of the serverless private link (STATE_CREATING, STATE_READY, STATE_DELETING, STATE_FAILED, STATE_UPDATING)
	State pulumi.StringPtrInput
	// Cloud provider specific status information
	Status ServerlessPrivateLinkStatusPtrInput
	// Timestamp when the serverless private link was last updated. This value changes on every update operation.
	UpdatedAt pulumi.StringPtrInput
}

func (ServerlessPrivateLinkState) ElementType() reflect.Type {
	return reflect.TypeOf((*serverlessPrivateLinkState)(nil)).Elem()
}

type serverlessPrivateLinkArgs struct {
	// Allows deletion of the serverless private link. Defaults to false.
	AllowDeletion *bool `pulumi:"allowDeletion"`
	// Cloud provider (aws)
	CloudProvider string `pulumi:"cloudProvider"`
	// Cloud provider specific configuration
	CloudProviderConfig ServerlessPrivateLinkCloudProviderConfig `pulumi:"cloudProviderConfig"`
	// Name of the serverless private link
	Name *string `pulumi:"name"`
	// The ID of the Resource Group in which to create the serverless private link
	ResourceGroupId string `pulumi:"resourceGroupId"`
	// Redpanda serverless region
	ServerlessRegion string `pulumi:"serverlessRegion"`
}

// The set of arguments for constructing a ServerlessPrivateLink resource.
type ServerlessPrivateLinkArgs struct {
	// Allows deletion of the serverless private link. Defaults to false.
	AllowDeletion pulumi.BoolPtrInput
	// Cloud provider (aws)
	CloudProvider pulumi.StringInput
	// Cloud provider specific configuration
	CloudProviderConfig ServerlessPrivateLinkCloudProviderConfigInput
	// Name of the serverless private link
	Name pulumi.StringPtrInput
	// The ID of the Resource Group in which to create the serverless private link
	ResourceGroupId pulumi.StringInput
	// Redpanda serverless region
	ServerlessRegion pulumi.StringInput
}

func (ServerlessPrivateLinkArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*serverlessPrivateLinkArgs)(nil)).Elem()
}

type ServerlessPrivateLinkInput interface {
	pulumi.Input

	ToServerlessPrivateLinkOutput() ServerlessPrivateLinkOutput
	ToServerlessPrivateLinkOutputWithContext(ctx context.Context) ServerlessPrivateLinkOutput
}

func (*ServerlessPrivateLink) ElementType() reflect.Type {
	return reflect.TypeOf((**ServerlessPrivateLink)(nil)).Elem()
}

func (i *ServerlessPrivateLink) ToServerlessPrivateLinkOutput() ServerlessPrivateLinkOutput {
	return i.ToServerlessPrivateLinkOutputWithContext(context.Background())
}

func (i *ServerlessPrivateLink) ToServerlessPrivateLinkOutputWithContext(ctx context.Context) ServerlessPrivateLinkOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServerlessPrivateLinkOutput)
}

// ServerlessPrivateLinkArrayInput is an input type that accepts ServerlessPrivateLinkArray and ServerlessPrivateLinkArrayOutput values.
// You can construct a concrete instance of `ServerlessPrivateLinkArrayInput` via:
//
//	ServerlessPrivateLinkArray{ ServerlessPrivateLinkArgs{...} }
type ServerlessPrivateLinkArrayInput interface {
	pulumi.Input

	ToServerlessPrivateLinkArrayOutput() ServerlessPrivateLinkArrayOutput
	ToServerlessPrivateLinkArrayOutputWithContext(context.Context) ServerlessPrivateLinkArrayOutput
}

type ServerlessPrivateLinkArray []ServerlessPrivateLinkInput

func (ServerlessPrivateLinkArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ServerlessPrivateLink)(nil)).Elem()
}

func (i ServerlessPrivateLinkArray) ToServerlessPrivateLinkArrayOutput() ServerlessPrivateLinkArrayOutput {
	return i.ToServerlessPrivateLinkArrayOutputWithContext(context.Background())
}

func (i ServerlessPrivateLinkArray) ToServerlessPrivateLinkArrayOutputWithContext(ctx context.Context) ServerlessPrivateLinkArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServerlessPrivateLinkArrayOutput)
}

// ServerlessPrivateLinkMapInput is an input type that accepts ServerlessPrivateLinkMap and ServerlessPrivateLinkMapOutput values.
// You can construct a concrete instance of `ServerlessPrivateLinkMapInput` via:
//
//	ServerlessPrivateLinkMap{ "key": ServerlessPrivateLinkArgs{...} }
type ServerlessPrivateLinkMapInput interface {
	pulumi.Input

	ToServerlessPrivateLinkMapOutput() ServerlessPrivateLinkMapOutput
	ToServerlessPrivateLinkMapOutputWithContext(context.Context) ServerlessPrivateLinkMapOutput
}

type ServerlessPrivateLinkMap map[string]ServerlessPrivateLinkInput

func (ServerlessPrivateLinkMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ServerlessPrivateLink)(nil)).Elem()
}

func (i ServerlessPrivateLinkMap) ToServerlessPrivateLinkMapOutput() ServerlessPrivateLinkMapOutput {
	return i.ToServerlessPrivateLinkMapOutputWithContext(context.Background())
}

func (i ServerlessPrivateLinkMap) ToServerlessPrivateLinkMapOutputWithContext(ctx context.Context) ServerlessPrivateLinkMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServerlessPrivateLinkMapOutput)
}

type ServerlessPrivateLinkOutput struct{ *pulumi.OutputState }

func (ServerlessPrivateLinkOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ServerlessPrivateLink)(nil)).Elem()
}

func (o ServerlessPrivateLinkOutput) ToServerlessPrivateLinkOutput() ServerlessPrivateLinkOutput {
	return o
}

func (o ServerlessPrivateLinkOutput) ToServerlessPrivateLinkOutputWithContext(ctx context.Context) ServerlessPrivateLinkOutput {
	return o
}

// Allows deletion of the serverless private link. Defaults to false.
func (o ServerlessPrivateLinkOutput) AllowDeletion() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerlessPrivateLink) pulumi.BoolOutput { return v.AllowDeletion }).(pulumi.BoolOutput)
}

// Cloud provider (aws)
func (o ServerlessPrivateLinkOutput) CloudProvider() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerlessPrivateLink) pulumi.StringOutput { return v.CloudProvider }).(pulumi.StringOutput)
}

// Cloud provider specific configuration
func (o ServerlessPrivateLinkOutput) CloudProviderConfig() ServerlessPrivateLinkCloudProviderConfigOutput {
	return o.ApplyT(func(v *ServerlessPrivateLink) ServerlessPrivateLinkCloudProviderConfigOutput {
		return v.CloudProviderConfig
	}).(ServerlessPrivateLinkCloudProviderConfigOutput)
}

// Timestamp when the serverless private link was created
func (o ServerlessPrivateLinkOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerlessPrivateLink) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Name of the serverless private link
func (o ServerlessPrivateLinkOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerlessPrivateLink) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The ID of the Resource Group in which to create the serverless private link
func (o ServerlessPrivateLinkOutput) ResourceGroupId() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerlessPrivateLink) pulumi.StringOutput { return v.ResourceGroupId }).(pulumi.StringOutput)
}

// Redpanda serverless region
func (o ServerlessPrivateLinkOutput) ServerlessRegion() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerlessPrivateLink) pulumi.StringOutput { return v.ServerlessRegion }).(pulumi.StringOutput)
}

// Current state of the serverless private link (STATE_CREATING, STATE_READY, STATE_DELETING, STATE_FAILED, STATE_UPDATING)
func (o ServerlessPrivateLinkOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerlessPrivateLink) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

// Cloud provider specific status information
func (o ServerlessPrivateLinkOutput) Status() ServerlessPrivateLinkStatusOutput {
	return o.ApplyT(func(v *ServerlessPrivateLink) ServerlessPrivateLinkStatusOutput { return v.Status }).(ServerlessPrivateLinkStatusOutput)
}

// Timestamp when the serverless private link was last updated. This value changes on every update operation.
func (o ServerlessPrivateLinkOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerlessPrivateLink) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

type ServerlessPrivateLinkArrayOutput struct{ *pulumi.OutputState }

func (ServerlessPrivateLinkArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ServerlessPrivateLink)(nil)).Elem()
}

func (o ServerlessPrivateLinkArrayOutput) ToServerlessPrivateLinkArrayOutput() ServerlessPrivateLinkArrayOutput {
	return o
}

func (o ServerlessPrivateLinkArrayOutput) ToServerlessPrivateLinkArrayOutputWithContext(ctx context.Context) ServerlessPrivateLinkArrayOutput {
	return o
}

func (o ServerlessPrivateLinkArrayOutput) Index(i pulumi.IntInput) ServerlessPrivateLinkOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ServerlessPrivateLink {
		return vs[0].([]*ServerlessPrivateLink)[vs[1].(int)]
	}).(ServerlessPrivateLinkOutput)
}

type ServerlessPrivateLinkMapOutput struct{ *pulumi.OutputState }

func (ServerlessPrivateLinkMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ServerlessPrivateLink)(nil)).Elem()
}

func (o ServerlessPrivateLinkMapOutput) ToServerlessPrivateLinkMapOutput() ServerlessPrivateLinkMapOutput {
	return o
}

func (o ServerlessPrivateLinkMapOutput) ToServerlessPrivateLinkMapOutputWithContext(ctx context.Context) ServerlessPrivateLinkMapOutput {
	return o
}

func (o ServerlessPrivateLinkMapOutput) MapIndex(k pulumi.StringInput) ServerlessPrivateLinkOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ServerlessPrivateLink {
		return vs[0].(map[string]*ServerlessPrivateLink)[vs[1].(string)]
	}).(ServerlessPrivateLinkOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ServerlessPrivateLinkInput)(nil)).Elem(), &ServerlessPrivateLink{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServerlessPrivateLinkArrayInput)(nil)).Elem(), ServerlessPrivateLinkArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServerlessPrivateLinkMapInput)(nil)).Elem(), ServerlessPrivateLinkMap{})
	pulumi.RegisterOutputType(ServerlessPrivateLinkOutput{})
	pulumi.RegisterOutputType(ServerlessPrivateLinkArrayOutput{})
	pulumi.RegisterOutputType(ServerlessPrivateLinkMapOutput{})
}
