// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package redpanda

import (
	"context"
	"reflect"

	"errors"
	"github.com/primait/pulumi-redpanda/sdk/go/redpanda/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type User struct {
	pulumi.CustomResourceState

	// Allows deletion of the user. If false, the user cannot be deleted and the resource will be removed from the state on destruction. Defaults to false.
	AllowDeletion pulumi.BoolOutput `pulumi:"allowDeletion"`
	// The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports
	ClusterApiUrl pulumi.StringOutput `pulumi:"clusterApiUrl"`
	// Which authentication method to use, see https://docs.redpanda.com/current/manage/security/authentication/ for more information
	Mechanism pulumi.StringPtrOutput `pulumi:"mechanism"`
	// Name of the user, must be unique
	Name pulumi.StringOutput `pulumi:"name"`
	// Password of the user. Deprecated: use passwordWo instead to avoid storing password in state.
	//
	// Deprecated: Use passwordWo instead to avoid storing password in Terraform state
	Password pulumi.StringPtrOutput `pulumi:"password"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Password of the user (write-only, not stored in state). Requires Terraform 1.11+. Either password or passwordWo must be set.
	PasswordWo pulumi.StringPtrOutput `pulumi:"passwordWo"`
	// Version number for password_wo. Increment this value to trigger a password update when using password_wo.
	PasswordWoVersion pulumi.IntPtrOutput `pulumi:"passwordWoVersion"`
}

// NewUser registers a new resource with the given unique name, arguments, and options.
func NewUser(ctx *pulumi.Context,
	name string, args *UserArgs, opts ...pulumi.ResourceOption) (*User, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClusterApiUrl == nil {
		return nil, errors.New("invalid value for required argument 'ClusterApiUrl'")
	}
	if args.Password != nil {
		args.Password = pulumi.ToSecret(args.Password).(pulumi.StringPtrInput)
	}
	if args.PasswordWo != nil {
		args.PasswordWo = pulumi.ToSecret(args.PasswordWo).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"password",
		"passwordWo",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource User
	err := ctx.RegisterResource("redpanda:index/user:User", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetUser gets an existing User resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetUser(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *UserState, opts ...pulumi.ResourceOption) (*User, error) {
	var resource User
	err := ctx.ReadResource("redpanda:index/user:User", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering User resources.
type userState struct {
	// Allows deletion of the user. If false, the user cannot be deleted and the resource will be removed from the state on destruction. Defaults to false.
	AllowDeletion *bool `pulumi:"allowDeletion"`
	// The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports
	ClusterApiUrl *string `pulumi:"clusterApiUrl"`
	// Which authentication method to use, see https://docs.redpanda.com/current/manage/security/authentication/ for more information
	Mechanism *string `pulumi:"mechanism"`
	// Name of the user, must be unique
	Name *string `pulumi:"name"`
	// Password of the user. Deprecated: use passwordWo instead to avoid storing password in state.
	//
	// Deprecated: Use passwordWo instead to avoid storing password in Terraform state
	Password *string `pulumi:"password"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Password of the user (write-only, not stored in state). Requires Terraform 1.11+. Either password or passwordWo must be set.
	PasswordWo *string `pulumi:"passwordWo"`
	// Version number for password_wo. Increment this value to trigger a password update when using password_wo.
	PasswordWoVersion *int `pulumi:"passwordWoVersion"`
}

type UserState struct {
	// Allows deletion of the user. If false, the user cannot be deleted and the resource will be removed from the state on destruction. Defaults to false.
	AllowDeletion pulumi.BoolPtrInput
	// The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports
	ClusterApiUrl pulumi.StringPtrInput
	// Which authentication method to use, see https://docs.redpanda.com/current/manage/security/authentication/ for more information
	Mechanism pulumi.StringPtrInput
	// Name of the user, must be unique
	Name pulumi.StringPtrInput
	// Password of the user. Deprecated: use passwordWo instead to avoid storing password in state.
	//
	// Deprecated: Use passwordWo instead to avoid storing password in Terraform state
	Password pulumi.StringPtrInput
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Password of the user (write-only, not stored in state). Requires Terraform 1.11+. Either password or passwordWo must be set.
	PasswordWo pulumi.StringPtrInput
	// Version number for password_wo. Increment this value to trigger a password update when using password_wo.
	PasswordWoVersion pulumi.IntPtrInput
}

func (UserState) ElementType() reflect.Type {
	return reflect.TypeOf((*userState)(nil)).Elem()
}

type userArgs struct {
	// Allows deletion of the user. If false, the user cannot be deleted and the resource will be removed from the state on destruction. Defaults to false.
	AllowDeletion *bool `pulumi:"allowDeletion"`
	// The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports
	ClusterApiUrl string `pulumi:"clusterApiUrl"`
	// Which authentication method to use, see https://docs.redpanda.com/current/manage/security/authentication/ for more information
	Mechanism *string `pulumi:"mechanism"`
	// Name of the user, must be unique
	Name *string `pulumi:"name"`
	// Password of the user. Deprecated: use passwordWo instead to avoid storing password in state.
	//
	// Deprecated: Use passwordWo instead to avoid storing password in Terraform state
	Password *string `pulumi:"password"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Password of the user (write-only, not stored in state). Requires Terraform 1.11+. Either password or passwordWo must be set.
	PasswordWo *string `pulumi:"passwordWo"`
	// Version number for password_wo. Increment this value to trigger a password update when using password_wo.
	PasswordWoVersion *int `pulumi:"passwordWoVersion"`
}

// The set of arguments for constructing a User resource.
type UserArgs struct {
	// Allows deletion of the user. If false, the user cannot be deleted and the resource will be removed from the state on destruction. Defaults to false.
	AllowDeletion pulumi.BoolPtrInput
	// The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports
	ClusterApiUrl pulumi.StringInput
	// Which authentication method to use, see https://docs.redpanda.com/current/manage/security/authentication/ for more information
	Mechanism pulumi.StringPtrInput
	// Name of the user, must be unique
	Name pulumi.StringPtrInput
	// Password of the user. Deprecated: use passwordWo instead to avoid storing password in state.
	//
	// Deprecated: Use passwordWo instead to avoid storing password in Terraform state
	Password pulumi.StringPtrInput
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Password of the user (write-only, not stored in state). Requires Terraform 1.11+. Either password or passwordWo must be set.
	PasswordWo pulumi.StringPtrInput
	// Version number for password_wo. Increment this value to trigger a password update when using password_wo.
	PasswordWoVersion pulumi.IntPtrInput
}

func (UserArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*userArgs)(nil)).Elem()
}

type UserInput interface {
	pulumi.Input

	ToUserOutput() UserOutput
	ToUserOutputWithContext(ctx context.Context) UserOutput
}

func (*User) ElementType() reflect.Type {
	return reflect.TypeOf((**User)(nil)).Elem()
}

func (i *User) ToUserOutput() UserOutput {
	return i.ToUserOutputWithContext(context.Background())
}

func (i *User) ToUserOutputWithContext(ctx context.Context) UserOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserOutput)
}

// UserArrayInput is an input type that accepts UserArray and UserArrayOutput values.
// You can construct a concrete instance of `UserArrayInput` via:
//
//	UserArray{ UserArgs{...} }
type UserArrayInput interface {
	pulumi.Input

	ToUserArrayOutput() UserArrayOutput
	ToUserArrayOutputWithContext(context.Context) UserArrayOutput
}

type UserArray []UserInput

func (UserArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*User)(nil)).Elem()
}

func (i UserArray) ToUserArrayOutput() UserArrayOutput {
	return i.ToUserArrayOutputWithContext(context.Background())
}

func (i UserArray) ToUserArrayOutputWithContext(ctx context.Context) UserArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserArrayOutput)
}

// UserMapInput is an input type that accepts UserMap and UserMapOutput values.
// You can construct a concrete instance of `UserMapInput` via:
//
//	UserMap{ "key": UserArgs{...} }
type UserMapInput interface {
	pulumi.Input

	ToUserMapOutput() UserMapOutput
	ToUserMapOutputWithContext(context.Context) UserMapOutput
}

type UserMap map[string]UserInput

func (UserMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*User)(nil)).Elem()
}

func (i UserMap) ToUserMapOutput() UserMapOutput {
	return i.ToUserMapOutputWithContext(context.Background())
}

func (i UserMap) ToUserMapOutputWithContext(ctx context.Context) UserMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserMapOutput)
}

type UserOutput struct{ *pulumi.OutputState }

func (UserOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**User)(nil)).Elem()
}

func (o UserOutput) ToUserOutput() UserOutput {
	return o
}

func (o UserOutput) ToUserOutputWithContext(ctx context.Context) UserOutput {
	return o
}

// Allows deletion of the user. If false, the user cannot be deleted and the resource will be removed from the state on destruction. Defaults to false.
func (o UserOutput) AllowDeletion() pulumi.BoolOutput {
	return o.ApplyT(func(v *User) pulumi.BoolOutput { return v.AllowDeletion }).(pulumi.BoolOutput)
}

// The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports
func (o UserOutput) ClusterApiUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.ClusterApiUrl }).(pulumi.StringOutput)
}

// Which authentication method to use, see https://docs.redpanda.com/current/manage/security/authentication/ for more information
func (o UserOutput) Mechanism() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.Mechanism }).(pulumi.StringPtrOutput)
}

// Name of the user, must be unique
func (o UserOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Password of the user. Deprecated: use passwordWo instead to avoid storing password in state.
//
// Deprecated: Use passwordWo instead to avoid storing password in Terraform state
func (o UserOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.Password }).(pulumi.StringPtrOutput)
}

// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
// Password of the user (write-only, not stored in state). Requires Terraform 1.11+. Either password or passwordWo must be set.
func (o UserOutput) PasswordWo() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.PasswordWo }).(pulumi.StringPtrOutput)
}

// Version number for password_wo. Increment this value to trigger a password update when using password_wo.
func (o UserOutput) PasswordWoVersion() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *User) pulumi.IntPtrOutput { return v.PasswordWoVersion }).(pulumi.IntPtrOutput)
}

type UserArrayOutput struct{ *pulumi.OutputState }

func (UserArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*User)(nil)).Elem()
}

func (o UserArrayOutput) ToUserArrayOutput() UserArrayOutput {
	return o
}

func (o UserArrayOutput) ToUserArrayOutputWithContext(ctx context.Context) UserArrayOutput {
	return o
}

func (o UserArrayOutput) Index(i pulumi.IntInput) UserOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *User {
		return vs[0].([]*User)[vs[1].(int)]
	}).(UserOutput)
}

type UserMapOutput struct{ *pulumi.OutputState }

func (UserMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*User)(nil)).Elem()
}

func (o UserMapOutput) ToUserMapOutput() UserMapOutput {
	return o
}

func (o UserMapOutput) ToUserMapOutputWithContext(ctx context.Context) UserMapOutput {
	return o
}

func (o UserMapOutput) MapIndex(k pulumi.StringInput) UserOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *User {
		return vs[0].(map[string]*User)[vs[1].(string)]
	}).(UserOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*UserInput)(nil)).Elem(), &User{})
	pulumi.RegisterInputType(reflect.TypeOf((*UserArrayInput)(nil)).Elem(), UserArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*UserMapInput)(nil)).Elem(), UserMap{})
	pulumi.RegisterOutputType(UserOutput{})
	pulumi.RegisterOutputType(UserArrayOutput{})
	pulumi.RegisterOutputType(UserMapOutput{})
}
